### PR TITLE
Trying to improve USB-PD

### PR DESCRIPTION
**Pull request by Ralim**
So this started with poking the PD stack to bring up PPS support.
Then a lot of back and forth in debugging quirks with having that be stable.

Now this works on all of my PD testing devices here so far.

I'm hoping this may help with some of the PD issues, but not entirely sure.

I would love any feedback on if things work of fail after these changes for you, since I did to a fair bit of poking around to flush out quirks

Key changes:

* PPS support (But will only be selected when provides more power than fixed)
* Removed the mostly pointless rx thread and folded it into the irq handler thread
* Bit of code de-dup
* Bit of code cleanup

This may help with the following issues:

* #848
* #838
* #762
* #683
If you have a PD equipped device (TS80P, Pinecil) and you could try the ci builds here: https://github.com/Ralim/IronOS/actions/runs/718426908 that would be fantastic :)

### CODE REVIEW

**Comment by zainahm3d** [comment]
Hi, I believe this has fixed some of the PD reset issues for my Pinecil. Previously I had constant resets with my 96W Apple adapter, and off of my LG Ultrafine Display's PD output. The apple adapter now works fine, but the constant (2hz) reset with the Ultrafine persists. Of course I don't really care if it works with the Ultrafine but I figured it was worth checking.

**Comment by Ralim** [comment]
That is fantastic feedback for the Apple charger, have had a rough time with them since all the ones my friends have, appear to work fine :/ 

Ah screens are interesting.

I have access to a Dell monitor that did the same thing but haven't yet been able to check it. Previously it was causing a reset because the iron wasn't quite responding in time, so this could still be the same issue. I'm planning to test this a bit more when I have access to it again in a week or so.

Good that no regressions so far at least 😅

**Comment by alvinhochun** [comment]
Tested with a Pinecil:

I can confirm that this did not break powering on a Lenovo 65W power adapter (ThinkPad), a Nintendo Switch power adapter and a Google Pixel 3a power adapter (9V/2A).

Also, I have a Apple 18W (9V/2A) power adapter that would continuously reset on previous firmwares, and it doesn't reset with this PR.

**Comment by pedrolamas** [comment]
Tested with my TS80P + [CHOETECH PD 61W USB C Charger](https://smile.amazon.co.uk/gp/product/B0829P294W/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1), worked flawlesly!

I had to solder some stuff 2 days again, and it was painful to get the iron to even turn on with the latest stable release of IronOS... I've now just flashed the CI build and it worked perfectly at first try!!

**Comment by xxv** [comment]
I flashed the image from [this build](https://github.com/Ralim/IronOS/actions/runs/718874134) to my TS80P and unfortunately don't have 100% success. The [two power supplies that were misbehaving the most](https://github.com/Ralim/IronOS/issues/683#issuecomment-814124111) (Anker 30W PD) will boot sometimes (1-5 boot loops) and when it does, negotiates 9V. The Lenovo charger will also boot after 2-3 tries and only negotiates 5V.

**Comment by alvinhochun** [comment]
@xxv Curious you have issues with the Lenovo 65W charger. Mine works fine 100% of the time. It is a model ADLX65YCC3A (FRU 01FR026, MFG 2018/07, made by Chicony).

**Comment by DanNixon** [comment]
This fixes issues I had with a Pinecil on an 45W Exibel power supply. Would previously get stuck in the reboot loop during negotiation, now works fine.

**Comment by pedrolamas** [comment]
> I flashed the image from [this build](https://github.com/Ralim/IronOS/actions/runs/718874134) to my TS80P and unfortunately don't have 100% success.

Might be worth trying the build from the first post, that's the one I tried and it worked fine!

**Comment by xxv** [comment]
> @xxv Curious you have issues with the Lenovo 65W charger. Mine works fine 100% of the time. It is a model ADLX65YCC3A (FRU 01FR026, MFG 2018/07, made by Chicony).

Is this a Pinecil or TS80P? As there could certainly be differences between the two.

**Comment by xxv** [comment]
> > I flashed the image from [this build](https://github.com/Ralim/IronOS/actions/runs/718874134) to my TS80P and unfortunately don't have 100% success.
> 
> @xxv Might be worth trying the build from the first post, that's the one I tried and it worked fine!

Yeah, I tried that build and the more recent one too. Both had similar issues.

**Comment by MarMed** [comment]
This fixes incompatibility with the HP USB-C Dock G4, on my Pinecil it would reboot endlessly, now it appears to be stable, I did not test for very long, but the difference was immediately obvious.

**Comment by Ralim** [comment]
> 
> 
> > @xxv Curious you have issues with the Lenovo 65W charger. Mine works fine 100% of the time. It is a model ADLX65YCC3A (FRU 01FR026, MFG 2018/07, made by Chicony).
> 
> Is this a Pinecil or TS80P? As there could certainly be differences between the two.

The only real difference is that the i2c on the TS80P has to be bit banged which introduces some latency issues.

I did test my TS80P on all of my supplies here without issue; which includes two different revisions of the Lenovo 65W power supples.


Just to rule it out, you did test taking the plug out, flip it 180 and plug it back in?

**Comment by xxv** [comment]
> The only real difference is that the i2c on the TS80P has to be bit banged which introduces some latency issues.

Huh. Weird that the HW was designed to require i2c bitbanging!

> I did test my TS80P on all of my supplies here without issue; which includes two different revisions of the Lenovo 65W power supples.
> 
> Just to rule it out, you did test taking the plug out, flip it 180 and plug it back in?

Yeah, I've been doing that in all my tests. Thanks for checking.

I just tried the binary from [CI run 500](https://github.com/Ralim/IronOS/actions/runs/725518808) as well from [CI run 478](https://github.com/Ralim/IronOS/actions/runs/718426908). Unfortunately, it's still not working on the first go with a Lenovo 65W supply (it bootloops a couple times and only negotiates 5V). I wonder what's different between our setups.

When I put the device into DFU mode, it says `DFU:3.50` and I've been needing to upload it twice to get the RDY file. I'm using the `TS80P_EN.hex` file from the archive though I'm not renaming it. Is there a way to verify build number from the installed firmware so I can verify it uploaded properly?

I've now tried three different Lenovo 65W supplies and all are behaving similarly.

I just tested a Chicony SA10M13947 mfg date 2019/02 rev:500. This one seems to reliably show the Miniware logo, restart, logo, restart, logo: success, 5V negotiated.

Another is a Liteon SA10M13948 mfg date 2018.08 rev:600. Interestingly, this one will sometimes go all the way to displaying the IronOS UI idle screen, then restart once or twice and eventually reaches a stable idle screen showing 5V. It doesn't seem to behave consistently, though: sometimes it'll show the Miniware logo and restart, other times it'll get to the idle screen.

I don't have the 3rd in front of me, but I recall it only ever showing the Miniware logo before restarting.

**Comment by Ralim** [comment]
> > The only real difference is that the i2c on the TS80P has to be bit banged which introduces some latency issues.
> 
> Huh. Weird that the HW was designed to require i2c bitbanging!

I have quite a few gripes with the Miniware hardware design team; 99.9% of these are poor pin selection for hardware peripherals. 

> 
> > I did test my TS80P on all of my supplies here without issue; which includes two different revisions of the Lenovo 65W power supples.
> > Just to rule it out, you did test taking the plug out, flip it 180 and plug it back in?
> 
> Yeah, I've been doing that in all my tests. Thanks for checking.

Just have to ask juuust in case.

> When I put the device into DFU mode, it says `DFU:3.50` and I've been needing to upload it twice to get the RDY file. I'm using the `TS80P_EN.hex` file from the archive though I'm not renaming it. Is there a way to verify build number from the installed firmware so I can verify it uploaded properly?

Yep absolutely, hold the button near the usb port down for about a second when on the home idle screen. The first line has the git short hash in it for verification :)

> 
> I've now tried three different Lenovo 65W supplies and all are behaving similarly.
> 
> I just tested a Chicony SA10M13947 mfg date 2019/02 rev:500. This one seems to reliably show the Miniware logo, restart, logo, restart, logo: success, 5V negotiated.
> 
> Another is a Liteon SA10M13948 mfg date 2018.08 rev:600. Interestingly, this one will sometimes go all the way to displaying the IronOS UI idle screen, then restart once or twice and eventually reaches a stable idle screen showing 5V. It doesn't seem to behave consistently, though: sometimes it'll show the Miniware logo and restart, other times it'll get to the idle screen.
> 
> I don't have the 3rd in front of me, but I recall it only ever showing the Miniware logo before restarting.
> 
> I also just tested both CI versions with the power supply that came with the iron and neither would cause the iron to function properly: bootloops all the way (flipped the cable too). I'm testing this with the stock cable that came with the iron, in case that matters. This supply is white and labeled TRAVEL CHARGER, Model: QC09, 45W, PD + QC3.0

This is very interesting. I'm guessing the main change here is either (a) enabling the PD3.0 or (b) changed timing.
I'll have to have a look into (b) first.

For reference the Lenvo charger I use for a lot of my testing is the Lite-on ADLX65YCC3A MFG 2018.06; rev 500
So it is different to yours 😢

**Comment by xxv** [comment]
> I have quite a few gripes with the Miniware hardware design team; 99.9% of these are poor pin selection for hardware peripherals.

Heh. I guess it's good that it's only poor pin selection then and not other things too? I wonder if it was due to needing to last-minute find a different MCU that was "drop-in replacement" but definitely not a pin-for-pin drop-in replacement.

> Yep absolutely, hold the button near the usb port down for about a second when on the home idle screen. The first line has the git short hash in it for verification :)

Very handy! Thanks.

> This is very interesting. I'm guessing the main change here is either (a) enabling the PD3.0 or (b) changed timing.
> I'll have to have a look into (b) first.

Yeah, I imagine that timing is challenging with something like PD. As you're requesting changes to the power that's going to the device that's being powered :sweat_smile:.

> For reference the Lenvo charger I use for a lot of my testing is the Lite-on ADLX65YCC3A MFG 2018.06; rev 500
> So it is different to yours cry

I've got one 65W Lenovo charger here and my girlfriend has 2. They're all different companies/models/revisions. Good for finding more edge-cases, but harder for replication!

> @xxv
> I did some cleanup that changes timing slightly; if you could try the lates: https://github.com/Ralim/IronOS/actions/runs/729416272

I gave that a shot (and verified the hash!) The Lenovo charger that I've got here still reboots once or twice and only negotiates 5V. I still can't get it to boot to idle with the charger that came with the iron (bootloop). It continues to work great with one of my Anker chargers and *now works* (single-boot to idle, 9V) on a different Anker charger (the one I keep by my electronics workbench that was the reason I posted here in the first place). So it sounds like the timing changes are fixing things for the better, just not 100% yet.

What's with the "reboot once or twice and then it stays on", BTW? I'd expect it to either work or not work, though I guess there are threads here so it's a little less deterministic than single-threaded MCU code. Is there some cap that charges up (on the iron or PSU) to change the state?

> Also, could you try doing a quick remove and re-insert of the usb-c?

Thankfully, my USB-C cables stick in firmly. I gave it my best shot, but wasn't able to get a high-frequency re-insertion and none of the attempts seemed to change any success results.

> Because my ts80P as a modified bootloader, I find i have to connect it once (and it goes into the bootloader) then quickly unplug and replug and then it boots up fine. I'm wondering if that is actually hiding an issue here :/

Ahhhh, yeah, a modified bootloader is probably the key difference between our setups. I'm guessing it's challenging to reflash the bootloader on your end, yeah?

I'm guessing the bootloader is what shows the Miniware logo, yeah? Is that also responsible for DFU support or is that separate?

**Comment by MacDragon** [comment]
I can confirm it gives me 9v now on the apple laptop PSU I have handy, and a third party switch PSU also I have lying about.

Still behaves oddly with a powerbank I have, if it's plugged in cold ( without waking bank first ) it immiedietly shows 9.2V and stays there, after replugging in/resetting it will drop to 5v, and sometimes negotiate upto 9V then 12v, or just stick at 5v.

**Comment by Ralim** [comment]
> 
> 
> > I have quite a few gripes with the Miniware hardware design team; 99.9% of these are poor pin selection for hardware peripherals.
> 
> Heh. I guess it's good that it's only poor pin selection then and not other things too? I wonder if it was due to needing to last-minute find a different MCU that was "drop-in replacement" but definitely not a pin-for-pin drop-in replacement.

They could have just put it on the same I2C as the OLED/Accel but they decided not to 🤷🏼 


> > Also, could you try doing a quick remove and re-insert of the usb-c?
> 
> Thankfully, my USB-C cables stick in firmly. I gave it my best shot, but wasn't able to get a high-frequency re-insertion and none of the attempts seemed to change any success results.
> 
> > Because my ts80P as a modified bootloader, I find i have to connect it once (and it goes into the bootloader) then quickly unplug and replug and then it boots up fine. I'm wondering if that is actually hiding an issue here :/
> 
> Ahhhh, yeah, a modified bootloader is probably the key difference between our setups. I'm guessing it's challenging to reflash the bootloader on your end, yeah?
> 
> I'm guessing the bootloader is what shows the Miniware logo, yeah? Is that also responsible for DFU support or is that separate?

Its the bootloader that does all the programming via drag & drop on a pc. to be able to connect the debugger to mine while bringing up PD, I had to erase it and I loaded the one from the TS80 as I had that to hand.



@xxv Could you try the attached file to see if it improves or gets worse for you?
[Test_Delay.zip](https://github.com/Ralim/IronOS/files/6289083/Test_Delay.zip)

**Comment by Ralim** [comment]
> 
> 
> I can confirm it gives me 9v now on the apple laptop PSU I have handy, and a third party switch PSU also I have lying about.
> 
> Still behaves oddly with a powerbank I have, if it's plugged in cold ( without waking bank first ) it immiedietly shows 9.2V and stays there, after replugging in/resetting it will drop to 5v, and sometimes negotiate upto 9V then 12v, or just stick at 5v.

> after replugging in/resetting it will drop to 5v, and sometimes negotiate upto 9V then 12v, or just stick at 5v.

That sounds exactly like QC not PD.

Is your power bank one of the ones that goes against spec and allows using QC on the type-C port?

**Comment by MacDragon** [comment]
> > I can confirm it gives me 9v now on the apple laptop PSU I have handy, and a third party switch PSU also I have lying about.
> > Still behaves oddly with a powerbank I have, if it's plugged in cold ( without waking bank first ) it immiedietly shows 9.2V and stays there, after replugging in/resetting it will drop to 5v, and sometimes negotiate upto 9V then 12v, or just stick at 5v.
> 
> > after replugging in/resetting it will drop to 5v, and sometimes negotiate upto 9V then 12v, or just stick at 5v.
> 
> That sounds exactly like QC not PD.
> 
> Is your power bank one of the ones that goes against spec and allows using QC on the type-C port?

Wouldn't surprise me, it is a QC/PD bank.

**Comment by xxv** [comment]
> @xxv Could you try the attached file to see if it improves or gets worse for you?
> [Test_Delay.zip](https://github.com/Ralim/IronOS/files/6289083/Test_Delay.zip)

Gave that a shot. Let me guess: you added a 1s delay before starting the PD negotiation?

It doesn't make it usable, but I'm going to guess it will give you useful info. On all the power supplies I tried (Lenovo 1, Lenovo 2, stock, Lenovo X1 Carbon 6th gen, UGreen PD adapter CD137), it boots to idle on the first go (yay!). However at 1000ms after the idle display starts, the device reboots. On Lenovo 1 & 2, it reboots a couple times and then stays at the idle screen showing 5V. I never saw it display anything other than 5V on any of these power supplies with this firmware.

**Comment by Ralim** [comment]
> 
> 
> > @xxv Could you try the attached file to see if it improves or gets worse for you?
> > [Test_Delay.zip](https://github.com/Ralim/IronOS/files/6289083/Test_Delay.zip)
> 
> Gave that a shot. Let me guess: you added a 1s delay before starting the PD negotiation?

Yep, just wanted to split apart any bootup shenanigans from the PD itself.


> 
> It doesn't make it usable, but I'm going to guess it will give you useful info. On all the power supplies I tried (Lenovo 1, Lenovo 2, stock, Lenovo X1 Carbon 6th gen, UGreen PD adapter CD137), it boots to idle on the first go (yay!). However at 1000ms after the idle display starts, the device reboots. On Lenovo 1 & 2, it reboots a couple times and then stays at the idle screen showing 5V. I never saw it display anything other than 5V on any of these power supplies with this firmware.
> 
> Just tested the Anker PSU that was working with the prev rev and it still works. The PD negotiates after the delay without any rebooting. The other Anker PSU that was causing troubles is also behaving the same way.

Interesting.

The TS80 responds to the pd message in an average case of 7ms, worst case of 12ms. So it should be responding plenty fast enough to keep the chargers happy.

I've noticed a bunch of adapters implement logic that if negotiation fails a certain number of times in a row they fall back to dumb 5v.

What your seeing sounds like the firmware is just not responding the chargers advertised supported outputs.
It doesnt feel like a hardware issue though as the other charger works :/

`CD137` brings up a lot of different chargers, could you get a photo of the unit / label? I might see if i can find one to test.

**Comment by Dids** [comment]
I can confirm that this fixes issues with Pinecil + Apple chargers (https://github.com/Ralim/IronOS/issues/838). No more boot looping and the Pinecil heats up to 400C in mere seconds.

**Comment by xxv** [comment]
> Interesting.
> 
> The TS80 responds to the pd message in an average case of 7ms, worst case of 12ms. So it should be responding plenty fast enough to keep the chargers happy.
> 
> I've noticed a bunch of adapters implement logic that if negotiation fails a certain number of times in a row they fall back to dumb 5v.

Yeah, sounds like the Lenovo ones. Honestly not a terrible solution, if you ask me.

> What your seeing sounds like the firmware is just not responding the chargers advertised supported outputs.
> It doesnt feel like a hardware issue though as the other charger works :/

Or maybe they're sending some extra PD-related packets that are confusing the iron?

Just curious: when the unit reboots after a fail in PD negotiation, is that reboot initiated by the power supply or the iron?

Also, do you have a setup where you can sniff the PD data line (CC)? 

> `CD137` brings up a lot of different chargers, could you get a photo of the unit / label? I might see if i can find one to test.

[Here are the photos of the charger](https://photos.google.com/album/AF1QipPz4kImvDDUYDb3ePJo-wCsrJCTunUn6yVZGRI). I don't know much about it. I found it in a box at my partner's house 😅

**Comment by Ralim** [comment]
> Or maybe they're sending some extra PD-related packets that are confusing the iron?

The iron will NACK any packets it cant handle; the most common one of these is USB-swap or power role swap.

> Just curious: when the unit reboots after a fail in PD negotiation, is that reboot initiated by the power supply or the iron?

That is 100% the power supply as its not liking _something_

> Also, do you have a setup where you can sniff the PD data line (CC)?

Yep; I use the CY4500 debugger to monitor the CC lines when trying to debug this; and so far it "works" on all of the chargers I can access so far. I have one dock that it doesnt play well with at a friends office but have not had time to debug it yet. 


> [Here are the photos of the charger](https://photos.google.com/album/AF1QipPz4kImvDDUYDb3ePJo-wCsrJCTunUn6yVZGRI). I don't know much about it. I found it in a box at my partner's house 😅

This URL is 404'ing for me 😢

**Comment by Ralim** [comment]
@xxv 
I've tried removing the flag for usb support; could you re-test if that helps?
The only device I've been able to find that wasn't happy kept trying to do a DR swap for the usb link. This makes it not keep re-attempting.

**Comment by Ralim** [comment]
I'm inclined to merge this as it fixes more than it breaks. @xxv can you open an issue for your chargers and Ill come back to sorting them out after the MHP30 ❤️

**Comment by xxv** [comment]
@Ralim sounds good! Progress! ♥️

**Comment by unCleanCode** [comment]
With the Apple's 87W charger and TS80P iron I can still see it cycles through (turns on and off few times) during the start

**Comment by unCleanCode** [comment]
Ok, that's weird...it was 9V at first few tests but now the same charger, same soldering iron and the same cable give me max of 5V...but it stopped blinking at start. Am I missing something or how could it happen?

**Comment by unCleanCode** [comment]
Loading it again in a few hours - again blinking but giving me 9V

**Comment by Ralim** [comment]
@unCleanCode If its truely an 87W charger it should have a 12V profile to allow the iron to select 12V. (As far as I'm aware)

**Comment by unCleanCode** [comment]
@Ralim not exactly. See more details on Apple charger:
https://ibb.co/gdMMYg2
https://ibb.co/QNw89yN
https://ibb.co/2kKjSPV

As you can see it supports  5V, 9V and...20V :D 
No idea why so

**Comment by Ralim** [comment]
@unCleanCode That is an unfortunate descision by apple.
If the charger does not support PPS then you have no (easy) option to have 12V with that charger.

**Comment by unCleanCode** [comment]
@Ralim yes, I know 12V is not an option for this charger. What I'm concerned about is that:
a) It not always even gets 9V. Sometimes it does - sometimes it doesn't. Unstable
b) When it gets 9V - it cycled through during the start couple of times. So the 9V itself is also somehow unstable

I thought this commit is all about fixing those problems (which I see many people informed it helped them), so just wanted to inform that this didn't fix issues for me...so probably for many other people as well. Up to you to decide if that's an important one or not (for me it's not a big deal, just would need to use another charger)

Thanks!

**Comment by Ralim** [comment]
@unCleanCode 

Understood, just wanted to be clear that I can't do 12V 😅

It's a step in the right direction; I'm not promising this was the final step.

That said; #949 is taking over this thread as I try to narrow down the remaining issues.

Would highly appreciate your help in testing further refinements to the code as you have time (and patience)

**Comment by unCleanCode** [comment]
@Ralim btw, not sure I understand: if the iron works at 12V 3A (well, I believe at 12V it's more like 2.5A at 30W), why can't it work at 9V 3A (27W), or at least 9V 2.5A (22.5W)? Or am I missing something?

**Comment by Ralim** [comment]
The irons tip is purely resistive that we can only turn on and off.

So the max power available is just defined by Ohms law of Volts=Current*Resistance and Power = Volts* Current.

As the tip is a fixed resistance that we can't change; and there is no DC/DC stepdown element we don't have any means to run at higher wattages.

**Comment by unCleanCode** [comment]
Oh....I'm sorry. That's really so clear and obvious that the resistor (tip) can't give the same current at a lower voltage. Looks like I was just too lazy to turn on my brain before asking such an obvious question :) 

Thanks for the answer, and have a good luck! The project is great, I don't even have too many things anymore I'd like to improve

**Comment by MacDragon** [comment]
Hm, not had time to poke much, but I think something did break further for me between the mid cycle pd experiments and current release, never seem to be able to coax my qc3/pd power bank to more than 9v now.

**Comment by Ralim** [comment]
@MacDragon 
Let me know if you have more insight into what is occuring.
Also may be worth trying the newly added PD timeout options just in case you are running into PD being too fast or slow for your charger.

**Pull request merged**
