### PR TITLE
logo update

### PR DESCRIPTION
**Pull request by discip**

### CODE REVIEW

**Comment by River-b** [comment]
I just installed this pull but I do not see IronOS logo in flat or animated on  screen.

version shows as  2.16.E10F958

**Comment by Ralim** [comment]
@discip 
Please dont create a logo per frame 😓 They are chewing up space in github and I doubt anyone is going to flash a particular frame?

**Comment by discip** [comment]
@Ralim
1. I am sorry, I did not mean to clutter github. 😅
*My intention was to provide the necessary parts for an animation that I was capable of delivering.*

   But except for the python part I only followed your guide https://github.com/Ralim/IronOS/issues/446#issuecomment-569477043.

   And additionally I did indirectly ask if this would work https://github.com/Ralim/IronOS-dfu/issues/1#issuecomment-1011289090.

2. Judging by the space restriction, it might be good to remove the ***`.dfu`*** & ***`.hex`*** files as well, since the python script to convert from ***`.png`*** to the desired format is also present. (And eventually adding an example batch to execute the conversion.)

   What do you think?

kind regards

**Comment by Ralim** [comment]
I'm happy for .dfu and hex files ; it was mostly just the animation ones since the way to get it to work would be a bit different and would need to create one "large" hex of all the frames :)

**Comment by discip** [comment]
How should they be stacked?
Do want me to try making one?

**Comment by Ralim** [comment]
Dont know yet, need to figure out a reasonable way to squeeze it down to fit onto a page of flash (1024 bytes)

**Comment by discip** [comment]
Than that'll have to wait, since I am not capable of achieving this. 😁

But maybe @alvinhochun is able to provide help, if he has time at hand and is willing that is.
### He is definitely more that capable of implementing this kind of thing.

**Pull request merged**
