### PR TITLE
tackling issue #1140

### PR DESCRIPTION
**Pull request by discip**
Please refer to https://github.com/Ralim/IronOS/issues/1140 for more details.

Tested this on both **TS80P** & **Pinecil**.
Worked well for both of them!

### CODE REVIEW

**Comment by Ralim** [comment]
Looks good to me, just need to fix MHP30 building and I'm happy :)

I think you just need to ensure the declarations are masked to match the functions they control

**Comment by discip** [comment]
Good morning.
> I think you just need to ensure the declarations are masked to match the functions they control
Sorry, but I don't really get what is meant by that. 😵
please help 🥺

**Comment by discip** [comment]
And there is one more thing, wich I am not able to solve myself:
If the settings are set, so that affected subentries are hidden, the 'scrollbar' is not updated right away, instead it is required to reenter the menu.

Please help.

thanks in advance

**Comment by Ralim** [comment]
So the issue looks to be you have put the functions to control I'd they are shown or not, inside the #ifdef so that it's not included for the MHP30, but it needs to be included for the menu.

So most likely you just need to move the functions out of being in the #ifdef

**Comment by Ralim** [comment]
Scrolling is currently only updated when you enter a menu .

**Comment by discip** [comment]
@Ralim
Should be good to go.
Maybe someone, who owns the MHP30, could test this.

**Comment by Ralim** [comment]
>Is it possible to change that?

Yeah it is possible

>If so, would this imply any downsides?

Mostly just more compute time, since it requires re-calling all of the "show" functions for each menu items.
Certainly doable without too much effort.
To keep this PR small I would say its best to make an issue for fixing this.

> Maybe someone, who owns the MHP30, could test this.
Tested it quickly on mine and it looks to work :)

**Pull request merged**
