### PR TITLE
Update translation_DA.json

### PR DESCRIPTION
**Pull request by t-xdk**
* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by discip** [comment]
@t-xdk
Please update your PR.

**Comment by t-xdk** [comment]
what is pr

**Comment by discip** [comment]
Sorry, PR is short for pull request.
As the languages ​​have been updated, you must either update this pull request or create a new one.

Hope that helps. 😅

**Comment by t-xdk** [comment]
yh no idea how to do that

**Comment by discip** [comment]
I think it would be easiest if you just change the appropriate lines [here](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_DA.json), open a new pull request and close this here.

Did that help?

**Comment by discip** [comment]
I think it would be easiest if you just open a new pull request by changing the appropriate lines [here](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_DA.json) and close the present one.

Did that help?

**Review by discip — APPROVED** [review]

**Comment by t-xdk** [comment]
i think it should be fixed now i retranslated the new file

**Comment by discip** [comment]
You need to sync [your fork](https://github.com/t-xdk/IronOS).
image

**Comment by t-xdk** [comment]
think it should be done now im not used to using github

**Comment by discip** [comment]
Please do not give up.
Just go [here](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_DA.json) and change the corresponding lines & open a new PR.

Or you could upload the changed file here and I will do it for you.

**Pull request closed without merging**
