### PR TITLE
Change to 128bit UUID's

### LINKED ISSUE #1569: Pinecil v2: Consider changing characteristics UUIDs in BLE services
The UUIDs of characteristics in https://github.com/Ralim/IronOS/blob/dev/source/Core/BSP/Pinecilv2/ble_characteristics.h are only unique in the scope of the different services. They are not unique in the scope of the whole device.

Also the UUIDs are 16 bit UUIDs which according to https://www.oreilly.com/library/view/getting-started-with/9781491900550/ch04.html (below headline **UUID**) can be used only for characteristics which are defined in the Bluetooth specification. (At least that's how I understood it, alas I am no BLE expert.)

For this reason I propose to at least consider changing the UUIDs so that the base UUID is the UUID of the respective service (128-bit UUID) as described in https://devzone.nordicsemi.com/guides/short-range-guides/b/bluetooth-low-energy/posts/ble-services-a-beginners-tutorial (below headline **Universally Unique ID (UUID)**)

Example:

New UUID for `BT_UUID_CHAR_BLE_LIVE_LIVE_TEMP`: `d85e0001-168e-4a71-affd-33e27f9bc533`

I know that there are at least 2 clients using the Pinecil BTL services already, but since BLE support is still fairly new and there are still new features planned for IronOS v2.21, maybe now  is the time to discuss this issue before more people rely on the characteristics UUIDs.

### PR DESCRIPTION
**Pull request by Ralim**
Change BLE UUID's to all be 128bit.
Closes #1569 

Will need someone to test (I dont have hardware to hand).

### CODE REVIEW

**Comment by River-Mochi** [comment]
> Will need someone to test (I dont have hardware to hand).

I can test this now.  anything specific I'm looking for? just be able to use the BLE apps PineSAM and Joric's webpage?

**Comment by builder555** [comment]
oddly enough I can't see any BLE_GATT services advertised. the device is present, i am able to connect, but services shows an empty list.

**Comment by River-Mochi** [comment]
is this ready for us to test right now with PineSAM? 
@builder555 and I downloaded from here:   https://github.com/Ralim/IronOS/actions/runs/4420347769
and  "can connect to the pinecil, but **cannot get any data**"

not sure what issue is; currently this version from that link is not working.

**Comment by River-Mochi** [comment]
- when you get a chance  Ralim,  load this beta to V2,  try to get PineSAM  to open.  doesn't work for me, I had to roll back to older BLE beta.
- <https://github.com/builder555/PineSAM>
-  tested with joric's bLE also and it doesn't work there too.

**Comment by River-Mochi** [comment]
https://github.com/joric/pinecil/issues/15#issuecomment-1469209893

**Comment by River-Mochi** [comment]
pls let me know. should this be tested now on BLE apps?

**Comment by Ralim** [comment]
@River-Mochi 
This should be worth testing now.
Note that all UUIDs are different so apps will need to be updated to handle them

**Comment by builder555** [comment]
Now the UUIDs are there, but all the settings are returning 0xffff values

example:
```
f6d75003-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
f6d75004-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
f6d75005-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
f6d75006-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
f6d75007-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
f6d75008-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
f6d75009-5a10-4eba-aa55-33e27f9bc533: bytearray(b'\xff\xff')
```
while all the live data and bulk data items return blanks:
```
d85ef001-168e-4a71-aa55-33e27f9bc533: bytearray(b'')
d85ef002-168e-4a71-aa55-33e27f9bc533: bytearray(b'')
d85ef003-168e-4a71-aa55-33e27f9bc533: bytearray(b'')
d85ef004-168e-4a71-aa55-33e27f9bc533: bytearray(b'')
```

**Comment by Ralim** [comment]
@builder555 
Now try, apologies for that. Missed updating the decoders.
Should have not recieved anything though (empty response), not `0xFF,0xFF`. That might be a bug in some other BLE stack as I couldn't reproduce that here.

**Comment by builder555** [comment]
@Ralim  looks like the values are coming through, i'm still testing. 
but i see the UUIDs have changed again, was that intentional or do they change for every build?

**Comment by Ralim** [comment]
Ack apologies, missed the updated decoder for writing values back.
Can you give this new build a try 🙏🏼 

> but i see the UUIDs have changed again, was that intentional or do they change for every build?
I changed them to make decoding easier; since its not merged in yet figured why make it messier :)

**Comment by builder555** [comment]
@Ralim success! 🕺 
I didn't test every setting, but the main ones (solder temp, boost, reset, save) work. If something doesn't work, I'll wait for bug tickets in my repo :)

**Comment by River-Mochi** [comment]
I'm having success  now but not fully tested between  128 uuid version + PineSAM.
- some bugs but I think maybe they are on PineSam side for Screen brightness (suspect the change in IronOS has not been updated in Pinesam yet). currently shows large weird numbers on brightness scale of pinesam.

**Pull request merged**
