### PR TITLE
Improve I2C for PinecilV2

### PR DESCRIPTION
**Pull request by Ralim**
+ Turn on glitch prevention
+ Force full redraws at some times
+ Enable SCL clock stretch
+ Fix bug that caused sending screen on a lot

### CODE REVIEW

**Comment by Ralim** [comment]
@River-b 
Could you give this alternative method a test for both:
- EPR operation
- Less glitches

**Comment by River-b** [comment]
this one yes?  
https://github.com/Ralim/IronOS/actions/runs/3507032672

**Comment by River-b** [comment]
- installed ver 2.20. 1C63B7B  20-11-22
- works on kovol 140W  EPR  and  Apple 140W chargers for now , no reboots.
-  will test for Screen glitch now
- does this version have the UART  messages set up so I could also connect to my UART Putty ?

**Comment by Ralim** [comment]
Ah sorry;
-> No UART logs that need to be captured on this one
This is good news, please have a look-see for glitches please :)

**Pull request merged**
