### PR TITLE
Pinecil | Rework I2C into much cleaner state machine

### PR DESCRIPTION
**Pull request by Ralim**
This is a rewrite of the I2C state machine from the code from Gigadevice into something a bit more sane and less tangled.
This will also make making it interrrupt based far easier later on (just sleep task and wake from irq).

This also moves handling bus errors etc into a general case to help with the iron lockup issue #843. As the older code didnt timeout correctly at various states.

Would like some sanity testing on more Pinecil units than what I have here :)

### CODE REVIEW

**Comment by jannic** [comment]
Hi Ralim!

Not sure if this is interesting, so just in case: I have a broken Pinecil which shows a garbled display. Otherwise it seems to work, it heats the tip when pressing `+`. I guess I2C is somehow broken. Already got a perfectly working replacement, only kept the broken one in case I need spare parts some day. 

So I tried this firmware (CI build 284) on the broken Pinecil, and noticed the following change in behavior:
- With the old firmware, on bootup I just get some random, but static garbage on the screen. 
- With the new firmware it seems like the Pincil reboots every few seconds: The random pattern changes, and each time `dmesg` reports it found a `new full-speed USB device` (with device descriptor read errors, as expected).

(Where "old firmware" means current release,  v2.14.1, IIRC)

**Comment by Ralim** [comment]
@jannic 
This is interesting;as if the buttons etc are still working but the display is garbled the _most likely_ issue is the display itself.
This is also interesting if it is making the unit reboot; I have to do another pass on this anyway to will have a look for that too.

**Comment by jannic** [comment]
Hey, just to let you know: I tried the latest firmware after you merged this branch (commit 334de33) on the broken Pinecil mentioned above. Now it doesn't show anything on the display, not even the random pixels it has shown before. Looks completely dead - but if I press the '+' button, it still heats up the tip.

**Comment by Ralim** [comment]
This sort of makes sense as this fixes a few logic flaws with how nacks are handled and so the oled driver will just abort the write fairly early on.

I would suggest just replacing the OLED in your unit.

**Pull request merged**
