### PR TITLE
BLE Settings rename + Unique Name

### LINKED ISSUE #1545: BLE Unique name  for Pinecil V2
**Is your feature request related to a problem? Please describe.**
Currently  all pinecil V2 broadcast the same BLE name "Pinecil"  which is used for pairing to BLE devices.
If  several people were together  in a maker class  or with family  and they all wanted to  pair pinecil with their  android phone using the beta BLE webpage, it might be a little juggle to connect the correct "pinecil" name to the BLE app.

**Describe the solution you'd like**
Include the unique ID  or serial number  or the last part of the number with the word Pinecil.
For example   "`Pinecil456789`"
It would be unique to every  pinecil but  also be easy to recognize as the Pinecil iron  since there are usually many variety of BLE devices broadcasting in the same room.

**Describe alternatives you've considered**
People could try to turn on only one Pinecil at a time and then connect to the BLE browser.   I tested this with  two V2.
The way the BLE beta webpage works currently,  when you pair  one Pinecil, then it will no longer show up on a scan on a second device's browser page. This requires some  coordination of the people in the room but it might be doable.
Example:

1. powered on Pinecil (1), paired it to a PC  Chrome browser  BLE webpage on PC.
2. then I  opened Chrome on a separate Android phone and I could no longer see  Pinecil (1) broadcasting the name  "Pinecil" when I attempted to scan for pairing. 
3.  Then I powered on Pinecil (2), and it showed up as "pinecil" on my  Android phone's Chrome app, and I paired it.  Both  machines, PC and Android phone  were showing 2 separate  Pinecils with different temperatures as desired.

### LINKED ISSUE #1566: Expose   "Reset All Defaults"  for BLE usage
**Is your feature request related to a problem? Please describe.**
For Builder555  effort  for BLE  settings changer for Pinecil V2  we  can not currently  use the BLE  to  select "Reset All to Defaults"   as builder555 notes in the below ticket,  that this is not exposed or they can't find it if it is.

https://github.com/builder555/pinecil-v2/issues/3#issuecomment-1419979263
**Describe the solution you'd like**
Please expose  this for BLE  from the Advanced Menu > reset all to defaults.
This would allow  people using the  newest BLE app to press one button on the browser screen to reset everything back to defaults.

image

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**
* Device will advertise as Pinecil-XXXXX where XXXX is random number.
* Adds option to reset settings
* Reshuffles UUID's for settings so that they make more sense for future

* **What is the current behavior?**
Would close #1566 
Would close  #1545

* **What is the new behavior (if this is a feature change)?**
This would break the current webapp for settings editing as it changes settings to be 0 based.
I think doing this pain _once_ is worth it; as it means we can keep setting ID's sync'ed
It also means that extras like save and reset are moved to the end so they count back towards the settings. (I never expect them to meet)

* **Other information**:

### CODE REVIEW

**Comment by River-b** [comment]
> * Device will advertise as Pinecil-XXXXX where XXXX is random number.

@Ralim  could we get clarification on this? a couple of us have tested the Beta today.

1. @zombie-detox  gets 4 digits  Pinecil-3xxx 
2. I get 5 digits Pinecil-5xxxx
3. Both of us get the exact same number every time we pair even if we restart browser and Pinecil. so is it unique to each Pinecil but the same everyday? 
4. Other odd thing is I just tested my 2nd Pinecil and it's advertising same number Pinecil-5xxxx

I loaded this beta since it also has PPS fixes: https://github.com/Ralim/IronOS/actions/runs/4190920103

On further testing, I paired V2-A to windows PC chrome brower joric's bLE webpage. and I paired completely separate V2-B  to Android phone (on same home network)  and connected to BLE webpage. Both V2 advertised same exact  Pinecil-5xxxx number.   Both were flashed with blisp on same  windows PC yesterday.

**Comment by River-b** [comment]
just now went to totally separate windows 11 laptop. Reflashed the beta one one of the V2.  then connected to BLE webpage on that 3rd device (laptop) and it's still same exact  Pinecil-5xxxx number as before.

**Comment by Ralim** [comment]
The number is derived from the device serial number; I'm just taking the lower half. As such its unique per _device_, not firmware related. This is what I understood you wanted from your discussion; where you wanted it as a way to tell them apart.
I didnt expect duplicates to be super common but certainly possible.
Could try and remix the bits a bit more to make it more random.

The number is not a fixed width; and will drop leading 0's.

**Comment by River-b** [comment]
> The number is not a fixed width; and will drop leading 0's.

this might explain why zombie saw 4 digits and I saw 5 digits if he had a zero there.

I just noticed that the first part of my Serial numbers on both V2 are very different, but **last 8 digits are identical.** if you are using the last part of the serial instead of the first part while trimming leading zero's this might explain why I have 2 different pinecils that **both**  show the same exact number when connecting to Joric's BLE and are not Unique name.

@Ralim 
See photo of my two pinecils this might explain why I don't have unique names.
IMG_3512

**Comment by River-b** [comment]
Issue is closed and resolved with 
https://github.com/Ralim/IronOS/actions/runs/4210122191

**Pull request merged**
