### PR TITLE
Off=>icon

### PR DESCRIPTION
**Pull request by discip**
This PR replaces every **`Off`**- / **`0`**-state with this symbol:

unavailable

I initially wanted to reclaim some memory space, but as it turns out, that's not the case here.

In some cases, however, this restores some screen space in places where the actual value is only 2 digits, while space is reserved for 3 digits.

That is, unless the corresponding setting shows **`Off`**, the 1-digit-space immediately before the leftmost digit is unusable.

By shortening **`Off`** to a symbol that doesn't require a 3-digit-space, there is more room for descriptive text, which is useful for languages ​​with relatively long terms.

I hope this makes sense. 😊

However, if that's not desired, I'll drop this PR.

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
I'm sorry to bother you, but did you have a chance to look at this?

And as mentioned in the initial post, if you don't like it I'll drop it!

**Comment by Ralim** [comment]
I dont have any issues with this; was mostly hoping for anyone else to chime in yes/no 🤣

**Comment by discip** [comment]
@Ralim
No problem.
I am willing to wait. 😊

**Comment by Ralim** [comment]
So I've been thinking about this,
I still don't find the power icon overly intuitive.it feels a little orthogonal to the other options (i.e. odd to jump from symbol to numeric system). I personally don't feel like it involves "off", but feels more used as the symbol for "power" over here. This may be cultural 😔

I've been thinking on this a lot, and struggling to come up with an alternative. I think the idea of a unified off icon makes sense.

I've been starting to lean towards a small X as that at least means disabled/not available. I don't love it though. It does make more logical sense as the opposite to a tick for "on".

Would love your thoughts, am I overthinking this?

**Comment by discip** [comment]
Thank you for taking the time.
1. > I still don't find the power icon overly intuitive.

   I totally agree with you!
   But if you remember, there was already a small discussion regarding this topic when I initially proposed to use one of the following icons: off_b / off_c.
   At that time you said, that these icons could mean **`unavailable`** instaed of **`off`**. 😊

2. > I've been starting to lean towards a small X as that at least means disabled/not available.

   If you mean the letter **`x`**, I don't seen an improvement over a _symbol-number-mashup_.
   I'd rather prefer a dedicated symbol, as that would make it more complete.

3. > am I overthinking this?

   I don't think so!
   I like things to be thought through thoroughly! And that rarely can be accomplished by a single person.

**Comment by Ralim** [comment]
Was thinking loosely `X` as in like https://thenounproject.com/icon/disabled-3194810/

But yeah I've not been super happy with an option in terms of the mixed off/on states :/

**Comment by federicodilo** [comment]
What do you think about something like this.
Perhaps easier to understand for the younger generation
off_sym2 off_sym4 off_sym off_sym3

**Comment by discip** [comment]
@Ralim
What do you think about this?

power2&emsp;**=>**&emsp;off_f

Would be great if you could actually test it on your device.

@federicodilo
I've considered such designs before, but discarded them because these symbols represent _only_ **1** of **2** _possible states_, so one would expect the other _state_ as well (feels _incomplete_).
Similar to the _unchecked box_.

Hope that makes sense. 😊

**Comment by federicodilo** [comment]
@discip 
As far I learned, you can surely tell me better, in Germany a cross over a box would mean something like "selected".
Also as Ralim said I would understand it as unavailable.
What about just a slash?
Does it mean "it doesn't apply/any" for you as well?

**Comment by discip** [comment]
1. Ah, that's definitely a shame!
You addressed exactly what I wasn't sure about.
You are absolutely right about that meaning of a _cross over a box_.
For a moment I considered the possibility of seeing it that way, but after testing it on the device itself, it appeared to be a _cross in a **circle**_.

2. The slash was the symbol I went for on the first run, but it was rejected at the time. 😊

   Because of this fact, I've discarded my recent _discovery_ that e.g. Linux/Windows use exactly the same icon for unavailable options/tasks.

3. > Also as Ralim said I would understand it as unavailable.

   Ralim posted:
   > I've been starting to lean towards a small X as that at least means disabled/not available. I don't love it though. It does make more logical sense as the opposite to a tick for "on".

   So: Yes! But that is what he was preferring lately. Right?

So all we're left with is this: off_b
At least to me, because either it looks like **`%`** or the circle and cross merge into an indistinguishable blob when I scale it down, which I need to do to maintain a clean look.

**Comment by discip** [comment]
@Ralim
Habe you by any chance had time to test this?

**Comment by discip** [comment]
@Ralim
Have you by any chance had time to test? 😊

**Comment by federicodilo** [comment]
Have you considered already something like [this](https://www.iso.org/obp/ui#iec:grs:60417:5008)?

**Comment by discip** [comment]
The ISO standard could be confused with the letter **`O`** and this is not understood as an abbreviation for **`off`** in all languages.

As you may have noticed, I've moved on from the idea of ​​representing some kind of **`off`** state and am now trying to find a solution for the **`unavailable`** state.
It's almost impossible to get it right otherwise!

And as mentioned earlier, we don't need to "reinvent the wheel" since the icon I used last is utilized by at least two major operating systems to mean what we need. 😊

What do you think about the round version?
off_b

**Comment by discip** [comment]
@Ralim
@federicodilo
What are your thoughts on the latest status after all this discussion?

**Comment by discip** [comment]
@Ralim
Since our dear Federico seems to be gone, you are the only one left to evaluate this.

Let me know what you want me to change if you don't like it.

**Comment by discip** [comment]
@Ralim
Just after I started typing I noticed that our dear Federico seems to be gone.
So you are the only one left to evaluate this.

Let me know what you want me to change if you don't like it.

**Comment by discip** [comment]
@Ralim
Just after I started typing, I noticed that our dear Federico seems to be gone.
So you are the only one left to evaluate this.

Let me know what you want me to change if you don't like it.

**Comment by discip** [comment]
@Ralim
I hope I'm not getting on your nerves, but I need to know if this has a future or if I should just drop it.

**Comment by discip** [comment]
@Ralim
I hope I'm not getting on your nerves, but I need to know if this has a future or if I should just drop it.

thanks in advance

**Comment by Ralim** [comment]
So the concept has a big 👍🏼 

Just the only question is trying to find the icon that is universal.

Could do the android toggle off? Android toggle off

Digging though https://fonts.google.com/icons?icon.style=Outlined to try and find google material design option icons.

One localisation question I've found is that typically over here the slash is in the `\` direction, where as disabled tends to use `/`. Is that just an Australian thing?

In the end your current icon _or_ the empty set version (aka the slash extends outside the circle) may be the simplest one?

**Comment by discip** [comment]
> Could do the android toggle off? Android toggle off

I considered this as well, but that would break consistency as we would have to replace the checkbox we otherwise use with a _toggle on_ icon corresponding to the one you suggested.
Additionally, this might confuse people since there is no explicit way to tell whether it means on or off, despite the fact that some use automatic screen orientation.
And on top of that I was not able to find a symbol in the list you linked.

As you may recall, I've actually changed this icon at least twice, but somehow I'm failing to meet user expectations.
So I ended up with this one, but ... 😅

Even Microsoft and Linux use this symbol in the way we need.

I think we should just implement this into a stable release to see what people think about it, because from my observation there are very few people following the development.
At least no one apart from you and Federico has actively discussed this topic. 😊

**Comment by Ralim** [comment]
Ah yes good point.

I think I agree, let's ship it and see if anyone shows up with a better suggestion

**Review by Ralim — APPROVED** [review]

**Comment by discip** [comment]
Thanks!

What, you are up already?

I was just about to change the symbol after you pointed me to pay attention to the orientation.

I guess I'll have to pull up one more follow up then. 😆

**Pull request merged**
