### PR TITLE
Settings toggle for ble

### LINKED ISSUE #1495: BLE  toggle off  Menu  feature
**Feature request**

@ralimtek   is there a way  that  Menu  could have  **BLE  off/on**  toggle (or Bluetooth On/Off)?   this way the BLE IronOS could be installed, but shut off  to see how it affects performance without needing to  Swap to different  IronOS versions?

I have not done  enough test to know since lack of time but it seems like there is performance loss which you confirmed in  chat a couple weeks ago.

**Describe the solution you'd like**
Menu option to   **toggle  on/off the  BLE**  all broadcast and receive.

**Describe alternatives you've considered**
Alternative  is  have two  different versions of  IronOS to download.  some people may not want the BLE at all broadcasting/listening. Some people may want BLE  but knowing that it affects performance,  they will need to switch to none-BLE version whenever they need if there is no Menu on/off option.

- **Pinecilv2_BLE.zip**
- **Pinecilv2.zip**

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Adds menu option to turn BLE on or off on PinecilV2

* **What is the current behavior?**
Fixes #1495

### CODE REVIEW

**Comment by Ralim** [comment]
@River-b 
Heads up.

This adjusts if we start BLE or not at boot.
This is cleanest way and means if its off there is no performance impact (none of the BLE code runs).

**Comment by River-b** [comment]
is there a file I can download to check?   I cant seem to find it when I  click on  26f71b2 above.

**Comment by Ralim** [comment]
Just grab a recent Dev build :)

**Comment by River-b** [comment]
I see it in Advanced menu  but it blacks out quickly  - does not have a scrolling  help line. see video 
https://user-images.githubusercontent.com/97197236/214415452-9524b83e-5925-46d3-a5c7-b28be2be4cc1.mp4

nice  to have scrolling  help message then it  might not  go  black screen so fast.

**Pull request merged**
