### PR TITLE
Pinecil uart

### PR DESCRIPTION
**Pull request by Ralim**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [ ] There are no breaking changes

* **What kind of change does this PR introduce?**
So, this ads in using the uart in the Pinecil to output some basic params about the operation of the iron as it runs.
This is emitted once per loop of the PID task, but is sent using IRQ's so it doesnt block the PID tasks operation or timing.

The data is sent out as csv at 2000000 baud 8N1.

Also during this noticed that I completely forgot to update the logo page so have moved that to the end of flash.
This will require logos to be re-flashed at the correct address.

* **What is the current behavior?**
(You can also link to an open issue here)
This helps with #753 by providing uart output every ~12ms of the current readings.

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

Todo before merge:

- [x] Update docs for logos
- [x] Someone else sanity test this works for them (@dhiltonp ?)

Grab from here https://github.com/Ralim/IronOS/actions/runs/511405176

### CODE REVIEW

**Comment by alvinhochun** [comment]
Slightly off-topic, but the only thing I have that can be used for UART is an ATmega32U4 board running at 5V. It should handle 3.3V UART input fine. On the Pinecil side, PA3 on GD32VF103 is not 5V tolerant, but a simple voltage divider should be fine here, right?

But I also wonder if you need to use as high as 2000000 baud.

**Comment by alvinhochun** [comment]
Gave this a try with 115200 baud. Data is received fine, but noticed that the third column `PWMWattsx10` is passed and printed as `unsigned` while the source value `x10WattsOut` is actually `signed`, so you might want to fix that.

The fourth column is a hard-coded `0`. I'm guessing that it's just unimplemented?

I wonder if it's worth also printing the tick timestamp to get more accurate timing info?

**Comment by Ralim** [comment]
> 
> 
> Slightly off-topic, but the only thing I have that can be used for UART is an ATmega32U4 board running at 5V. It should handle 3.3V UART input fine. On the Pinecil side, PA3 on GD32VF103 is not 5V tolerant, but a simple voltage divider should be fine here, right?

You should be fine with a voltage divider, though at the moment the firmware does not implement anything on the rx side :)
> 
> But I also wonder if you need to use as high as 2000000 baud.
I mean, could run slower but everything I use these days runs at fast baud rates, and it makes more sense to send it fast as I'm sure more data will be added over time. I find it quite rare to run into a device that cant run at a high baud rate these days, 115200 feels very slow 😁 
But could probably drop it down if its a bad issue.




> 
> 
> Gave this a try with 115200 baud. Data is received fine, but noticed that the third column `PWMWattsx10` is passed and printed as `unsigned` while the source value `x10WattsOut` is actually `signed`, so you might want to fix that.
Ah heck, yep.
> 
> The fourth column is a hard-coded `0`. I'm guessing that it's just unimplemented?
Yeah for now, this was 99% a quick bash out something to get people to commect first.
> 
> I wonder if it's worth also printing the tick timestamp to get more accurate timing info?
Yep absolutely

**Comment by alvinhochun** [comment]
> > But I also wonder if you need to use as high as 2000000 baud.
> 
> I mean, could run slower but everything I use these days runs at fast baud rates, and it makes more sense to send it fast as I'm sure more data will be added over time. I find it quite rare to run into a device that cant run at a high baud rate these days, 115200 feels very slow 😁
> But could probably drop it down if its a bad issue.

It's just solely because I don't have a proper USB UART hardware for this. The ATmega32U4 I have runs at 16MHz so to read 2000000 baud it will only have the time for like, 80 instructions per byte received? It might be doable, but I have not yet dug into it. Actually, I just remembered I have a RPi somewhere so perhaps I should use it instead, which would've also save me the logic level conversion 🤣

**Comment by dhiltonp** [comment]
Woohoo!

**Comment by Ralim** [comment]
I'm thinking I'll merge this in as is; and I'm sure any feature requests will appear in a github issue :)

**Pull request merged**
