### PR TITLE
Update translation_RO.json

### PR DESCRIPTION
**Pull request by discip**
Fortunately there is a way to use diacritics in translation_RO. 😊

@mobycl1ck
@cipyyy
@sandmanRO

### CODE REVIEW

**Comment by sandmanRO** [comment]
Hello @discip, I had no doubt that eventually you will get this sorted out. Only I noticed a small typo in the translation_RO.json. At line 172 ("description": "Clipeţte temperatura după oprirea încălzirii, în timp ce vârful este încă fierbinte"), the first word of the translation ("Clipeţte") is misspelled. It should be "Clipeşte". The word is the translation for blinking.

**Comment by discip** [comment]
@sandmanRO
Fixed!

The original file came from @mobycl1ck.
And I noticed exactly that difference, but as he changed it, I believed this was correct. 😅

Btw:
Have you already tested it on your device?

**Comment by sandmanRO** [comment]
Hello @discip, I haven't tested the new translation as on my TS100s I have a custom version of the firmware that is not so fancy as the IronOS (the text is hardwired in the code and it can not be easily changed as in the IronOS).

**Comment by mobycl1ck** [comment]
Helo folks, hectic week at work, saw the changes being merged and after all the corrections being made. RO_translation is finished and has the right form and shape, as in use of diacritics and other details.

**Comment by discip** [comment]
@Ralim
This is good to go. 😊

**Review by Ralim — APPROVED** [review]

**Pull request merged**
