### PR TITLE
Update translation_fr.json

### PR DESCRIPTION
**Pull request by HanaO00**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**
(Bug fix, feature, docs update, ...)

* **What is the current behavior?**
(You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by HanaO00** [comment]
Yes I tested on my TS100, the Pinecil has not yet arrived, I see that the line 266 exceeds on the letter "D" of option "SettingLockDisableChar" but instead of putting "Lock the - buttons" I can put "Lock - the buttons", I just repeated the test in this way and it does not shift the text any more and the other options work, there are errors of spellings on the old translations, what do I do, do a PR again just changing this, knowing everything is OK?

**Comment by HanaO00** [comment]
Let me know if you want pictures or something

**Comment by Ralim** [comment]
No need for pictures, just wanted to check you had tested as you were changing spacing and thats prone to pushing stuff offscreen :)

If you happy with how it is i can merge it, or you can push a commit to fix up as much as you can in this one -- your choice really.

**Comment by HanaO00** [comment]
Thanks for trusting me,

I did a test of the options, it no longer shifts line 266 of the file, and the options work, I enabled the full display in iron mode, for the tip option , before my commit it displayed: 19.3, after it displays 19, is it necessary to modify my commit to have the number after the comma?

I can imagine that it can be boring that I do PR little by little, but I try to do my best not to mix everything up, if you prefer I can try to see what I can improve and do as little PR as possible

**Comment by Ralim** [comment]
If your text is too long it will push the remaining characters of the edge of the display. It won't harm anything but it's down to if you think it's required or not.


I'm absolutely happy for big commits when it comes to languages, because I mostly trust the crowd on this. Feel free to do lots of smaller commits if you want if your using the build artefacts to download the firmware for testing.

GitHub only notifies me if one of the following is true:

- you comment
- you tag me

So you can push as much as you want - I don't mind 😂

Just let me know when you think it's good to go.


It's better to do one big or than 10 small ones.

If you break things like the file structure the build will fail (no green tick next to it)

So long as the build passes, and you get the green tick; then it's purely down to aesthetics of how it looks, and if you can just check that text isn't cut off.

**Comment by federicodilo** [comment]
Hello, I noticed that two strings would seemengly go out of bounds.
I case you may try this:
"NoAccelerometerMessage": "Accéléromètre\n**pas disponible** !",
"NoPowerDeliveryMessage": "Aucune interface\n**USB-PD** détectée !",

**Comment by HanaO00** [comment]
@Ralim, thank you, so on the detailed screen in soldering mode do you prefer it to be displayed: Panne 19.X, or Panne 19 (which removes a number after the decimal point by adding a space before and after ":", in France it is considered as a spelling error when there is no space before and after, if the number after the decimal point is absolutely not important I can leave it like that , if it's very precise I try to find another solution

@federicodilo thanks also, my Pinecil has not arrived yet I have nothing in USB to test on the screen, is there enough space for "Aucune interface\nUSB-PD détectée"? Otherwise I leave "Pas d'USB-PD\ndétecté !!"

**Comment by federicodilo** [comment]
In order to rest assured that everything will fit in, a length of sixteen characters per line would be just fine.
Both strings will work in any case 👌🏻

**Comment by Ralim** [comment]
Is this good to merge in ? @HanaO00

**Comment by HanaO00** [comment]
It's good for me @Ralim, I'll help you a little more with the Pinecil when I have it

**Comment by Ralim** [comment]
Thank you :)

**Pull request merged**
