### PR TITLE
Added VPDO option for disabling PPS/EPR PDOs.

### PR DESCRIPTION
**Pull request by Samuelrmlink**
* **Please check if the PR fulfills these requirements**
- [*] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**

Added "PD VPDO Enabled" option to the Power settings menu. 
This option allows the user to disable PPS/EPR PDOs and just use the best Fixed PDO available. 

* **What is the current behavior?**

Pinecil chooses whatever appears to be the best PDO available. 
(Maximum power without overloading the supply)

* **What is the new behavior (if this is a feature change)?**
Behavior remains the same - unless the "PD VPDO Enabled" option is unticked in the Power settings. 

* **Other information**:

### CODE REVIEW

**Comment by Samuelrmlink** [comment]
I should have tried compiling with all languages first before creating this PR...

**Comment by Ralim** [comment]
I'm all for this idea.

Also note you will need to also add a new entry to https://github.com/Ralim/IronOS/blob/eb5d6ea9fd6acd221b8880650728e13968e54d3d/source/Core/BSP/Pinecilv2/ble_characteristics.h#L90 to extend it to being exposed over BLE.

But once build passes; looks fine by me otherwise.

**Comment by Ralim** [comment]
Hmm, dont think those TS80P build failures may be your fault; if you dont have time to debug them I'll look into them later on

**Comment by Samuelrmlink** [comment]
Oh - Looks like I forgot to actually create the BLE characteristic.

**Comment by Samuelrmlink** [comment]
Okay - that should do it. 
I don't (yet) have a PinecilV2 to test it though.

**Pull request merged**
