### PR TITLE
Possible fix for lock/unlock toggle loop

### PR DESCRIPTION
**Pull request by neon12345**
This is an untested draft to fix a possible lock/unlock toggle loop bug when holding both buttons.

### CODE REVIEW

**Comment by neon12345** [comment]
The logic seems to work but display information can be optimized (show longer?).

**Comment by neon12345** [comment]
I works now as I would expect it:

Hold both buttons when unlocked = go into locked mode and show locked until button release.
Hold both buttons when locked = go into unlocked mode and show unlocked until button release.

But the locked warning on single button press is still short.

**Review by Ralim — APPROVED** [review]
This looks good to me.
Showing the alert for longer could be solved by also triggering the `warnUser` in other paths perhaps?

**Comment by neon12345** [comment]
@Ralim as I understand it, the message is shown as short as the button is pressed?!

**Comment by neon12345** [comment]
@Ralim see #1957

**Pull request merged**
