### PR TITLE
changed idle screen & missing tip

### PR DESCRIPTION
**Pull request by discip**
idle screen
idle screen

missing tip
missing tip
Since the A-button is not doing anything if pressed briefly, I replaced it following @sandmanRO example.
(Hope he does not mind.) 😊

### CODE REVIEW

**Comment by sandmanRO** [comment]
Is looking good. Unfortunately we can not control per pixel brightness so that dotted approach is the close we can get to the "grayed out" appearance.

**Comment by discip** [comment]
@Ralim
Will have to fix the 'flip case' for this one first! 😅

**Comment by discip** [comment]
@Ralim
One more question though: How do I make **CI** compile only *one device* e.g.: **TS80P**?

**Comment by Ralim** [comment]
Edit this line : https://github.com/Ralim/IronOS/blob/04ad5a3bfc6471534caa95be4dd34f94d48209d6/.github/workflows/push.yml#L10

**Comment by discip** [comment]
Thanks, I have already found and edited it. 👍

**Comment by discip** [comment]
@Ralim
Good evening,
unfortunately I am not able to figure out, how to prevent the **`disconnectedTipIcon`** from getting flipped over when in *left-handed mode* is enabled. (in the current state it points in the wrong direction).
I tried to change these [lines](https://github.com/discip/IronOS/blob/21b399be6b7c767fe4c27ad4eaa48f7ebf645f6d/source/Core/Threads/GUIThread.cpp#L983-L992), but without any success.
Please tell me where I have to look for. 😊

**Comment by sandmanRO** [comment]
Hello @discip, I don't want to take you away the pleasure of figuring this all by yourself, but if I may, let me offer you few hints. 
1. The flipping is done automatically by the OLED once you change the configuration array (see the function responsible for rotating the display).
2. You don't "prevent" an image from being flipped. You simply either:
2a:  draw the image as mirrored, that is, when you transfer the image to the graphic buffer you go backwards, starting with last picture's column then go towards 0 column (as opposed to going from 0 to last column as you normally would do)
2b: if you don't mind increasing a bit the firmware size, you can create and store a mirrored image of the initial image and you draw one or the other depending the current rotation status of the display (e.g. you are in right or left handed mode).

**Comment by discip** [comment]
@Ralim
Sorry for nagging,
but could it be possible, that you missed the previous post? 😅

thanks in advance

**Comment by discip** [comment]
@sandmanRO
Good morning Sir,
I thought about that as well, but went with the invitation Ben made earlier, to bump him now and than.
I appreciate him taking a deserved timeout, but since I don't know for sure, I think he is not going to punch me in the face. 😁
Thank you for the precise explanation, I am going to look into that. 👍

**Comment by sandmanRO** [comment]
The table below will also help you better understand how the image is created, stored and used in conjunction with this OLED.

Image

**Pull request merged**
