### PR TITLE
Update configuration.h

### PR DESCRIPTION
**Pull request by River-Mochi**
fixes tickert  #1624 

* **Please check if the PR fulfills these requirements**
- [X] The changes have been tested locally
- [X] There are no breaking changes

* **What kind of change does this PR introduce?**

typo bug fix,   10C = 50F 
Current code  has 10C  and 60F as minimum temperatures; they are not equivalant.
(**10°C** × 9/5) + 32 = **50°F**

### CODE REVIEW

**Review by discip — APPROVED** [review]

**Comment by discip** [comment]
@Ralim
I hope I did not do something I am going to regret. 🤦🏻

I should have looked for the settings in the config files of all the other devices before merging, as they also say 60°F instead of 50°F!

I'm sorry for rushing.

Should we revert this PR or should we change all other corresponding configs as well?

**Comment by River-Mochi** [comment]
10°C  does not equal  60°F   (conversion math not right in original code maybe)

(**10°C** × 9/5) + 32 = **50°F**

**Comment by discip** [comment]
Yes, I got that, but I suppose there is more to it than just converting one unit into the other, since all the other conversions don't match either:
https://github.com/Ralim/IronOS/blob/0a4560efac961e5f5fbe47d5f9d7beb78dc77d4a/source/Core/BSP/Pinecilv2/configuration.h#L132-L137
```
450°C => 842°F
250°C => 482°F
```

**Comment by River-Mochi** [comment]
i saw that too, figured  Ralim was just rounding up the MAX  temp on F to make it cleaner looking at 850 F instead of 842F.  so I left that alone. 

but for  60F or 50F  there is no reason for rounding since it's a whole number. 
but we shall see what is behind this soon.

**Comment by discip** [comment]
@Ralim
Is your vacation over?
If so, nice to have you back!
I hope you had time to relax.

Please let me know if this should be reverted, or if we should adapt all the other configs as well.
Just a reminder. 😊

**Comment by Ralim** [comment]
Still ongoing, just checking in here and there 😊 I'll be back next week.


I would just update all the rest to match.

**Comment by discip** [comment]
Oh, sorry to interrupt!
I didn't mean to do that.

Enjoy your free time and relax.

Have a good time! 😃

**Pull request merged**
