### PR TITLE
add ukrainian lang

### PR DESCRIPTION
**Pull request by beelash**
* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by discip** [comment]
@beelash
Sorry to disappoint you, but fortunately your language is already implemented!

https://github.com/Ralim/IronOS/blob/dev/Translations/translation_UK.json

**Comment by discip** [comment]
@beelash
Sorry to disappoint, but:

1. fortunately your language is already implemented:

   [translation_UK.json](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_UK.json)
and

2. the file you used as a reference seems to be old and in order to implement this it would need a complete overhaul.
However, if you need to change only certain parts, please make a PR based on the already present [Ukrainian translation](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_UK.json).

**Comment by discip** [comment]
@beelash
Sorry to disappoint, but:

1. fortunately your language is already implemented:

   [translation_UK.json](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_UK.json)
and

2. the file you used as a reference seems to be old and in order to implement this it would need a complete overhaul.
However, if you need to change only certain parts, please make a PR based on the already present [Ukrainian translation](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_UK.json).

**Comment by beelash** [comment]
great! so maybe should rename it as translation_UA.json? it will be correct.

**Comment by alvinhochun** [comment]
The ISO 639-1 language code for Ukrainian is `uk`. If you, say, want to use a more complete BCP 47 tag then it could be `uk-UA`. But the current Ukrainian localization has existed for a long time, so unless there is a really good reason to change it, keeping the current code is better.

**Comment by beelash** [comment]
you're right, I checked as well right after replying to the message. it is the confusion that has led me astray.

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=uk

comrades did not found Ukrainian. actually I checked too, so decided to make it. Most people in UA (who are not familiar with iso) associate the UK with United Kingdom. And this is the reason why they cannot find the correct translation. :(

**Comment by MagicLike** [comment]
> The ISO 639-1 language code for Ukrainian is `uk`. If you, say, want to use a more complete BCP 47 tag then it could be `uk-UA`. But the current Ukrainian localization has existed for a long time, so unless there is a really good reason to change it, keeping the current code is better.

I think such naming is way better, e.g. for eventual extended German translations like de-DE de-CH de-AU, etc....

**Pull request closed without merging**
