### PR TITLE
Add capability of writing logos in binary format

### PR DESCRIPTION
**Pull request by cybernesto**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Feature: Extended python script to support writing .bin files directly. This avoids the additional step of using objcopy.

* **What is the current behavior?**
img2ts100.py can only create .hex files. objcopy is necessary to convert it into a .bin file.

* **What is the new behavior (if this is a feature change)?**
img2ts100.py can create .bin files directly.

* **Other information**:
The 001_PINECIL.bin file now matches the updated PNG logo.

### CODE REVIEW

**Comment by discip** [comment]
@cybernesto
Thank you! 👍
I would hate to create a separate PR on the following, so please change the name of **`001_PINECIL.bin`** to **`Pinecil.bin`** and add **`Pinecil_L.bin`** in as well?

thanks in advance
kind regards

**Comment by cybernesto** [comment]
Gotcha. I only noticed this was changed today. Hopefully the merge worked correctly. Let me know if any other changes are required.

**Comment by discip** [comment]
## Great! Thank you! 😃👍

**Comment by discip** [comment]
> Hopefully the merge worked correctly.

I don't know, since I neither tested this, nor do I need the **`*.bin`** files.
I just wanted to prevent people complaining about the **`*.bin`** files not working. 😁

**Comment by cybernesto** [comment]
Oh, the .bin files are working fine. I was just wondering if the commit in my branch got correctly reflected here but it looks like it went well.

**Comment by discip** [comment]
@Ralim first has to approve this PR and if I got this right, it simplifies thing, so its merger should be no problem.

**Comment by Ralim** [comment]
This looks good to me ❤️ 

Do you think you could go the next step and pull in the functions from the dfu-util packer so we just create a .dfu file that is directly flashable?
https://github.com/Ralim/IronOS/blob/master/source/dfuse-pack.py

**Comment by cybernesto** [comment]
Yeah, I can give it a try. Would it make sense to do it in a separate pull request though?

**Comment by Ralim** [comment]
Yes it would, was just asking here (and waiting for CI)

Thank you though for this :)

**Comment by discip** [comment]
@cybernesto
There is a request from earlier this year regarding the topic @Ralim asked for here: https://github.com/Ralim/IronOS/issues/798 maybe there could be some collaboration? 😊

**Pull request merged**
