### PR TITLE
Translate new strings to EL (Greek)

### PR DESCRIPTION
**Pull request by Devnol**
* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Translate new strings to EL

Sorry for taking so long, I had literally forgotten about it until now.

### CODE REVIEW

**Comment by Devnol** [comment]
These are the strings that were immediately obvious, if something else has changed please do let me know so I can add it.

**Comment by discip** [comment]
@Devnol
Unfortunately you did use an old translation file, please update your fork first.

**Review by discip — COMMENTED** [review]
@Devnol
Unfortunately you did use an old translation file, please update your fork first.

Currently the **[`dev`](https://github.com/Ralim/IronOS/tree/dev)** branch is the default, instead of the **`master`** branch.
 
So you would need to adapt this file [translation_EL.json](https://github.com/Ralim/IronOS/blob/dev/Translations/translation_EL.json.).

**Comment by Devnol** [comment]
whoop, sorry. Will do. Also, I'm sorry to bother you about this but could you please take a look at [this](https://github.com/Ralim/IronOS-dfu/issues/11)? I could _really_ use some help.

**Comment by discip** [comment]
You do not need to be sorry at all! 😊

It's fine!

**Comment by Devnol** [comment]
for some reason I didn't have a dev branch on my fork and I couldn't be bothered to find how to do that now so I think the easiest option was to just yeet it and start over, see pr #1623

**Pull request closed without merging**
