### PR TITLE
Update translation_RU.json

### PR DESCRIPTION
**Pull request by JugglerLKR**
* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [V] There are no breaking changes

* **What kind of change does this PR introduce?**
Rephrasing

### CODE REVIEW

**Comment by Ralim** [comment]
Is this superseded by #1289 ?

**Comment by CRImier** [comment]
`"text2"` is marginally better, while `"desc"` is less correct than in #1289 . I'd recommend merging the `"text2"` part only, if possible!

**Comment by CRImier** [comment]
> This means user has to know which maximum voltage user's power supply can safely provide and set corresponding voltage in Iron' settings.
No.
> Should user limit the voltage, so Iron will not try "asking for" 20V from 12V max capable PSU.
No.
> Can Iron damage QC PSU that way?
No.

> power supply is able to provide 12v, but user sets 9v in settings deciding it is enough?
Yes. For instance, some PSU at 12V can only give 1.2A, which is not enough (12V needs 1.5A), but 1.2A at 9V is good enough.
> Maximum QC voltage - this translation means that user may set 20V and don't care which PSU is being used, not caring will it support 20V or not. Thus Iron will negotiate at maximum QC voltage psu can supply.
Yes.

**Comment by CRImier** [comment]
"Can Iron damage QC PSU that way?" was in context of " 'asking for' 20V from 12V max capable PSU", and that won't cause damage

**Comment by JugglerLKR** [comment]
Reading all the above I'm voting for @CRImier suggestion:
"text2" is marginally better, while "desc" is less correct than in https://github.com/Ralim/IronOS/pull/1289 . I'd recommend merging the "text2" part only, if possible!
How do we do this?

**Comment by discip** [comment]
@JugglerLKR 
Just edit the coresponding lines in ’changed files’ here in your PR. 😊

**Comment by JugglerLKR** [comment]
> @JugglerLKR Just edit the coresponding lines in ’changed files’ here in your PR. 😊

@Ralim - I hope I've done it correctly.

**Comment by discip** [comment]
@JugglerLKR
Since the master branch was modified since your initial PR, you have to update this PR. 😊

regards

**Pull request closed without merging**
