### PR TITLE
Remove em-dash from strings

### PR DESCRIPTION
**Pull request by alvinhochun**
* **Please check if the PR fulfills these requirements**
- The changes have been tested locally
- There are no breaking changes

* **What kind of change does this PR introduce?**

Bug fix?

* **What is the current behavior?**

Most languages include the em-dash char not in the font table which makes all of them load the CJK font unnecessarily.

* **What is the new behavior (if this is a feature change)?**

Replaced the em-dash with colon

### CODE REVIEW

**Comment by Ralim** [comment]
Should we just add `em-dash` to the font table?

**Comment by alvinhochun** [comment]
Is it really necessary? 🤔

**Comment by Ralim** [comment]
Could argue either way on that 🤔

**Comment by Ralim** [comment]
Just thinking, we should either stop it bringing in the em-dash -or- just add it? Since this will happen again

**Comment by alvinhochun** [comment]
I've considered implementing a way for the translations to define what fonts they use, so that one wouldn't accidentally bring in glyphs from the CJK font for non-CJK translations...

**Comment by Ralim** [comment]
Would make a lot of sense to indicate what is used; though is it really a problem either?

**Comment by alvinhochun** [comment]
Eventually I might want to specify some font glyph overrides specifically for yue_hk and zh_tw which will differ from what hypothetically zh_cn would use, and the ability to exclude CJK font from a translation will come together. But this is not *that* important to me so I haven't really got the motivation to implement...

Regarding em-dash specifically, I think it's fine to just make this change for now. More importantly, I think that

>     3S: 3.0V - 3.7V

is clearer than 

>     3S — 3.0V - 3.7V

anyway.

**Comment by Ralim** [comment]
I agree 100% on all of your points, especially the motivation part 😅

Mostly using you to get a second opinion here :)

Appreciate the work 🥰

I definitely agree it's clearer as well

**Pull request merged**
