### PR TITLE
changed power animation

### PR DESCRIPTION
**Pull request by discip**
Just testing, please do not merge yet.

### CODE REVIEW

**Comment by Ralim** [comment]
If you leave them as drafts I won't merge them :)

**Comment by discip** [comment]
@Ralim
What program do you use to convert bmp/png to hex?

**Comment by Ralim** [comment]
Hmm good question, often I've exported as binary and used xxd to do binary -> hex.

There is somewhere a web based editor for these though I can try and find.

Don't have a super good workflow sadly off the top of my head

**Comment by Ralim** [comment]
Ah, can you hit edit that the top of this and change it from trying to merge into `pid` to `master` then it should be allowed to reopen

**Pull request closed without merging**
