### PR TITLE
idlescreenBG  -> buttonA & buttonB

### PR DESCRIPTION
**Pull request by discip**
Since the icon for the B-button is for all versions the same I split *idlescreenBG* in half.

Updated icons for **MHP30**:
buttonA
buttonA
missing plate
missing tip

Credits to @TRaMeLL https://github.com/Ralim/IronOS/discussions/1119#discussioncomment-1917133.

Tested for **TS80P**.

### CODE REVIEW

**Comment by Ralim** [comment]
So thinking out loud, I havent checked, but if we split the screen do we still need the flipped form or can we just draw with different starting offsets from the left?
(Havent checked)

**Comment by discip** [comment]
@Ralim
Actually **ˋbuttonBˋ** should work without being flipped.
But since we can't foresee when the icons get updated into whatever design, I think the flipping 'action' should be kept.

The **ˋbuttonBˋ** needs to be flipped either way to please all the lefties out there. 😊

By the way:
I don't understand, why the previous **`idkescreenBG`** icon and now the **`buttonA`** & **`buttonB`** have to be read from *right to left*
and not the way the **`disconnectedTip`** icon *left to right* is  handled?

**Comment by Ralim** [comment]
I'm happy to keep the flipping action, was just thinking out loud. Not expecting you to change.


>I don't understand, why the previous idkescreenBG icon and now the buttonA & buttonB have to be read from right to left
and not the way the disconnectedTip icon (left to right) is handled?

Not 100% following this sorry

>I noticed, by comparing the sizes of idkescreenBG (84) and disconnectedTip (41), that the later is not exactly half the size of the former. Ideally this should be 42. May I change this, or are there any implications I can't see right away?

It saves two bytes :D

**Comment by discip** [comment]
@Ralim
> Not 100% following this sorry

No problem, found the issue, in the latest edit this is fixed. 😊


> It saves two bytes :D

I made them both the same size **42** and that actually saved even more. 😁

**Pull request merged**
