### PR TITLE
removed some redundant lines

### PR DESCRIPTION
**Pull request by discip**
as stated in the header
and corrected reset message

Reset message was in both cases the same, but the result was not!

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Some words regarding the *'reset-after-firmware-update'* function.

Since I'm using a fork of **IronOS** without *Invert* & *ButtonLocking*, I noticed that the current handling of a **firmware&nbsp;update** in terms of a reset causes problems that make a manual **`reset`** unavoidable.

I assume that values ​​from previous functions are being moved and put in the place of other functions, resulting in a chaos.

In my case the device displayed a VIN of **`8 V`** instead of **`5 V`**!

So we either need to:
1. rework the way a reset is performed, or
2. reset all values to default after a **firmware&nbsp;update**.

I'd like to have the 1 option, but don't know how to achieve this. 😅

**Comment by Ralim** [comment]
Are you at all messing with the enumeration inside the settings file? That enumeration is append only (only ever add new ones) if any are reordered or removed you have to force a reset as that breaks the migration.

Additionally migration only works forwards, ie. On adding, if you go forwards to a new setting,back and then forwards again it may not behave well as it will shoehorn the former extended setting into the new one.

So long as that settings enumeration is not touched it should migrate fine.

**Comment by discip** [comment]
Sorry, but I am not able to follow. 😅
What do you mean by enumeration?

> Additionally migration only works forwards, ie. On adding, if you go forwards to a new setting,back and then forwards again it may not behave well as it will shoehorn the former extended setting into the new one.

That is exactly what I did. 🤣

I primarily thought about a scenario where features might eventually be removed.

**Comment by discip** [comment]
I failed at making a return to the **`home screen`** after a **`factory reset`**! 😩
What am I missing? Is there an easy way of achieving that?

thanks in advance

**Comment by Ralim** [comment]
So this part of the code: https://github.com/Ralim/IronOS/blob/efeb0e68045ab94295665939acb217186c7311f1/source/Core/Inc/Settings.h#L16

Where it assigns a setting to a number; can never be changed since thats how they are laid out on flash.
So if we remove a setting its value will stay (and be lost) for now.

>I failed at making a return to the home screen after a factory reset! 
The best way to do this is just reboot the device tbqh to make it do a full settings reload.

**Comment by Ralim** [comment]
>This seems a bit clumsy. I think it would be best if we could virtually reboot the device (without disconnecting it).
Is there a way to achieve this?

Sorry thats what I meant; we can just ask the chip to do a reset for us.
There is the command `reboot();` but iirc it needs fixing on Pinecilv2. If ok; we can do that in new PR (want to kick 2.20 out)

**Comment by discip** [comment]
> Sorry thats what I meant; we can just ask the chip to do a reset for us.
> There is the command `reboot();`

## Ahh, that's fine! 👍🏻

> but iirc it needs fixing on Pinecilv2. If ok; we can do that in new PR (want to kick 2.20 out)

I'm good with that!
Should I try to send a PR on the way *(At least the part I think I can do.)?*
I would leave the I²RC to you. 😁
Or should I leave it all up to you?

**Comment by discip** [comment]
@Ralim
> Additionally migration only works forwards,

Since the feature removal method I used in my fork doesn't work, I would like to know how to do it properly?

**Pull request merged**
