### PR TITLE
Handle menu sizing better

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**

Fixing scroll indicator to update correctly when menus turn on and off, and also position correctly.

* **What is the current behavior?**

https://github.com/Ralim/IronOS/issues/1139

### CODE REVIEW

**Comment by Ralim** [comment]
@discip If you are around to give this a test :)

**Comment by discip** [comment]
@Ralim
Good morning,
sorry for being late.

Unfortunately this did not solve the issue! 😔
(Neither **TS80P**, nor **Pinecil**.)

If I can be of any assistance, please let me know.

Btw: The max **`QC voltage`** for the **TS80P** is ***14.2*** is this by design or should this be **_14.0_**?

regards

**Comment by Ralim** [comment]
Did it flash correctly?
As this changes it from 14.2 to 14

**Comment by discip** [comment]
> As this changes it from 14.2 to 14

Sorry, my bad, unfortunately the last commit was the master not the branch you changed! 😓😔

**Comment by Ralim** [comment]
Ah yeah, if you click on the green tick next to the last commit, you can click on one of the tests to go to the right one.

Where is the scroll bar corrupting for you? (Preferably pinecil as I have that nearby)

**Comment by discip** [comment]
As stated in the initial issue:

1. Go to **`Power settings` => `QC voltage`**.
2. Raise the value to **22.0 V**.
3. See how the 'scrollbar' is all over the place!

**Comment by Ralim** [comment]
Eugh of course its the one i didnt test on. Fixed it for the other ones I tested in the power menu. Hmm.

**Comment by Ralim** [comment]
Try after this builds^
Dont think issue was the scroll bar, but rather that there was a cutoff `V` fighting it :D

**Comment by discip** [comment]
@Ralim
Perfectly that works! 😃👍
## Thank you!

**Comment by Ralim** [comment]
😅 glad that was it.
Fixed the other scrollbar stuff anyway so good to do :)

**Pull request merged**
