### PR TITLE
disconnected tip pic in detailed idle screen

### PR DESCRIPTION
**Pull request by discip**
Replaced the text on idle screen with the picture of disconnected tip.

@Ralim
First contribution to:
https://github.com/Ralim/IronOS/pull/1076#issuecomment-927386798
>I agree it is a rather neat solution.

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Will have to take care of the layout in *'left-handed'* orientation, before this is mergeable. 😅

*Maybe I'll have to come back at you on this one. 😁*

**Comment by Ralim** [comment]
:) It shouldnt be crazy to handle the flip case.
There is code there that handles this for the main screen that you could be inspired from

**Comment by discip** [comment]
@Ralim
Since this *(detailed idle screen)* would have to be rearranged completely for the *lefty mode*, I would like to stick with the minimal change I made here, for now.

**Comment by Ralim** [comment]
I haven't been able to test this, but you think its good ?

**Comment by discip** [comment]
@Ralim
I have tested this on the **TS80P** and that worked just fine!

**Pull request merged**
