### PR TITLE
Update Chinese and Japanese translations

### PR DESCRIPTION
**Pull request by alvinhochun**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Translation update

* **Other information**:

* Fixed the English menu text used in the Japanese translation -- they have to use the two-line syntax same as English to be displayed properly.
* The Japanese translation update was done with the help of Google translate, but I didn't dare to do this for the "Calibrate CJC" menu text. Best for this to be checked/updated by a Japanese speaker. CC @yuk7 @i4M1k0SU @skishida
* @contactalexliu might want to check the Simplified Chinese translation...
* @Ralim I have to revert #1430. Apparently it now takes too much RAM to extract the ZH_CN translation for the MHP30...

### CODE REVIEW

**Comment by Ralim** [comment]
Eugh running out of ram now.

Need to have some thoughts about this, the ZH_CN is pushing us on ram and flash depending on what state its in at one point in time.

**Comment by alvinhochun** [comment]
Perhaps we may finally need to optimize it to store CJK glyphs as 12x12 bitmaps instead of padding them to 12x16... I don't have the time to implement this though...

**Comment by discip** [comment]
@Ralim
> and see if I make any progress

Did you make any progress? 😃

**Comment by Ralim** [comment]
So for now I'm merging this and happy to take the revert. Variable fonts and other optimisations need more work than I think I'll have time for, for now.

**Comment by discip** [comment]
@Ralim
> Variable fonts and other optimisations need more work ...

Hasn't that already been implemented by revising the language handling?

Iirc it started with:
https://github.com/Ralim/IronOS/commit/97651f07d7ff54e960ba18d49e3919d68007ed6d

and was completed with:
https://github.com/Ralim/IronOS/commit/f9ce1ef0466ac6d383f3343c766dfdd90dcc8499

**Comment by Ralim** [comment]
It certainly had some more work but it's not optimal entirely yet.

Should still look into variable width font handling and possibly overhaul the some more of it. But it is a little better in my testing

**Pull request merged**
