### PR TITLE
updated graphics for idle screen & for missing tip

### PR DESCRIPTION
**Pull request by discip**
### TS80(P)
idle screen:
idle screen
missing tip:
missing tip

### TS100 / Pinecil
idle screen:
idle screen_Pinecil
missing tip:
missing tip_II

### MHP30
idle screen:
idle screen
missing tip:
missing tip

reference picture:
MHP30

I tried several designs and this is all I came up with, if someone is capable of creating better pictures, I will definitively have a look.

kind regards

### CODE REVIEW

**Comment by Ralim** [comment]
Should we start doing different graphics for different models?

Been thinking about this for a bit since the MHP30 doesnt really make sense with the iron tip.

And this definitely _looks_ like a TS80(P) 🤣 

Thoughts?

**Comment by discip** [comment]
Good evening,
since no one complained about the previous design, I just proceeded using it.
In fact it is an alternated version of this https://github.com/Ralim/IronOS/discussions/1119#discussioncomment-1708997.
And as I was asked about my opinion on implementing this, I jumped right in.

But if anyone does not like this, I will leave it as is.
But if you are willing to implement the code part for different models, I will try my best on delivering the graphics. 😃

**Comment by Ralim** [comment]
I like it, dont get me wrong :)

Just thinking that especially with the MHP30 we should probably start to make the icons a bit nicer

> But if you are willing to implement the code part for different models, I will try my best on delivering the graphics. smiley

Easiest way is to `#ifdef` them for now

so 
```
#ifdef MODEL_TS100
<logo here>
#endif
#ifdef MODEL_Pinecil
<logo here>
#endif
#ifdef MODEL_MHP30
<logo here>
#endif

#if defined(MODEL_TS80) + defined(MODEL_TS80P) > 1
<logo here>
#endif
```

**Comment by discip** [comment]
No worries, I did not get you wrong. 😊

Since I do not know the code well enough:

>```
>#ifdef MODEL_TS100
>.
>.
>.
>```

Will it work,
1. if I enter it like this, or
2. would you have to change other parts of code beforehand?

If the 1st is true, please give me some time and I will try to cover them all.

Are the tips for the **TS100** and for the **Pinecil** are not identical?
So I would have to tune in only 2 more, instead of 3. 😁

And we definitely will need more space, so would you mind adding this flipping feature (https://github.com/Ralim/IronOS/pull/1097#issuecomment-939559330) you proposed?

**Comment by Ralim** [comment]
So it will work, basically the `#ifdef` stuff is a compile-time switch, so depending on what model is selected it will either include or exclude the content inside the `#ifdef` -> `#endif` sections.

No change should be required

Ah, Pinecil and TS100 are indeed the same

You wont need extra space as only one option will get compiled in :)


Example:

```
#if defined(MODEL_TS80) + defined(MODEL_Pinecil) > 1
const uint8_t idleScreenBG[] = {};
const uint8_t disconnectedTipIcon[] = {};
const uint8_t disconnectedTipIconFlip[] = {};
#endif

#ifdef MODEL_MHP30
const uint8_t idleScreenBG[] = {};
const uint8_t disconnectedTipIcon[] = {};
const uint8_t disconnectedTipIconFlip[] = {};
#endif

#if defined(MODEL_TS80) + defined(MODEL_TS80P) > 1
const uint8_t idleScreenBG[] = {};
const uint8_t disconnectedTipIcon[] = {};
const uint8_t disconnectedTipIconFlip[] = {};
#endif
```

And fill in the values

**Comment by discip** [comment]
> So it will work, basically the `#ifdef` stuff is a compile-time switch, so depending on what model is selected it will either include or exclude the content inside the `#ifdef` -> `#endif` sections.

I know about that, I was not sure, if the code already knows, 'how to handle':
```
#if defined(MODEL_TS80) ...
```

Hopefully I made myself clear this time. 😊
Apologies for the confusion. 😔

So I'll try my best and afterwards I'm going to ping you about the result. 😃

regards

**Comment by Ralim** [comment]
Ahhh, yeah the MODEL_?? stuff is used all throughout the code (look in the `configuration.h` files for example)
Its what actually picks what your building for :)

**Comment by discip** [comment]
@Ralim
Since you have the **MHP30**, would you please give this a go, I unfortunately do not own such device. 🥺

Thanks in advance

**Comment by Ralim** [comment]
Looks good on MHP30 :)
Will merge in

Thank you ❤️

**Comment by discip** [comment]
Glad you like it. 😃

**Pull request merged**
