### PR TITLE
Add raw hall effect output to the debug menu.

### PR DESCRIPTION
**Pull request by ritkit**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Adds a raw hall effect debug menu item for troubleshooting hall effect sensor. 

Changes are made to make_transition.py and GUIThread.cpp/

* **What is the current behavior?**
Hall effect output cannot be viewed.

* **What is the new behavior (if this is a feature change)?**
Can now click through debug menu to see raw hall effect sensor output.

* **Other information**:
Will build and test shortly.

### CODE REVIEW

**Comment by Ralim** [comment]
Hia,
Looks good to me. If CI passes then should be good to go. Can you give it a test on the CI builds once those are done?

**Comment by ritkit** [comment]
> Hia, Looks good to me. If CI passes then should be good to go. Can you give it a test on the CI builds once those are done?

Yes, I can. Waiting on my hall effect sensor to arrive Monday. Will get it soldered up and a build for pinecil to test.

**Comment by ritkit** [comment]
I just realized, I probably should have used 

#ifdef HALL_SENSOR

So this code can support the other builds without the hall effect sensors.

**Comment by Ralim** [comment]
Yeah good point, that's what the CI checks are there for

**Comment by Ralim** [comment]
clang-format is a picky pain but it does sorta help in making everything perfectly identical. Apologies for the pain

**Comment by ritkit** [comment]
Hahaha, ya. It also doesnt help I am starting with a fresh dev environment on my own computer with no clang format checks or anything. Trying Atom.io out.

**Comment by ritkit** [comment]
Alright, flashed my iron with this code. Changes don't break the iron but it reads out 0 which makes sense as it does not have the hall effect sensor in it.

Once I get the hall effect sensor soldered on, I can update this pull request with results if you want me to.

**Comment by Ralim** [comment]
Hoping you like all the upgrades so far :)

Yeah if you can verify it would be great. If I get time to verify before then I'll merge it in

**Comment by ritkit** [comment]
#1193 Attaching the Issue I opened on this, to this pull request for documentation purposes.

**Comment by discip** [comment]
@ritkit @Ralim 
I don't know if this is covered by this PR, but it  would be nice if the settings for the hall effect sensor would only show up, if it was actually populated onto the PCB.

thanks

**Comment by Ralim** [comment]
@discip  The debug menu is meant to be super simple so it doesnt really do "skip if not present" at the moment as that can be _more_ confusing?

**Comment by discip** [comment]
@Ralim
> The settings in the settings menu should only show if its present tho.

Yes that's what I thought at first, but I did not populate the required hall sensor onto the board and still I am able to set the sensitivity of it. 😵

The fact that the setting was available made me assume that the sensor was installed in the first place.

**Comment by ritkit** [comment]
> ### Edit:
> ### I have just opened up the **Pinecil** and realized, that the hall sensor is actually already there, but it does not react, regardless of which sensitivity is set. Even more 😵😵.

Really!! Mine definitely does not have the hall effect sensor and the documentation on their wiki says it should be unpopulated.



I still need to get mine soldered on.

**Comment by discip** [comment]
> Really!! Mine definitely does not have the hall effect sensor and the documentation on their wiki says it should be unpopulated.

## You are absolutely right!
I made this conclusion based on a photo that was claimed to show the soldered part,
150044319-d581bc2b-1de4-460b-a27d-466eeb7c9c88
but I did not go the extra step to take a peek on the other side of the board. 🤦‍♂️😓

Your photos are depicting exactly the same situation I found in my **Pinecil** (including the version number).

**Comment by Firebie** [comment]
It is due
```
#define HALL_SENSOR
``` in the .\source\Core\BSP\Pine64\configuration.h

**Comment by discip** [comment]
@Firebie
> It is due
> 
> ```
> #define HALL_SENSOR
> ```
> 
> in the .\source\Core\BSP\Pine64\configuration.h

Ah now I get this! 🤦‍♂️
So it is based on the iron not on the presence of the hall sensor!
## Thank you for pointing this out! 😃👍

**Comment by discip** [comment]
@Ralim
> The settings in the settings menu should only show if its present tho.

But than I don't get why the settings for it are available? 🤷‍♂️🤯 Or what did you mean by that?

**Comment by River-b** [comment]
this is hall sensor location on the U14 spot. I installed on 2 different pinecil this week. 
this is what it looks like before and after install. 
1b

this is the model I purchased at Digikey - notice there are 3 qty tiny ones.
Hall Sensor
This is 3 hard drive magnets on stand, which activates the hall sensor Zzzzzz. Sensor is on HIGH setting but it still needs magnets very close to work. If I use just one magnet, I have to hold it right against pinecil for it to work. I tried flipping it every direction. some directions don't work at all because of magnet direction.

**Comment by Ralim** [comment]
Just did a tweak to print absolute value but otherwise it works :) @ritkit

**Comment by discip** [comment]
@Ralim
What about fact I described above?

**Pull request merged**
