### PR TITLE
Logo rework

### LINKED ISSUE #446: Feature: Custom GIF on boot-up
Feature request

Hi,
I have a simple ( I hope :D ) idea, that besides custom logo on boot-up, You can also implement a custom gif on iron startup. That could be a fun little feature.
Chears!

### LINKED ISSUE #617: clean logo ts100 not working
* **I'm submitting a ...**
  - [x] Bug report
  - [ ] Feature request
  - [ ] Translation

* **What is the current behavior?**
I want to remove the bootup logo. 
but when i try to flash the file (with _clean_logo.hex) it create an .err file and the logo remain.

the installation method is working (i try with the last ts100 firmware and it work perfectly), but the _clean_logo.hex create this error.

I already try with command copy from windows but not working.
I already try with linux and windows too(same problem)
DFU 3.45

***Steps to reproduce:***

1. flashing firmware  _clean_logo.hex
2. 
3.

***Video of problem if hard to reproduce***

* **What is the motivation / use case for changing the behavior?**

### LINKED ISSUE #1173: _clear_logo.hex not working (Win10)
**Describe the bug**
Not able to flash *_clear_logo.hex*

resulting in ***.ERR***

**Details of your device:**
device|firmware
-|-
**TS80P**|build https://github.com/Ralim/IronOS/commit/5058e18138635b87978e24db58bf4c58c60e0a15
PC|Win10

**Additional context**
Tried flashing it several times.
Flashing the firmware.hex works as intended though!

### LINKED ISSUE #1228: boot logos converted to dfu
I  got all the Boot logo Art I could find on this github that people shared publicly to be used in pinecil and I converted them to DFU. 
I made a fork with them in the boot logo folder.

How do I upload it or join it into a pull request for review.  It would be nice to include all the Art in one central location like the Boot Logo Folder so people can browse and select what they like to personalize their Pinecil.

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [ ] There are no breaking changes

* **What kind of change does this PR introduce?**

Support for new logo support that (a) fixes the old endian issue and (b) allows animation.
Removes logo's from this repo and instead places them in the Meta repo.

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

Closes #1173
Closes #1228
Closes #617
Closes #446
Inches closer to supporting #292

### CODE REVIEW

**Comment by Ralim** [comment]
@discip and @River-b 
I'm sure you will want to start testing this with the IronOS-Meta logos

**Comment by discip** [comment]
@Ralim
I am on it finetuning **`IronOS.gif`**.
As soon as this fits, I'll replace the previous one. 😊

**Comment by Ralim** [comment]
🤟🏼 ❤️ 
I was really hoping this would take your attention and we would end up with an epic intro animation :)

**Comment by discip** [comment]
@Ralim
I really like to help and to contribute to your great work.

This is kind of a PM.
I don't know if you are Christian but please do not use the *horned hand* symbol, since it is a satanic one.

I hope you get me right.

thank you

**Comment by Ralim** [comment]
Ah okay apologies, over here its `love_you_gesture` :/

**Comment by Ralim** [comment]
Also u should add to answer the other part, absolutely love what you have done with animated logo so far, and I'm excited to see how you put this to use.

I spent a while trying to find a lean enough encoding to let some wise animation design work to get a fair few frames in, and I think this should be the most flexible one

**Comment by discip** [comment]
> Ah okay apologies ...

Thank you for respecting that! ❤

> I spent a while trying to find a lean enough encoding to let some wise animation design work to get a fair few frames in, and I think this should be the most flexible one

I think you did s great job on that one as well.
Hopefully I am able to live up to your expectation.

**Comment by Ralim** [comment]
Always happy to respect things like that. It's always a case of I just don't know, but always happy to be told about them. I'm assuming the heart is okay, though is there a preferred emoji version of " your awesome/thank you/etc"?


I don't meant to stress you by this  but knowing that if I build it out your likely to come along and push it; it is excellent motivation to do a decent job the first time around. The classic motivation of knowing something will be used, and therefore the effort is justified.

**Comment by discip** [comment]
@Ralim
> Also i should add to answer the other part, absolutely love what you have done with animated logo so far, and I'm excited to see how you put this to use.

Totally missed replying on that. 😓
# I absolutely appreciate you acknowledging this! 
# And I am highly honored to be allowed to contribute to your project!
When I first stumbled over your *'custom firmware'* I was astonished, that someone (you) ***dared*** and also managed to supercharge the already beautiful hardware!

Flashing the latest build of **IronOS** and the animation worked flawlessly!
Buuuut ... on the iron some frames get cut away.

1. Is the duration coupled to a certain amount of frames, or is it totally independent? (Maybe it should be dependent on the duration of the animation.)
2. Since you opened an issue addressing the extra entries in **`User interface`** ***(logo on/off | duration)*** [here](https://github.com/Ralim/IronOS/issues/292) already, I am not going to open a separate one.

**Comment by River-b** [comment]
> @Ralim I am on it finetuning **`IronOS.gif`**. As soon as this fits, I'll replace the previous one. 😊

what are the *.Gif used for?  I thought we could only use png or bmp?

**Comment by Ralim** [comment]
This changeset is for adding in support for animated boot logo's so gifs are an option now :)

**Comment by River-b** [comment]
So I could tell the artist they can make gifs now? and how are Gifs converted into  DFU?

**Comment by discip** [comment]
@River-b
Good morning,
all the files (**`.gif`** & **`.png`**) in [here](https://github.com/Ralim/IronOS-Meta/tree/main/Bootup%20Logos/Images) are automatically converted to **`.dfu`** & **`.hex`** files and put into a **`.zip`** file [here](https://github.com/Ralim/IronOS-Meta/actions) on each CI run.

So you have to create a PR with new **`.gif`** & **`.png`** files and wait for CI to complete.

**Comment by River-b** [comment]
@discip what is easiest for Artist to do? I'm trying to understand the procedure since we  have to explain to new people how to do things. 
**Scenarios**
(1)  Artist just wants to make art for themselves and not share: download python script, install python+pillow locally and using the provided script, convert any PNG or animated gif into DFU. Then upload the dfu it to Pinecil similar to firmware upgrade procedure.
(2) Artist wants to convert Png or animated Gif and willing to share art freely to others: they use IronOS-Meta repository, run Pull Request, everything is auto converted, people can download the correct Zip for their  correct equipment. 

@Ralimtek
For Scenario #2, not that this would happen, but there could be NSFW images?  it's a tiny screen but people are creative and there are very young people who buy pinecil & have access to github so that is one concern. Should there be some message in IronOS-Meta and documentation that NSFW images should not be loaded into the IronOS-Meta for PR, and to just use Python to do conversion locally on your PC ?

**Comment by discip** [comment]
@River-b
1. Create a **fork** of [IronOS-Meta](https://github.com/Ralim/IronOS-Meta) and proceed as mentioned above.
2. Create a new **branch** in your **fork**, put files which you want to share in and make a PR (Pull Request).

**Comment by Ralim** [comment]
@River-b 
I definitely think most people are wise enough to know that NSFW content should not belong on the public web like in Meta.
People can fork and do what they want in their forks but should not PR back to the repo. I might add a note about this to Meta though.


My expectation that if its people doing it once off for themselves, it will work like before where they use the python script themselves.

If they want to give it back to the community then they can always think about a PR to meta

**Comment by Ralim** [comment]
This has been working well for me in my testing, and a bit better after the latest tweaks.
Would love your feedback on if this is working or not

**Comment by discip** [comment]
As mentioned above:

> Flashing the latest build of **IronOS** and the animation worked flawlessly! Buuuut ... on the iron some frames get cut away.
> 
> Is the duration coupled to a certain amount of frames, or is it totally independent? (Maybe it should be dependent on the duration of the animation and only accept the input from the future duration menu if it is a static picture.)

and here https://github.com/Ralim/IronOS/pull/1241#issuecomment-1050320552 it works for the most part. 😊

**Comment by Ralim** [comment]
Did you reset after the push of [8a3a45e](https://github.com/Ralim/IronOS/pull/1232/commits/8a3a45e4eea135040bd7a9612a2d1d6185eb5873) ? It changed the inter-frame delay to round to 5ms increments which allows slower frames which should help. Also it brings if its constraining the framerate now.

**Comment by discip** [comment]
Yes I did, since I merged all the changes you created PRs for.
But the fact that the animation is quitted to early remains, as mentioned in #1241.

**Comment by discip** [comment]
I don't know if I was supposed to test the latest commit, but I did and this has unfortunately no effect on the animation being interrupted.

**Comment by Ralim** [comment]
Which animation are you seeing interruption on?
Did you update to latest ironos-meta as well?

**Comment by discip** [comment]
Thank you!
Sorry, 😅 I missed the fact that there was an update as well.

Now the entire animation is shown, but the last frame is to short, so maybe adding a bit of extra time at the end?

**Comment by Ralim** [comment]
@discip 
Okay try now if you get time 😓 I dont have time to test tonight but will try tomorrow if i can

**Comment by discip** [comment]
Will do later as you know by now. 😀

I have been thinking about the extra time at the end that it might be not a solution for every case.

I will test if duplicating the last frame will still be in the allowable size range.
That might help with the last frame.

Have a good refreshing night. 😃

regards

**Comment by discip** [comment]
Good morning Sir,
unfortunately I have to report, that this did not change a thing. 😓

**Comment by discip** [comment]
Still nothing.

**Comment by Ralim** [comment]
Hmm, which animation is not showing the last frame for the correct time?

**Comment by discip** [comment]
@Ralim
Its this one:
[IronOS.gif.zip](https://github.com/Ralim/IronOS/files/8219229/IronOS.gif.zip)

**Comment by Ralim** [comment]
@discip 
Can you share the .gif you used? Or is this the one thats in the meta repo already?

**Comment by discip** [comment]
> Or is this the one thats in the meta repo already?

Yep, that is exactly it. 😊

> Note I've also pushed a few touches to meta

This time I considered  that for testing! 😁

But, it still exits immediately after the animation is finished, without waiting for 4s. 🤷‍♂️

**Comment by Ralim** [comment]
Ohh

The logo isn't meant to wait for four seconds, that's only for static images

**Comment by discip** [comment]
🤦‍♂️
Sorry I thought this https://github.com/Ralim/IronOS/pull/1232/commits/5a8fc42340a486375cbd101ec9961e06d06e4d59 was meant to do this.

Is there a chance to get this done?

**Comment by Ralim** [comment]
My intention was that the logo exit's after the gif finishes.
Since your PR was adding in a time duration, I would rather merge this mess in and then finish out yours to add a time control?

**Comment by discip** [comment]
I am fine with that!

**Comment by River-b** [comment]
adding time at the end of the animation would be great because it ends way to fast, thanks for doing this.

**Comment by discip** [comment]
It is good to go! 👍

**Pull request merged**
