### PR TITLE
Update translation_pl.json

### PR DESCRIPTION
**Pull request by canislupus11**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**
I correct some polish translations

* **What is the current behavior?**
Automatic translations

* **What is the new behavior (if this is a feature change)?**
Better - manual translation

* **Other information**:

### CODE REVIEW

**Comment by Ralim** [comment]
Could you please just run a double check using the CI generated files (click green tick or [here](https://github.com/Ralim/ts100/runs/1507403248) and then use the artifacts drop down to select the zip for your device model.

Just to make sure it all displays correctly :)

**Comment by canislupus11** [comment]
Yes, it's much better, I made a few more corrections. I had a problem
translating "PowerPulsePower" because I don't know how it works.

W dniu 06.12.2020 o 23:51, Ben V. Brown pisze:

**Comment by KITT3000** [comment]
Był jakiś problem z wyświetlaniem litery `ł`, że zmieniłeś ją na `l`?

**Comment by canislupus11** [comment]
https://github.com/Ralim/ts100/issues/728

pon., 7 gru 2020, 16:45 użytkownik Ziuta <notifications@github.com> napisał:

**Comment by KITT3000** [comment]
Na TS100 czy TS80 bo mam TS80 i normalnie widzę ten znak.

**Comment by canislupus11** [comment]
Ts100. Może wieczorem zdążę, to wgrane firmware polski i zrobię foto.

pon., 7 gru 2020, 16:52 użytkownik Ziuta <notifications@github.com> napisał:

**Comment by Ralim** [comment]
@canislupus11 
`PowerPulsePower` is how much power is drawn in the brief power pulses that are used to keep a power bank awake (mainly on ts80). This lets the user adjust the intensity of the pulse for their power bank.

Trying to figure out the missing char but no massive progress just yet but will poke tomorrow a bit more.

**Pull request closed without merging**
