### PR TITLE
clang-format implementation

### PR DESCRIPTION
**Pull request by ia**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [ ] There are no breaking changes[^1]

[^1]: it depends how to treat it.

* **What kind of change does this PR introduce?**
`clang-format` check on github CI.

* **What is the current behavior?**
`make check-style` [is not running on github CI via actions](https://github.com/Ralim/IronOS/actions/runs/5514071700/jobs/10052902665#step:6:6). It successful only because it doesn't return error code to the environment: `find` external tool is not provided in a container but `busybox` built-in implementation of `find` doesn't support required flag for `find` in `check-style` target.

* **What is the new behavior (if this is a feature change)?**
Make `check-style` [run "successfully"](https://github.com/ia/IronOS-plus/actions/runs/5523882664/jobs/10075414823#step:5:2143)[^1] (**unfortunately**) with a lot of warnings.

* **Other information**:
Maybe I miss something but while I was working on a slightly different modifications, nearly _by accident_ I discover this situation. Is there any chance that you're aware of that and this is a supposed behavior?

---

P.S.

To be fully honest with you, I personally in my humble opinion find some of the _suggestions_ by `clang-format` a bit strange because for me they look like "_formality_ over _read-ability_" like `enum` style declarations or _some_ recommendations on comments style. So maybe instead of making `clang-format` happy, just `.clang-format` config can be tweaked a bit. ;)

Plus, some source files, especially those which were auto-generated by STM-related IDEs or obtained as 3rd party projects as FreeRTOS/usb-pd/etc., _probably_ should be excluded at all from checking.

Regardless your decision over formatting rules I will be glad to help with code reformatting. As always, let me know what you think about all of this.

Oh, and I took some liberty to split/rename build steps with tests & checks for unification in naming and splitting by code language.

### CODE REVIEW

**Comment by ia** [comment]
Oh, I just noticed that this is not a _strictly_ required build step. But still, having at least one red light is not quite good, I guess. :thinking:

**Comment by Ralim** [comment]
I'm happy to exclude freertos and driver folders from clang format.

The re isn't much in this format I insist on; mostly I use this to stop my ide's folding code at 80 characters or putting {} on their own lines.

**Review by Ralim — APPROVED** [review]

**Comment by ia** [comment]
Ookay... I tweaked a bit `ALL_INCLUDES` & `ALL_SOURCE` by excluding everything related to `ST`/`CMSIS`/`HAL`/etc. And I must admit that some suggestions looks pretty neat & tidy. But for some warnings _it thinks_ that it knows better. :D

I tried briefly to find some options myself... but I got luck with enums only. So, what I would disable in the first place:
- [how comments must be aligned](https://github.com/Ralim/IronOS/actions/runs/5526331587/jobs/10080949822?pr=1740#step:5:1395)
- [how macros](https://github.com/Ralim/IronOS/actions/runs/5526331587/jobs/10080949822?pr=1740#step:5:1321) must be [aligned](https://github.com/Ralim/IronOS/actions/runs/5526331587/jobs/10080949822?pr=1740#step:5:1361)
- how to [align spaces](https://github.com/Ralim/IronOS/actions/runs/5526331587/jobs/10080949822?pr=1740#step:5:347) in complex conditions

But `.clang-format` config seems pretty sophisticated so I guess the main approach is to ~keep googling & trying stackoverflow advices~ sit down and read very carefully [official documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) considering that some _"high level"_ options may enable/disable another set of _"low level"_ ones (as far as I could understand from brief docs look through).

**Comment by Ralim** [comment]
What we may want to do is instead pick an upstream standard one clang-format knows (Google,LLVM etc) and then just stack overrides on that.
I often default to LLVM iirc in IDE's where there isnt one setup yet.

**Comment by ia** [comment]
Official documentation doesn't make much of a sense to me for some reason BTW. For example, [it says](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutivemacros):
```
AlignConsecutiveMacros (AlignConsecutiveStyle) **clang-format 9**
    Style of aligning consecutive macro definitions.
[...]
AlignConsecutiveMacros: AcrossEmptyLines

AlignConsecutiveMacros:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: false
```

Okay, sounds what can be tweaked to disable warnings for macros. Check version in docker:
```
$ clang-format --version
Alpine clang-format version 13.0.1
```

Okay, 13 > 9. Trying by adding this into `.clang-format`:
```
AlignConsecutiveMacros:
  Enabled: true
  AcrossEmptyLines: false
  AcrossComments: false
```
and run `check-style` to get multiple errors like:
```
/build/source/source/./.clang-format:11:3: error: unknown enumerated scalar
  Enabled: true
  ^
Error reading /build/source/source/./.clang-format: Invalid argument
```
and even after removing `Enabled: true` line I get:
```
/build/source/source/./.clang-format:11:3: error: unknown enumerated scalar
  AcrossEmptyLines: false
  ^
```
:no_mouth:

**Comment by ia** [comment]
> What we may want to do is instead pick an upstream standard one clang-format knows (Google,LLVM etc) and then just stack overrides on that. I often default to LLVM iirc in IDE's where there isnt one setup yet.

As far as I understand, the current `.clang-format` has been generated based on LLVM code style. However, my another understanding is that the way how `clang-format` works is pure binary logic for every option: `true` to mess code **according to an option**, `false` to mess code **against to an option**. But there is no _"don't touch"_ option (except putting special comment into a file but then the whole file will be ignored): even when I tweak some `true`/`false` options (or just commenting them with `#`) locally, `clang-format` suggests me to change the code **in one way** or **another** but not keeping it as is for some reason. Probably I'm just not getting something. Anyway, sorry to waste your time on this not so much important thing, really.

**Comment by ia** [comment]
Ufff... what an adventure! Here is a brief write-up of what has been done:
- out of curiosity I decided to see what I could do;
- but to navigate over suggestions from `clang-format` with comfort I needed a proper log format;
- to do that, I had to update `Makefile`;
- but since I had to work with `Makefile` anyway, I decided to [unify its style](https://github.com/ia/IronOS-plus/blob/da5534d56176a12b12a166c6b0d893ee77ae2aef/source/Makefile#L230) first too;
- then I updated `check-style` target - now it should show [gcc-like error line](https://github.com/Ralim/IronOS/actions/runs/5538230694/jobs/10107956061#step:5:234) pointing out to `file:line:column` which helps a lot in the environments where this format is used by default to navigate through errors in source code;
- and then little by little I was making suggested formatting changes.

Surprisingly, there were not so many big issues and considering that the rest of the files are having coherent style, I guess current tweaks of `clang-format` config relatively reasonable. Speaking of which, what I had to trade-off with:
- I disabled option to tell to make `include` in alphabet order (PinecilV2 / BLE stuff complexity of declarations in particular order from headers);
- I used _some_ suggestions for `heap_5.c` but then I excluded it since it's very hardware-specific piece as far as I understand;
- and after some jumps around I disabled `clang-format` **only for section** of `menuitem`s inside `settingsGUI.cpp` (once again, only due to very specific nature of this part of code).

Now, as of for these two _"expected checks"_... as far as I understand from [this conversation](https://github.com/orgs/community/discussions/26698#discussioncomment-3252954), since there is an update of `workflow/push.yml` which is related to origin repo/branch management, github doesn't allow (even as a part of Pull-Request) to mess with jobs/build steps. So I guess you should manually to commit changes into `workflow/push.yml` so everything would turn into green for merge here. And yes, in my humble opinion I would like to see test steps separated & renamed a bit but only if you don't mind. As always, will be waiting your reaction.

---

P.S.

I swear, I came to this project only to do a couple of PRs for tiny features for my own single one iron... and I even didn't have time to start work on them yet! :rofl:

**Comment by ia** [comment]
And here is how build steps [look](https://github.com/ia/IronOS-plus/actions/runs/5539173858) with current `push.yml`.

**Comment by ia** [comment]
Brief status update:
- the more I worked with `clang-format` the more I see the usefulness of it to a certain degree;
- since 99%[^1] of IronOS code formatted according to current `.clang-format` config, I decided to make it pass the checks and even kept `SortIncludes` option;
- there is also [very useful option](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#insertbraces) `InsertBraces` for `clang-format` but **it supported only since version `15`** while reference version of `Alpine Linux` for `docker` has `13`;
- but I did a bit of some `sed`/`grep` syntax madness to implement the imitation of this option since I work on this anyway;
- I'm sorry if it's getting too far especially with _"manual"_ unification of some parts of code but you always can tell me what to fix/undo;
- I understand that code review for this merge could be complicated but we can discuss any concerns (my own is that I hope I didn't miss/put extra bracket or something which can be detected only in the field);
- but in general currently I personally consider this task as **complete**.

Please, let me know what you think because I can't wait to hear back from you & crew.

P.S. If I have to rationale the braces for loop/conditions then I can say that in the most inappropriate moment it can easily fire back when you in the heat of testing/debugging/fixing put just only one extra line to some block not having them.

[^1]: 100% in this branch

**Comment by ia** [comment]
I have a couple of thoughts how to improve a bit _manageability_ of `check-style` [target](https://github.com/ia/IronOS-plus/blob/382ae15d04113cf6147f68546ea8bd30472dd177/source/Makefile#L882) in `Makefile` but I would like to make it as a separate pull request (in case if this one will be accepted) since this one is getting pretty bloated already.

**Comment by Ralim** [comment]
Yeah definitely seperate PR.

I think this is good to go btw, just want to recheck when I'm more awake 😂

**Review by Ralim — APPROVED** [review]

**Pull request merged**
