### PR TITLE
New translations format

### PR DESCRIPTION
**Pull request by Ralim**
Work in progress; looking to migrate translations to be editable using Weblate's online editing system as well. To make it easier for people who dont like the translation editor or editing json files directly.

~This will not merge until I have confirmed Libre project hosting with Weblate. But open for criticisms :)~
Hosting confirmed.

~Now just waiting for 2.20 to go out and bugs fixed.~

This _should be good to go_. Waiting to test a bit more and then we are good and I can _finally_ finish Weblate integrations fully.

### CODE REVIEW

**Comment by discip** [comment]
Greetings Ben,
unfortunately I have to report, that something broke with this PR.

1. https://github.com/Ralim/IronOS/blob/fba69977d817dd1a7ceb1032dfecb7dd6bf29194/Translations/translation_EN.json#L60-L61 is misspaced: Instead of being drawn on the right, it overlays the lower half of the menu name on the left.

2. The following 3 texts are garbled in that:
   1. they do not scroll &
   2. only the lower half is displayed:
https://github.com/Ralim/IronOS/blob/fba69977d817dd1a7ceb1032dfecb7dd6bf29194/Translations/translation_EN.json#L33-L40

Looking through the changes you made, I was not able to spot the responsible part.

thanks in advance
kind regards

**Comment by Ralim** [comment]
Thanks for checking; will try and patch. Was expecting a few of these to break.

**Comment by discip** [comment]
@Ralim
I don't know if I was supposed to test after this commit, but I did and unfortunately multilingual is still broken.

**Comment by Ralim** [comment]
Yeah; though its _slightly_ less broken.
Just still trying to figure out how I've managed to break the index lookup table _sigh_.

**Comment by discip** [comment]
@Ralim
### Ah!, just noticed that the issues with the _single-language-version_ are gone. 👍🏻

In the meantime, did you have a chance to think about what else could have gone wrong? 😊

**Comment by discip** [comment]
@Ralim
## Ah!, just noticed that the issues with the _single-language-version_ are gone. 👍🏻

In the meantime, did you have a chance to think about what else could have gone wrong? 😊

**Comment by Ralim** [comment]
@discip 
Multi language and single languages should now be fixed 😓 
Have bought back up to sync with `dev` as well.

**Comment by Ralim** [comment]
Would be mint if you could give it a quick pass over.
Also validate the reboot on settings reset works fine on Pinecil 1 and 2 for me here.

**Comment by discip** [comment]
Thanks.
Unfortunately I'm currently not at home.
Will definitely do, as soon as I am back.

**Comment by discip** [comment]
## Works as expected for both **`TS80P`** and **`Pinecil`**. 👍🏻

**Comment by Ralim** [comment]
Amazing thank you.

No rush was implied, you still tested before I woke up lol. 😍

**Pull request merged**
