### PR TITLE
Pinecil mod detection

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**

Expanding the shown type in the debug menu to indicate if VBus is connected or not.
This allows user to check the VBus mod presence on a Pinecil for use over 21V

* **Other information**:

Would love _any_ pinecil testers (both modded and not).

It should show `PD W. VBus` if you have not done the mod, and `PD No VBus` if you have done the mod.

### CODE REVIEW

**Comment by River-b** [comment]
Updated to firmware 2.16.FB29770  06-02-22

using USB-c to usb-C cable to PC.   because that has enough power to view menu, selected minus long hold, then + to scroll through debug menu.   I can see other settings like HW, time, move, rtip, ctip,  CHan, Vin, ACC,  PWR DC, Max,  Hall 
and nothing else,
It does not show me PD setting at all.

**Comment by willlovesbearz** [comment]
Flashed the Sciencil, registers PD No VBus, main pinecil registers PD W. VBus

**Comment by River-b** [comment]
Connected to Pinepower USB-C 65W port. 
menu correctly shows PWR PD No Vbus     (And I have modded my pinecil to 24V)
might be better if it said  
PWR DC 24V modded   and   PWR  DC 21V no mod

**Comment by River-b** [comment]
Also tested by connecting  old google pixel 2 cellphone (PD device)   by  usb-c cable to Pinecil and shows same PD No Vbus  correct message as my pinecil's are 24V modded.
image
PD_phone_usb-c_to_Pinecil_2
Also tested connecting usb-C  to anker usb-c 36W  charger.
IMG_1474

All worked correctly and displayed same message indicating that my Vbus is not connected to PD and I have a successful cut of my trace.

**Comment by Ralim** [comment]
The mod is for Pinecil only, Miniware TS80P should show No VBus

VBus is a pin on the FUSB302 used for USB-PD negotiation that does not need to be connected and infact can cause issues if it is connected and you connect > 21V to the input on the Pinecil. So this is for detecting if VBus is actually wired up or not.

The iron should _not_ restart itself though.

I cant reproduce the restart here? :/

**Comment by Ralim** [comment]
Shouldn't be related; does it restart any other times (not in the menu) ?

**Comment by discip** [comment]
1. It does not crash immediately.
2. I do not need to press any button.

I just tried it using different plugs:

Power Supply  | tech |  state
-|-|-
**[Anker Nano II 45W](https://de.anker.com/collections/wandladegerate/products/a2664311)**|**PPS**|**resetting**
**[UGREEN 65W GaN Charger](https://www.ugreen.com/products/65w-gan-usb-c-fast-charger?variant=32127034654782)**|**fixed value**|**not resetting**

**Comment by Ralim** [comment]
Ahh wait,  its probably because the TS80P does the software I2C (slow) and PPS needs the timings :/

**Comment by discip** [comment]
Since this is not needed for the **TS80P** anyway, I recommend limiting this exclusively to the **Pinecil**, instead of working this out. 😊

What do you think?

**Comment by Ralim** [comment]
Made pr to mask check.
I wish Miniware just had some brains in their design team :/ but yeah fair enough

**Pull request merged**
