### PR TITLE
Pinecil pd tweaking

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**

* Raise PD max voltage to 21V (for PPS)
* Adding a PD read out menu
* Cache VBus mod a bit
* Add VBus mod info to PD menu as well

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**
If on Pinecil, and you boot while holding the front button (+), it will allow inspecting the PD data.
Pressing the rear button (-) will exit the menu and continue boot
* **Other information**:

### CODE REVIEW

**Comment by discip** [comment]
Is this only applicable to the **Pinecil**?
Could this work for the *miniware* devices as well?
Or is certain hardware required for this to work which is not present in *miniware* devices?

**Comment by Ralim** [comment]
The code will not fit on the TS80P sadly

**Comment by discip** [comment]
Oh that's a pity.

**Comment by Ralim** [comment]
Its only a few bytes saved; so not enough.
And I dont have a lot of time at the moment to spend on this part of IronOS; and this is mostly a feature requested by the Pinecil chat, so focusing there first. 😓

**Comment by discip** [comment]
No worries, you do need to feel bad about that! 😃
Just thought of being able to check PD readings without having to use an external device.

**Comment by discip** [comment]
What changes for the **TS80P** regarding https://github.com/Ralim/IronOS/pull/1272/commits/9689c057347ea538745f2d33ab2e47ef57313c54?

**Comment by Ralim** [comment]
Not using freestanding mode so lto can drop a tiny bit more code. Frees up around 200 bytes, enough that we squeeze in

**Comment by discip** [comment]
Does that affect the accuracy or the performance some how?
Sorry for this questions, but I really don't understand much about this. 😓

**Comment by Ralim** [comment]
Should not, just trades off different types of optimisation :)

**Comment by discip** [comment]
What about the *hall related stuff* @alvinhochun brought up?

**Comment by Ralim** [comment]
It will save like 5 bytes; which is not a huge amount 🤣

**Comment by discip** [comment]
You raised my concern by adding the crying smiley (😢) to the commit, what was it than about if there is nothing worrisome?

**Comment by River-b** [comment]
where could I find the pinecil.zip for this I have a PPS  psu I could test it on.

**Comment by River-b** [comment]
here is some testing (video) I did with multiple chargers.  only weird thing is that I am seeing  3.5amps on chargers that say on box  max 3.25amps.  non_daniel said I can not trust the 3.5amps.
Also I did some testing with a USB-Tester between the Pinecil and the  Charger, and I notice if I flip the cable over , then I get a State 6 instead of a State 12.  here you will see the special EPR (240W cable)  but I got the same results with my  100W emark cable.
Here I'm testing on 3 different chargers (1-white no name 'cirtek' brand, 2- pinepower desktop, 3- some low cost PD65W charger small black one)

notice when I  flip the Cable that is plugged into the right side of the USB-tester,  I get State 6
sometimes I don't get state 6 when I move from one charger to the next charger, but as soon as I RESET the tester button on the top, then I can repeat the problem over and over.  The tester is doing something to cause this?  notice also when I flip the cable I don't see the Welcome message on the tester.

**https://www.youtube.com/watch?v=dxAC8iQOVy0&ab_channel=RiverB.**

The tester I am using. https://smile.amazon.com/gp/product/B07DCTG6LH

**Comment by River-b** [comment]
I also am getting  [5  20v 3.5amps]  just using a normal  PD60W cable to Pinepower and  I don't think I should be seeing 3.5amps on that cable?  

This is using the red USB-C cable I bought from Pine64 + PinePower desktop.

**Pull request merged**
