### PR TITLE
Animation non block

### LINKED ISSUE #1330: Menu animation prevent moving quickly
**Describe the bug**

When navigating the menu items, there is some animation expressing a move between the items. The animation cannot be skipped. And is effectively limiting to at most one button press per second.

**To Reproduce**

Open the settings menu. Try to navigate faster than one action per second.

**Expected behavior**

Move to the next menu item as fast as I press the buttons.
Alternatively, an option to turn off menu animation similar to turning off icon animations.

**Details of your device:**
Pinecil, updated to IronOS v2.19.

**Additional context**

The original firmware on my Pinecil did not have animation when moving between menu items. This made navigating as fast as you can press the buttons. But somehow the software would lockup randomly. Once I didn't noticed the iron stayed on (and hot) for a full day. Hence why I upgraded the firmware.

Fun remark: This soldering iron has a computer more powerful than both my CNC router and my 3D printer. That is both amazing and horrifying at the same time.

Final note: the soldering iron is the best I have ever used. It heats up fast, and maintains temperature incredibly well (when it doesn't locks up that said).

### PR DESCRIPTION
**Pull request by Ralim**
Buttons can now skip an animation in progress
Animations are faster
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Should close #1330

### CODE REVIEW

**Comment by River-b** [comment]
This is related to Issue ticket #1330 also.

**Comment by discip** [comment]
@Ralim
I tried that with my trusty **TS80P** and have to say:
Only if you *press* and *hold* **B** the animations are skipped.
If you however only press **B** quickly in a consecutive manner there is only a minor speed change observable *imho*.

**Comment by discip** [comment]
@Ralim
What was this PR supposed to achieve?
Make the animation faster, leave the animation out completely on consecutive button-press?
How can I assist?

**Comment by Ralim** [comment]
Slightly faster animation
Dont allow animation playing to block you moving to the next item; so holding button or pressing rapidly should cancel animation and move on to next item as fast as possible.

**Comment by River-b** [comment]
some people said that on pinecil, they did not like the new animations b/c it was not keeping up with button presses. They want the ability to press the buttons fast and not be delayed waiting for the entire animation to complete. 
They were used to this in past firmware, but with the new animations, it affected their QOL and user experience.

**Comment by discip** [comment]
@Ralim
> or pressing rapidly should cancel animation and move on to next item as fast as possible.

Yeah, that is what I expected when I first read the description of this **PR**.
But as I pointed out above animations are only skipped when **B** is held down, there is **little to no change** if **B** is pressed in rapid succession, though!

ps: Does it work for you the way you described it?

**Comment by River-b** [comment]
I tried the beta and I like it , it's much faster now when I press the button fast, it seems to keep up on the display.  I had no issue just pressing the button slower, but other people in discord did complain about it not being like older firmware.  therefore Ralim made the beta. so you could skip  animations the moment you press the button.

**Pull request merged**
