### PR TITLE
Sequre T55 Support

### LINKED ISSUE #1885: Support Sequre T55 hot plate
**Is your feature request related to a problem? Please describe.**
While looking for a cheaper alternative to the MHP30/MHP50 I stumbled across the Sequre T55 hotplate. I would assume (naively) that it uses a similar microcontroller to the s60/s60p. Although it looks like a knock off of another mini plate that uses a stc51 (I’m not sure what the s60p uses)

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**

Adding support for the T55 hotplate.
Closes #1885.

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

Like all Sequre devices, the unit is designed to minimum cost. So there is no inductor or enough caps to filter out noise.
We get some PWM hum when running it as fast as we can to keep current regulation smooth.

### CODE REVIEW

**Comment by StevenSeifried** [comment]
As already commented in #1885: LGTM \
The only "issue" I noticed is, that some descriptions are a bit cut at the end.

**Comment by Ralim** [comment]
Thanks for testing, can you some examples of what is cut off ?

**Comment by StevenSeifried** [comment]
I clicked through all the settings and all the descriptions are cut off at the end.

e.g. Soldering settings -> Temp change short

**Comment by StevenSeifried** [comment]
Perhaps this is because the full OLED resolution is not yet supported

**Comment by StevenSeifried** [comment]
Hi @Ralim

can I help with anything else here? I don't know if I'm the right person to do a review.

I can only review the functionality, but not the code. However, if that is sufficient, I can to do the review

**Comment by ReimuHakurei** [comment]
Just got one of these and tested the firmware.

It's possible this issue is something broken on my end when building (the CI artifacts have expired so I can't test an official build for this), but the localization strings for the profile support seem to be missing, resulting in a blank menu item for all of those settings.

When I deleted all the `include` keys from the `translations_definitions.json` file and rebuilt, it displays fine. Not familiar with the codebase so couldn't find any obvious cause why those would be missing in the build.

**Comment by Ralim** [comment]
@ReimuHakurei 
I have not been able to replicate the profile mode issues you have mentioned here.
How did you build the firmware?

@StevenSeifried I believe the cut off should be fixed 😓

**Comment by ReimuHakurei** [comment]
I compiled the firmware with `make docker-build` on Ubuntu 22.04. The tests crash on that same system (looks like clang-format shipped on 22.04 is likely too old to support the config in this repo) so it wouldn't surprise me one bit if its my build environment. 

I'll test the latest CI artifact this evening and see if it works properly there.

**Comment by StevenSeifried** [comment]
> I believe the cut off should be fixed 😓

@Ralim the cut off seems to be fixed. I tested with the [current version from GitHub actions](https://github.com/Ralim/IronOS/actions/runs/9972758329) (German and English). I didn't click through all the settings and all the descriptions in both languages, just checked a few, but none of them was cut off

**Comment by Ralim** [comment]
@ReimuHakurei yeah that would make sense. I advise to do all commands inside the docker container to ensure we are all using the same tooling. Can you check it's working fine in the CI builds to compare against ?

**Comment by ReimuHakurei** [comment]
Can confirm it works correctly in the CI build.

**Comment by Ralim** [comment]
This is most likely something missing in the drawing modes for the higher res oled screen. I'll try and have a look tonight

**Comment by Ralim** [comment]
Phase printing should work now I think

**Comment by valzzu** [comment]
I just got T55 today and found this, hows the firmware coming along?

**Comment by StevenSeifried** [comment]
> I just got T55 today and found this, hows the firmware coming along?

Only @Ralim can tell it excactly, but I'm optimistic that the T55 will be officially supported with 2.23

**Comment by valzzu** [comment]
Cool

**Comment by Ralim** [comment]
Hardware should work, just the UI is limited

**Comment by FutureJames** [comment]
I'd like to help test.  If I hold one button while plugging the use cable into a laptop, it I get a message "UPDATE V11.00 [READY]" on the device OLED.  I would have expected it to show up as a usb mass storage device on the laptop to copy over the new firmware, but no luck.  Are you guys using a DFU tool or something to load the ironOS firmware?

**Pull request merged**
