### PR TITLE
Dutch translations

### PR DESCRIPTION
**Pull request by ColoMAX**
- Improved translations for NL and NL_BE
- Fixed some text after testing
- Improved translation for NL and NL V3_BE
- Fixed some wrong spelling and totally wrong translations. 
- Added some missing translations. 
- Modified single char option in menu. 
- Not tested on display.

continues & resolves #1830

### CODE REVIEW

**Comment by discip** [comment]
@ColoMAX
Thank you for this PR.
Would you please try the compiled version and report back in order to get this merged?<

thanks in advance
kind regards

**Comment by discip** [comment]
@ColoMAX
Thank you for this PR.
Would you please try the compiled version and report back in order to get this merged?

thanks in advance
kind regards

**Comment by ColoMAX** [comment]
Trying it on the Pinecilv2, but the settings QCMaxVoltage till PDVpdo are not getting displayed, also Bluetooth the setting. But this is also true for the EN version, so this is more likely a bug to do with the custom boot logo I previously installed, and does not seem to go away with subsequent firmware uploads.

I used the newest blisp from soure for all uploads.

**Comment by discip** [comment]
Try the following:

1. Flash the Boot-Logo you want _(**it has to be `*.dfu` though**)_ [logos for Pinecil-V2](https://github.com/Ralim/IronOS-Meta/releases/download/latest/pinecilv2.zip):

   ```
   sudo blisp write -c bl70x --reset IronOS.gif.dfu
   ```
3. Flash IronOS [wirmware for Pinecil-V2](https://github.com/Ralim/IronOS/actions/runs/7343147381/artifacts/1137185514):
   ```
   sudo blisp write -c bl70x --reset Pinecilv2_multi_compressed_European.bin
   ```

On my Pinecil-V2 this works as expected.

**Comment by discip** [comment]
Nice!
So, is this good to be merged it finally? 😊

**Comment by discip** [comment]
Nice!
So, is this good to be merged in finally? 😊

**Comment by discip** [comment]
Nice!
So is this good to finally merged it in? 😊

**Comment by discip** [comment]
@ColoMAX
Nice!
So is this good to finally merge it in? 😊

**Comment by ColoMAX** [comment]
> @ColoMAX Nice! So is this good to finally merge it in? 😊

Yes, although I have found that the Ralim/dev (166cf934) has the same problem with multiple languages not displaying all settings titles. Whilst the latest release does work correctly.

**Review by discip — APPROVED** [review]

**Comment by discip** [comment]
Please try the latest build:
https://github.com/Ralim/IronOS/actions/runs/7451884972

**Pull request merged**
