### PR TITLE
Fixes for I2C on Pinecil + USB-PD stack

### LINKED ISSUE #1070: DFU Flashing error for the new DFU files on Windows
**Describe the bug**
"More than one DFU capable USB device found!" Error when flashing Pinecil 2.16 dfu file on Windows.

**To Reproduce**
Following the Flashing Guide for Pinecil I ran the following command:
dfu-util -D Pinecil_multi_compressed_European.dfu

The output is the following:
`More than one DFU capable USB device found! Try --list and specify the serial number or disconnect all but one device`

Running the --list command gives:

```
Found DFU: [28e9:0189] ver=0100, devnum=9, cfg=1, intf=0, path="1-1", alt=1, name="@Option Bytes  /0x1FFFF800/01*016Be", serial="3TBJ"
Found DFU: [28e9:0189] ver=0100, devnum=9, cfg=1, intf=0, path="1-1", alt=0, name="@Internal Flash  /0x08000000/128*001Kg", serial="3TBJ"
```

Flashing with more flags to set the partition succeeds:
`dfu-util -a 0 -D Pinecil_multi_compressed_European.dfu -s 0x08000000`

But the device does not boot at all. The screen is black and usb reports a bad usb device. Reverting back to 2.15 works fine.

**Expected behavior**
Flashing to succeed without the error

**Details on your device:**
 - Device: Pinecil
 - Release: 2.15

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**

Finishes off and closes #1024 
Should close #1070 as well

* **What is the current behavior?**

Two issues:

* IRQ's were not quite right for PD
* Loots of edge cases in how the Pinecil I2C code handles disturbances to the I2C bus
* * Turns out the SCA model accelerometer was more sensitive to these
* * Ended up going to a blocking I2C read for now, which is non optimal but same speed and _works_

* **What is the new behavior (if this is a feature change)?**

Above issues should be fixed

* **Other information**:

Would love if people who have time (dont blame you if you dont); could test this and report back.
Should have 0 effect on non-PD devices (TS100, TS80) but if one has time would love a sanity check as well.

If it does or doesn't work for you, could you _please_ include your accelerometer version details <3
If it breaks, if you could list what power supply it would be awesome.

Tested confirmed working on:

- [x] Pinecil BMP
- [x] Pinecil SCA
- [x] TS80P (LIS)
- [ ] TS80
- [ ] TS100
- [x] MHP30

### CODE REVIEW

**Comment by Ralim** [comment]
@Firebie and @discp you may be interested in this.

_Really_ hoping I have fixed the issues for this @Firebie with this 😅

**Comment by Firebie** [comment]
No, with enabled PD still freezes. I suspect broken PD chip.

**Comment by Ralim** [comment]
Gah damn, was really hopeful it was this. Sorry :(

**Comment by HanaO00** [comment]
Pinecil SC7A20, on PD power, it works perfectly, no more freeze or small pixels at startup

**Comment by discip** [comment]
@Ralim
Works here too.
But for some odd reason the temperature readings jump around on **Pinecil** just like it did with the bad tip on my **TS80P**.

One thing I think I will not be able to deal with myself is the weird flashing scrollbar in QC voltage.

**Comment by Ralim** [comment]
@discip 
What temp are you testing at and what tip are you using?
I cant see any real fluctuation on either ADC mode; but I havent tested all of the tips in my holder.

Ah the scrollbar flash is a bit odd hmm not sure a huge amount can be done trivially either

**Comment by discip** [comment]
@Ralim
Good evening.
Sorry for the late response.
1. First 320 deg C
Than remebered, that it might help letting the tip burn in for some time so raised to 400 deg C.
Unfortunately no change yet.
2. It's the tip that came with the **Pinecil**.

**Pull request merged**
