### PR TITLE
Cleanup OLED_FLIP logic

### PR DESCRIPTION
**Pull request by Ralim**
Just cleaning up some OLED logic to be a bit cleaner

### CODE REVIEW

**Comment by discip** [comment]
Did just check for **TS80P** & **Pinecil**.
## Working for both! 😁👍

**Comment by discip** [comment]
@Ralim
Sorry, but...
Now the stock screen is broken in lefty mode for **TS80P** & **Pinecil**.

**Comment by Ralim** [comment]
Eugh, im on it

**Comment by Ralim** [comment]
Wait which bit is broken for you?

**Pull request merged**
