### PR TITLE
Generate a mkdocs github page + Migrate documentation links to use it

### PR DESCRIPTION
**Pull request by Ralim**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Making documentation nicer to read
Serves nicer docs at https://ralim.github.io/IronOS/

* **What is the new behavior (if this is a feature change)?**
* Github action automatically updates documentation on merge into dev
* Links are updated from linking to the `.md` files to instead point to the new docs page

### CODE REVIEW

**Comment by Ralim** [comment]
@discip @River-b 
I think you two are the main ones I'd love to double-check this.
If its a thumbs up from you, it would be great.

Its all still made from those `.md` files that we have had before and then the `mkdocs.yml` file defines the menu down the left side.

I'm thinking the new setup with that menu should make organisation and access easier.

**Comment by discip** [comment]
Greetings,
will have to look into this later, I am currently at work.

**Comment by discip** [comment]
Greetings,
generally speaking: Automation is highly welcome!
Otherwise, I will have to go through it later, since I am currently at work.

**Comment by Ralim** [comment]
No rush, happy to wait for people to have a look :)

**Comment by discip** [comment]
Sorry for being slow. 😅

I only managed to get a glimpse of what you did.

1. Automation is your territory anyway, so I did not even bother checking that.

2. Content wise:
   1. I think there is nothing new.

   2. But one thing confused me a bit.
As you know I do not like redundancies especially regarding information.

   In your PR there are 2 sets of **`.md`** files.
If you plan on moving documentation to this new (much more appealing) location, then a temporary redundance is no problem. But in the long run one set of **`.md`**'s should be removed. This is just my opinion though.

**Comment by Ralim** [comment]
Yeah nothing new added, just setting up automation to take the contents of the Documentation folder and turn it into the docs site.

There is only one "set" of .md files, but a bunch of noise from me moving them around.
Any changes we make to the .md files in the Documentation folder will be pushed through via this automation once merge.

I will have to look into the formatting issue

**Pull request merged**
