### PR TITLE
Update BG translation for PD mode options

### PR DESCRIPTION
**Pull request by ia**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Update RU translation for PD mode options.

* **What is the current behavior?**
Description for PD mode and its modes are not translated.

* **What is the new behavior (if this is a feature change)?**
Translated description for PD mode and for its modes.

* **Other information**:
Before submitting the patch I did make a set of custom builds to find the most adequate _"adoption"_ to make it fit and to have it clear (as much as possible) at the same time for an average user.

Also, I tried to get some additional information about options and what exactly they do [here in a form of code review comment](https://github.com/Ralim/IronOS/pull/1917). But I think I figured it out after all, more or less.

P.S. As always, I understand we all busy with our lives as well. But I still determine to keep dedicating some of my time to this project when I can with everything I can.

### CODE REVIEW

**Comment by Ralim** [comment]
The code review comment never posted? Did you make sure to submit it from pending?

**Comment by ia** [comment]
> The code review comment never posted?

Oh... wait, indeed! It has "Label: Pending". I thought what it means is "now it's waiting for reply"! Oops... :flushed:

> Did you make sure to submit it from pending?

I feel myself ashamed asking this but... how should I do that exactly? I don't see any "publish"/"submit" code comment button in that PR form. Is it possible that it's because that pull-request (#1917) is merged & closed already? Just curious.

UPD: Aaaaaa... I got this! Ufff, wow, now I see! My bad indeed. Will publish it in a couple minutes. Sorry.

**Comment by ia** [comment]
Status update: just don't merge this yet, please. I will prepare a little update in a day or so.

**Comment by ia** [comment]
> Status update: just don't merge this yet, please. I will prepare a little update in a day or so.

Done. Now it should be sound a bit more clear.

**Review by Ralim — APPROVED** [review]

**Pull request merged**
