### PR TITLE
Convert logos directly into DFU format

### PR DESCRIPTION
**Pull request by cybernesto**
* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Feature: Modified python script to support writing .dfu files directly. This simplifies the flashing of a logo.

* **What is the current behavior?**
`img2ts100.py` creates .bin files that must be flashed with a complex `dfu-util` command.

* **What is the new behavior (if this is a feature change)?**
`img2ts100.py` can create .dfu files directly.

* **Other information**:
Replaced .bin and .hex pinecil logos with .dfu files.

### CODE REVIEW

**Comment by cybernesto** [comment]
I forgot to fetch the upstream before doing this branch. Sorry if this is causing extra trouble. Let me know if there is something else I should do.

**Comment by Ralim** [comment]
Can you merge master in to your branch if you have a chance?
I can sort it but not for a bit 😓

**Review by Ralim — APPROVED** [review]

**Comment by discip** [comment]
@cybernesto & @Ralim
I just realized that flashing a **`*.dfu`** logo to the **TS80P** running the new [dfu bootloader](https://github.com/Ralim/IronOS-dfu) does not work!
Although it flashes everything correctly, judging by the output in **`cmd`**, on the iron no logo is installed! 🤷‍♂️

Is this due to the *custom **bootloader***?

btw:
Also realized that except for ***Pinecil.dfu*** all other files named **`.dfu`** are in fact **`.hex`** files.
Of course I tried flashing the only real dfu *(**Pinecil.dfu**)*.

ps: No effort yet to change the fake **`.dfu`s** to real ones until this is fixed.

**Comment by Ralim** [comment]
The .DFU file is only for the pinecil; since the location for the image is different between miniware and Pinecil.

**Comment by discip** [comment]
So the option for a bootlogo is not available for miniware devices using the new bootloader?

**Comment by Ralim** [comment]
At this point in time, since the alternative bootloader still isn't something I'm pushing, you would need to make them yourself as the value for `DFU_LOGO_ADDRESS` is different and you would need to change it to `0x0800F800` to match the address the smaller flash STM32's are expecting.

Not focusing on this _right_ now since at some point the whole logo mess needs a clean up _anyway_. And I need to figure that out first

**Comment by discip** [comment]
Ok.
I got you! 👍
Will not bother you on this any more until you take care of it. 😊

**Comment by cybernesto** [comment]
> Also realized that except for _**Pinecil.dfu**_ all other files named **`.dfu`** are in fact **`.hex`** files.
> Of course I tried flashing the only real **`dfu`** _(**Pinecil.dfu**)_.

Something must have gone wrong during the merge. My branch had indeed valid .dfu versions of IronOS, Pinecil_L and Pinecil. It's an easy fix though.

@Ralim should we add a new option for the TS80P so that it considers the different addresses?

**Comment by Ralim** [comment]
Yeah not sure when things went AWOL, but working on it now.
Going to pull them out of this repo to their own with auto building. Then link to them instead, just to keep noise down :)

**Comment by cybernesto** [comment]
Sounds fair. Let me know if you need any support.

**Pull request merged**
