### PR TITLE
Remove register keyword according to ISO C++17 for fixing related warning

### PR DESCRIPTION
**Pull request by ia**
* **Please check if the PR fulfills these requirements**
- [ ] The changes have been tested locally
- [ ] There are no breaking changes

* **What kind of change does this PR introduce?**
Fix warning from compiler.

* **What is the current behavior?**
`Pinecil` build generates a lot of messages with the same type of warning.

* **What is the new behavior (if this is a feature change)?**
`register` keyword is removed from _source/Core/BSP/Pinecil/Vendor/NMSIS/Core/Include/core_feature_base.h_.

* **Other information**:
Not an C++ expert but as far as I understand, here is the situation:
- _ISO C++17_ standard is used while compiling `Pinecil` build;
- the standard tells that `register` keyword has no any effect (_my guess_ is that now it's up to compiler's decision whether or not to save the variable value in CPU register);
- some variables declared with `register` keyword in `core_feature_base.h`;
- plus, there is `-Wregister` flag for the build;
- hence, the build output log is overwhelmed with a lot of warnings like:
```
core_feature_base.h: warning: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
|   register int32_t result;
```

I didn't cross the checklist though since I haven't tried the build on the hardware to make sure that it doesn't break anything on the device but since the keyword has no meaning _I guess it should be ok_.

### CODE REVIEW

**Comment by Ralim** [comment]
I have no issue with the PR; I'll test on hardware this week (nag me if I dont get back to you)

**Review by Ralim — APPROVED** [review]

**Comment by discip** [comment]
@ia
Sorry for the late answer.
I was able to briefly test this on the **`Pinecil-2`** & on the **`S60P`** but unfortunately not yet on the **`TS80P`**.

So far nothing seems to be broken.

Is there anything particular to look out for?

**Comment by ia** [comment]
> @ia Sorry for the late answer.

No-no, don't even worry.

> I was able to briefly test this on the **`Pinecil-2`** & on the **`S60P`**

Thanks!

> but unfortunately not yet on the **`TS80P`**.

Yeah, sorry about that... I saw your comments from another discussion: it seems that yours is half bricked now. I'm sincerely really sorry to hear that :(
I wish I could help you but I don't have any experience with unbricking/reflashing `TS80P` through _SWD_ myself _yet_.

> So far nothing seems to be broken.

Really appreciate your help!

> Is there anything particular to look out for?

Well, this particular change goes for _Pinecil V1_ **only** so if you can check just basic _OK_ behavior on _Pinecil V1_ then it would be awesome. If not - that's fine, don't worry.

**Comment by discip** [comment]
@ia
> Yeah, sorry about that...

Thank you! 👍

> Well, this particular change goes for Pinecil V1 only so if you can check just basic OK behavior on Pinecil V1 then it would be awesome. If not - that's fine, don't worry.

I'll let you know as soon as I get my hands on it.

**Comment by Ralim** [comment]
Tested on two units here and works perfectly ❤️ 
Thank you for this

**Pull request merged**
