### PR TITLE
reorder debug menu . . .

### PR DESCRIPTION
**Pull request by discip**
. . . and added in the headline for **`Tip Res`**, but since I do not know its exact purpose, I left it to be completed by e.g.: @Ralim

### CODE REVIEW

**Comment by River-b** [comment]
@discip  hi,  I had the items ordered by how they appear in the debug menu on the screen. 

note the sentence: "so they use short codes and appear in this order:"

_unless_ the Debug menu has been changed now and  items are in a different order for new 2.20 coming up?

**Comment by discip** [comment]
@River-b
I did reorder how *'the items appear on the screen'* as well.

**Comment by River-b** [comment]
thanks

**Comment by Ralim** [comment]
`Tip Res` is the Tip Resistance.

For Irons that have multiple possible values, and the iron is automatic sensing (Pinecil V2) this will show the value the Iron is using.

**Comment by discip** [comment]
@Ralim
Thanks! 
I knew about it representing the tip resistance, but I was not sure, if this was all to it. 😅

**Comment by discip** [comment]
@Ralim
Thanks! 
I knew about it representing the tip resistance, but I was not sure if this was all to it. 😅

**Comment by River-b** [comment]
the V2 Pinecil is auto-sensing,  But the V1 has different hardware and can not do this.  Ralim mentioned the V1  is getting code where we can manually select either  6.2 ohm (short tip) or 8 ohm ( long standard tip).   needed because Pine64 will offer new design  shorter high performance tip soon (fits in all ts100 style irons and heats faster).

**Pull request merged**
