### PR TITLE
USBPDDebug: Check whether VPDO is EPR or PPS

### PR DESCRIPTION
**Pull request by Samuelrmlink**
* **Please check if the PR fulfills these requirements**
- [*] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**
Bug fix

* **What is the current behavior?**
SPR PPS VPDOs are being classified as AVS EPR VPDOs. 
This results in an incorrect wattage value being displayed in the PD Debug menu. 

* **What is the new behavior (if this is a feature change)?**
VPDOs are identified. 

  - PPS - maximum current is shown. (As provided by the source)
  - EPR - maximum wattage (PDP value) is shown. 

* **Other information**:
Referencing Table 6-13 and Table 6-14 from the "USB Power Delivery Specification Revision 3.1, Version 1.7" (Pages 138, 139)

  - It should be noted - this change has not yet been tested on EPR power adapters as I don't have any on hand.

### CODE REVIEW

**Comment by River-Mochi** [comment]
@Samuelrmlink  I can't seem to find a working zip of this PR from above verified numbers, could you give me a link to it so I could test this? 
Are there specific chargers I should focus on? I have a bunch  PPS/ non-PPS/ EPR 28V ?
one of each?   what should I be checking for?
- that all of them behave like they did before and no obvious things?
- does V1 and V2 have to be tested or only V2 to save me time?

**Comment by dandimi** [comment]
V1 tested on Baseus 120w gan pro, no issues, no reboots, in pps mode
tested on samsung 25w charger, negotiated 11v, works, no issues
tested on ravpower 45w powerbank with no pps support, negotiated 15v
all power check in debug menu seemed alright and accurate

**Comment by River-Mochi** [comment]
### Tested Devices one V1, and two V2.
- Chargers used: 
--one random 20V charger
-- one PinePower portable PD 65w/20V
--one PPS charger with both 100W port and 65W port, both ports tested using both PD60 cables and PD240W cables.
-- one EPR 28V charger tested with 240W EPR cable.
### Results
-  PD debug menu looked normal
- testing heating up on all  was normal, wattages showed expected amounts
-  does not appear to cause any strange side effects
- tested in Detailed screen and no-detail screen
- 
### Additional information
- Reboot on start-up  behavior seen on V2 that did not happen a single test with the V1 Pinecil on any of the 4 chargers tested.
This may have nothing to do with this repo, but I want to note this side behavior that happened:
- on Both V2 tested, _sometimes_  when I plugged in the cable to the back for a split second, it would show the symbol for no tip installed and 5V but quickly jumped to normal.  This did not happen every single time I plugged in more like 1/8 times. and sometimes the screen would be black for a split second like it was rebooting and then it was fine. it did not matter which way the cable was flipped. The rebooting at startup happend with Kovol EPR charger that I happen to have handy in the room. Rebooting at startup could be repeated more than the symptom of initiallly seeing icon for no tip inserted.
in all cases, if I waited a couple seconds or simply re-plugged in everything was normal.  I did not see it happen plugging into the 20V USB-C chargers, however I did not test them enough to know for sure. Pinecil V2 still works fine, it's just this odd reboot and occasionally. 

**Otherwise. I think this is fine, nothing jumped out as affecting operation on Pinecil V1 or V2.**

**Comment by River-Mochi** [comment]
Also ralim, I don't  know if you remember this Huwder 150W PPS charger, (3 usb-c ports, 1 usb-A port) with a 100W C port and a 65W C port. 

It would reboot on plug in but then be fine. it's still finicky and reboots during start up or simply Pinecil will just stay Black screen (see photo). re-plugging back in fixes it and it works if it stays black. if  it reboots then it just starts working no replug needed.

this is pre-existing issue with this charger. but I thought I would test it since there have been so many updates maybe it was magically fixed from last 6 months of repos.
Photo is plugged into the 100W pps port - that reboots in first few seconds, but sometimes like here it just stays completely black. replug fixes it and then charger works.
IMG-3546

**Comment by River-Mochi** [comment]
> PPS power profiles have a maximum current rating, while EPR profiles have a wattage rating. This was already implemented in the PDDebug menu - there just weren't sufficient checks previously.

@Samuelrmlink   since you dont have V2 yet, I made a video so you can see what we see.
-  PD debug on 28V EPR charger and Pinecil V2.  It normally just shows up as 

`8  28V     5. 0A  for me`    ( no idea why there is a space there but there is always the space too) 
as far as the pd debug display,  it  always showed  28V 5 amps as far as the menu display and doesn't show us in watts  on Pinecil V2. 


https://user-images.githubusercontent.com/97197236/223012156-63254245-fdf1-4259-ba7e-2e934335865b.mp4

**Review by River-Mochi — APPROVED** [review]
tested here  https://github.com/Ralim/IronOS/pull/1600#issuecomment-1455244859

**Comment by Samuelrmlink** [comment]
@River-Mochi 
Thanks for the video - there were a few things in it that stood out to me. 

1. PDO index number jumps from 6 to 8 (skipping 7) with your EPR charger. 
2. Your 28 volt EPR PDO is displaying as though it were a PPS profile (???)

Looking over the code we have here and the USB-PD spec I haven't been able to spot why your EPR PDO is displaying as current. It should be displayed as wattage, since that is how EPR PDOs are framed in the PD spec. 
_It may be possible that your charger is not following the spec??_

Do you have a PD analyzer?

**Comment by Samuelrmlink** [comment]
On a secondary note - I just added another commit to this PR to change the appearance of the current readout. 
See below. 

**Old:**
 1   5V   3.  0A
 2   9V   3.  0A
 etc....

**New:**
 1   5V   3.00A
 2   9V   3.00A
etc....

**See Commit 9a16eb8fa8b81d56c659a0cf7f089c623848806c
Builds:** 
[Pinecil-ctz.zip](https://github.com/Ralim/IronOS/files/10894693/Pinecil-ctz.zip)
[Pinecilv2-ctz.zip](https://github.com/Ralim/IronOS/files/10894694/Pinecilv2-ctz.zip)

**Comment by River-Mochi** [comment]
> 1. PDO index number jumps from 6 to 8 (skipping 7) with your EPR charger.

I can test on my other EPR (Apple 140W)  but I think it's always 8 for EPR.

**Comment by River-Mochi** [comment]
> Do you have a PD analyzer?

yes I have the KM002C (chargerlabs) with the PC software to save logs.

**Comment by Samuelrmlink** [comment]
> > Do you have a PD analyzer?
> 
> yes I have the KM002C (chargerlabs) with the PC software to save logs.
Could you go ahead and take two captures? One with the Apple EPR charger, and the other with your generic EPR charger?
(I also have the ChargerLabs KM002C unit and the appropriate software for it - so I can open their file format.)

> > _It may be possible that your charger is not following the spec??_
> 
> * I don't totally  trust the Kovol 140W 28V to  follow the specs, they were so cheap the other port on this is a QC2.0 not even QC3.0.  that is why I dont recommend it to people, it works but there are so many better ones.
> * Apple 140W 28V I have should follow spec.  they sit on the USB-IF board  so they get exceptions put in to accomodate for what they are doing. technically we can say apple would be compliant bc they make it so. but these chargers are meant to have the weird apple tip at the other end and not for USB-C to C EPR cable. but it works since they have to comply bc they sit on the board.
Absolutely. Apple's chargers are pretty much guaranteed to follow the spec since they are the top company on the board & spearheading the USB PD spec. 

> * I don't understand USB-PD code but  does Ralim allow it to display watts instead of Amps in that section. All chargers on all Pinecil V1 and V2  **ever since PD Debug menu came out in 2.17 release have shown for me  as Amps inside PD Debug and never have I seen watts.**  I've tested a few chargers and seen test results from other people, no watts are inside PD debug menu. maybe this needs to be enabled?
Yeah it's possible that my interpretation of the specification document may be flawed. 
I don't have the EPR-capable power source to test/compare against.
I just got my Pinecilv2 in the mail two days ago - but don't have any EPR chargers.

**Comment by River-Mochi** [comment]
This is my Apple EPR  PD3.1, 28V 140W charger. it is showing very different from the off-brand Kovol.
it shows a  "9" stage.

**`9   15-28V   140W`**
image

https://user-images.githubusercontent.com/97197236/223057379-86b9a631-f65a-489c-b5f5-c03cfa4bdff9.mov

**Comment by River-Mochi** [comment]
@Samuelrmlink your beta for V2 doesn't have the BLE built in. is it possible you bring in one of Ralim's newer approved versions of the beta so that I can test your features using  also PineSAM  which gives me extra information. 
it will be a beta version that in Advanced menu  there is a BLE checkbox to enable/disable. 
it was slated to be released with 2.21  stable.

**Comment by Samuelrmlink** [comment]
Last night’s build has BLE. 
https://github.com/Ralim/IronOS/files/10894694/Pinecilv2-ctz.zip

**Comment by River-Mochi** [comment]
> I noticed that BLE can take a minute before it shows up on your other device though.

it takes time for the  Windows/Mac/Linux PC  to pair with Bluetooth. think about when you pair speakers BLE with a PC, there is a time for scanning then pairing.   I usually plug in V2, start the script and then  if it doesn't connect on Browser I hit F5.  after that even if I quit the  terminal script and re-open, then  it's faster to connect in the Browser.
other thing you could do is pair inside windows first.

**Comment by River-Mochi** [comment]
Attached PD analyzer Logs and Videos of PD Debug for:
- Apple 140W 28V charger
- Kovol (off-brand) 140W 28V charger
[KM002-logs.zip](https://github.com/Ralim/IronOS/files/10905566/KM002-logs.zip)

https://user-images.githubusercontent.com/97197236/223327150-20c42d1c-f482-4129-adcc-020590e9aab0.mp4
https://user-images.githubusercontent.com/97197236/223327177-63b28100-842b-43ce-acb3-ca271a95d7a1.mp4

**Comment by River-Mochi** [comment]
@Samuelrmlink did you get a chance to look at the logs I attached; are you good now for this PR?

**Comment by River-Mochi** [comment]
fwiw.  I tested in Windows 11, and PineSAM does not connect if I first connect Pinecil to "windows bluetooth"

Pinecil has to be disconnected from all other OS/devices. and then when I open PineSAM, and let the script do all the backend connecting - then the browser opens and it's good. if the PC is a little slow working with the backend script, then I hit "F5" on the browser and it works.

**Review by Ralim — APPROVED** [review]
Code-wise this seems good to me, dont have a suitable charger for testing.
Has this been tested as working (Comments are not super clear)

**Comment by River-Mochi** [comment]
> Has this been tested as working (Comments are not super clear)

yes it has been tested by at least 2 people and it works.  I also sent some of my PD logs to Samuel as requested but did not hear back if he did anything with that. 

I tested with PPS  charger.  and Dancho (test results here above https://github.com/Ralim/IronOS/pull/1600#issuecomment-1448741201)  tested with PPS charger.   

Dancho/dandimi said this code helped him, his  PPS charger no longer reboots. 

I tested also with EPR chargers and it does not seem to cause any harm or break anything.

**Pull request merged**
