### PR TITLE
adjusted max brightness

### PR DESCRIPTION
**Pull request by discip**
As proposed https://github.com/Ralim/IronOS/issues/1078#issuecomment-929212314.

And updated *translation_EN.*

### CODE REVIEW

**Comment by Ralim** [comment]
I'm not against this, though I'm sure someone will ask for brighter screen options 😓 
Always a tradeoff between longevity and brightness

**Comment by discip** [comment]
@Ralim
Good afternoon Sir,
I am with you on that one, but after having observed the increase of brightness of **255** compared to **126**, I have to say the difference is barely noticeable, if at all.
@sandmanRO stated that as well:
> Increasing the value farther towards 255 would not lead to a significant extra gain in the actual contrast ...

If someone does not like this, than I will take this down.
I absolutely do not want to box anyone in! 😊

**Comment by sandmanRO** [comment]
Hello Gentlemen,
I do confirm that those finding are true for all four TS100 units that I have. I personally stopped at 100. 126 would probably "squeeze" the most of the remaining extra light this OLED is capable of. The issue is that once the OLED is no longer producing extra light it means the further we go, a larger and larger percent of the extra energy we put in is no longer converted into luminous energy but into something else, and that is heat. In case someone that reads this is really interested to learn more about this, I would suggest them start with a paper that covers pretty well the OLED degradation due to Joule heating.
https://www.sciencedirect.com/science/article/abs/pii/S0379677915301193

**Comment by discip** [comment]
@Ralim
Good afternoon Ben, I kind of feel like I’ve upset you with this PR. If so, I am sorry. I did not meant to. 😔

1. Are you waiting for others to comment this?
2. Are the OLED displays of the supported irons (TS100, TS80, TS80P, Pinecil, ...) different?
If not, than what @sandmanRO observed, should apply to these as well.
3. Do you expect me to do anything to get this going?

Thanks in advance 😃
kind regards

**Comment by Ralim** [comment]
Naah no upset, I'm just not always around as much (my response time is basically a 1:1 match to how close I am to watching my email inbox).

(1) Nup
(2) OLED displays are all the same in theory so not worried
(3) Nope 😂

**Comment by Ralim** [comment]
If i dont look at a PR / comment for a while you are welcome to poke me; though generally I'm _coming_ eventually :P Just my response time varies a lot. I've spent most of tonight offline so not as present

**Comment by discip** [comment]
Thank you! 😃

**Pull request merged**
