### PR TITLE
Maintenance: Move to using PD library

### PR DESCRIPTION
**Pull request by Ralim**
So this is mostly a maintenance piece of work.
Moving the usb-pd logic to use the external version of the library.
Have been doing more testing and cleanup of the library and now I believe its ready for use.

Would absolutely love anyone testing this.
Should have no regressions, _may_ have some improvements due to the cleanup.
As far as I can this has _improved_ response time to sub 3 milliseconds in my testing.

Testing is ongoing though :)

Items confirmed working:

- [x] TS100
- [ ] TS80
- [ ] TS80P
- [X] Pinecil
- [ ] MHP30

### CODE REVIEW

**Comment by Firebie** [comment]
Hi,
small fix:
```diff
diff --git i/source/Core/BSP/Pine64/Power.cpp w/source/Core/BSP/Pine64/Power.cpp
index f5602ef1..571cfb17 100644
--- i/source/Core/BSP/Pine64/Power.cpp
+++ w/source/Core/BSP/Pine64/Power.cpp
@@ -19,9 +19,11 @@ void power_check() {
 }
 
 bool getIsPoweredByDCIN() {
+#ifdef POW_PD
   if (USBPowerDelivery::negotiationComplete()) {
     return false; // We are using PD
   }
+#endif
   if (hasQCNegotiated()) {
     return false; // We are using QC
   }

**Comment by discip** [comment]
@Ralim
Good morning,
seems to work as intended, at least on the first run. 😁
Will report back otherwise.

kind regards

iron  |  Firmware Version  |  PCB Version  |  Power Supply
-|-|-|-
**TS80P**|**https://github.com/Ralim/IronOS/pull/1024/commits/ff9fb4da14765bc5776bd8bbe50ba4eeeed1d0fa**  |**2**|**[UGREEN 65W GaN Charger](https://www.ugreen.com/products/65w-gan-usb-c-fast-charger?variant=32127034654782)**

**Comment by Ralim** [comment]
@Firebie  and @discip 

Would love you to give this a poke again, I ended up sinking a fair bit of time testing against a charger I have that didn't work on master or this and its now working but I ended up touching a fair bit of the code.

Will need to do more testing in a day or two when I have more time, but keen to hear if you run into issues.

**Comment by Firebie** [comment]
hi
```Core/Drivers/USBPD.cpp: In static member function 'static uint8_t USBPowerDelivery::getStateNumber()':
Core/Drivers/USBPD.cpp:43:77: error: no matching function for call to 'PolicyEngine::currentStateCode(bool)'
   43 | uint8_t USBPowerDelivery::getStateNumber() { return pe.currentStateCode(true); }
      |                                                                             ^
In file included from Core/Drivers/USBPD.cpp:10:
./Core/Drivers/usb-pd/include/policy_engine.h:89:7: note: candidate: 'int PolicyEngine::currentStateCode()'
   89 |   int currentStateCode() { return (int)state; }
      |       ^~~~~~~~~~~~~~~~
./Core/Drivers/usb-pd/include/policy_engine.h:89:7: note:   candidate expects 0 arguments, 1 provided
Makefile:404: recipe for target 'Objects/Pinecil/./Core/Drivers/USBPD.o' failed
```

**Comment by Firebie** [comment]
It looks like this build doesn't work anymore with my xiaomi qc and started to stuck again (pinecil)

**Comment by Firebie** [comment]
If I disable POW_PD, then QC works again

**Comment by Ralim** [comment]
@Firebie do you have ability to do logic analyser capture of I2C bus of the Pinecil?
I'm suspect that it was "working" before because a bug was causing the PD ic to respond fast enough for all chargers.

What cable are you using with the charger? On a normal A->C cable the CC line should be disconnected, and thus the FUSB wont even be able to talk to anything.

**Comment by Firebie** [comment]
I do not have any logic analyzer of I2C bus :-(
The cable was supplied together with the xiaomi charger (and phone note 9 pro)

**Comment by Firebie** [comment]
Wait, look like it works, it was some issue with git submodule, now usb-pd is at a9ea9e9917eb and QC works.

**Comment by discip** [comment]
Good evening @Ralim,
first o all a big 👍**THANK YOU**👍 for working on this!

Just flashed https://github.com/Ralim/IronOS/pull/1024/commits/16b6543db08e2bf56f9282dfa096235c0511fa51.
The first thing I noticed, was that the start up is somewhat bumpy compared to the previous version!
1. When powering the iron, the following *'flashing sequence'* is executed:
*logo, **main screen**, logo, **main screen***

2. Only if **`PD timeout`** is **>0**, **PD** is used (`PWR 2`).
Else **QC** is used (`PWR 1`).

3. If **QC** is used the iron is fed with ***12.1 V***, with **PD** only ***11.8 V***.

Hope that helps. 😅

iron  |  Firmware Version  |  PCB Version  |  Power Supply
-|-|-|-
**TS80P**|**https://github.com/Ralim/IronOS/pull/1024/commits/16b6543db08e2bf56f9282dfa096235c0511fa51**  |**2**|**[UGREEN 65W GaN Charger](https://www.ugreen.com/products/65w-gan-usb-c-fast-charger?variant=32127034654782)**

**Comment by Firebie** [comment]
Tested a little more on pinecil.
If PD timeout = 0, QC doesn't rise voltage to 19.8
If PD timeout = 1, QC goes to 19.8

**Comment by Ralim** [comment]
Ah some of this is my bad, with the PD timeout I need to do a few extra guards on it, intent is for it to be used to disable PD (0) or used to make PD have a short timeout (rather than the ~10 seconds) it used to use, in case you're using QC and the charger has a short timeout.

That option needs some more work before I merge this in.

@Firebie you dont happen to know what version you had checked out that was _not_ working? (I'm curious).


@discip 

Ah interesting to know its bumpy, can you test testing the timeout for PD to 50 (ish) and see if its still bumpy?
I don't have my TS80P on hand at the moment so very interested in any notes you have.

(2) That is expected, though poorly documented

(3) No idea here tbh, could be accuracy of _something_

**Comment by Firebie** [comment]
`you dont happen to know what version you had checked out that was not working? (I'm curious).`
Yes, it was a frankenstein of new IronOS and old pd-lib

**Comment by discip** [comment]
@Ralim
Good evening Sir,
1. No matter how high I set the *timeout* (tried **`48`** & **`49`**) the *'logo-flashing'* stays!
2. If the timeout is set to **`49`**, something strange happens.
Namely: The entire **`PD timeout menu`** **vanishes**! Only resetting helps.
3. For some reason **`PD`** & **`QC`** are used interchangeably! (At least as per the debug menu.) 😵🤷‍♂️
For the most part of the time **`PD`** is used, but for the duration of the set *timeout* it changes to **`QC`**!

e.g.:

set timeout  |  PWR 2  |  PWR 1
-|-|-
**30**|**~10s**  |**~3s**
**40**|**~9s**  |**~4s**
**10**|**~12s**  |**~1s**

**Comment by Firebie** [comment]
Pinecil, PD timeout  - 1, using QC charger (19.8V).
Starting soldering (350C), after 1 minute I see that screen refresh is slowing down and in a few seconds device is stuck. No reaction on button too.

**Pull request closed without merging**
