### PR TITLE
reworked CJC calibration appearance

### LINKED ISSUE #1448: Calibration method is too confusing even for EE experts
**Is your feature request related to a problem? Please describe.**
SDG who is a youtube and EEVblog  reviewer  posted a video today  on Pinecil V2 that had several issues.   Here is  an  electronics hobby expert with a wide  following,  where  Calibration screen is confusing which leads him to think it is broken either the firmware or the Pinecil.  it could be a misunderstanding or it could be a problem with tip or something else.

[Video here ](https://www.youtube.com/watch?v=-TosWhPsru4)

Please watch the  whole video, but based on several incorrect things he tells people about long versus short tips power,  that calibration software doesn't work, many people in comments are reacting  and saying how they are disappointed with V2. This is  a matter of some misunderstandings in how to use V2 and errors from interpretation of  how the menu works or how calibration works.  or it could really be broken.

**Describe the solution you'd like**
Some of these things below I know you can not do in github but could pass along to Pine64 people.

1. Some of the mistakes could be avoided by  adding some information to the Pine Store webpage.  Not everyone knows about Pinecil Wiki.  I would like to see  a link to Pinecil Wiki  on the Pine Store webpage.  Would also like  Pine Store to tell people to unplug Pinecil when swapping tips of different lengths.   It needs to be noted that many people will never know to go to Pinecil Wiki or Github and just use the pinecil as they get it with only the information they see on the website when they buy it.

2. Pinecil V2  mini user manual is so small it is not readable at all.  on front page should have huge letters with link to Pinecil Wiki, and the Github/IronOS,  and to the PDF version of the User manual.   It comes in such a tiny font that people will just put it aside, but if it had those 3 links in Large readable font on the front, people would have a chance to go to real instructions pages.  FYI, it already includes  webpage link to Github-IronOS  but it is so tiny, you can not see it or any of the manual without a good magnefying glass or taking a macro photo. it could be so much better for end-users than it is now.

3. when performing a calibration,  when the Offset number appears, make it more clear you are done. In SDG's video example  it could be  
`833   offset.  Done.  `  or `833  offset. Complete.`
 that would be more clear and avoid the  huge misunderstanding that he showed to whole world today. 

4.  SDG is not the only person who does not understand how calibration works,  it is unclear to everyday people when is calibration Done or Complete?

### PR DESCRIPTION
**Pull request by discip**
@River-b
Please check if this is sufficient.

resolves #1448

### CODE REVIEW

**Comment by Ralim** [comment]
@River-b  as the poster of #1448 can you test this and see if it improves things in your mind?
I like the look of this I think

**Comment by River-b** [comment]
checking it now

**Comment by River-b** [comment]
1.  After reboot, this is nice:   "calibrating...."  and then "calibration done". Looks clear  to the user what happens. much improved. (not sure  what offset number helps with for troubleshooting, don't think it will be missed)
2. could the  Check Box be on Left side of screen so it's more obvious you have to check it?
3. could the long scroll sentence say that they need to "check the box"?   might not realize.  Sometimes I had to  click (A/+)  a couple times for it to take, probably because I didn't do it fast enough before the scroll message.  but I  already know from documents that I need to check the box so I did not  leave that menu until I saw a check in box.

current sentence says
`Calibrate tip Cold Junction Compensation at the  next boot  (not required if Delta T is <  5 °C)`
consider something with "**Check the Box**" in it.  suggestion below is just to keep characters/words down, either way works, just more wanted "Check the Box"  added.
`Check the Box  to calibrate tip temperature(T) at next reboot (skip this if Delta T < 5 °C)`

4.  I noticed that if I  check the box to calibrate, and did not fully leave the submenu, just  Unplugged and rebooted,  it did not calibrate.    I had to  first check the box, then  hit (-)  to get to the main screen  view, and then I rebooted and saw  Calibrate... message. might want let people know in Documents at some point.

**Comment by discip** [comment]
1. The offset value is still available in the **`Debug Menu`** *(Tip O)*.
2. This would break the UI consistency as every other entry also has the checkbox on the right side.
On the other hand, this would require changes that I am not able to execute.
3. This is documented in [Menu.md](https://github.com/Ralim/IronOS/blob/dev/Documentation/Menu.md) and works the same as the **`reset option`**.
Also, if this is changed, the **`reset option`** would also need to be changed to  preserve consistency.
4. According to https://github.com/Ralim/IronOS/issues/1159#issuecomment-1004028583, this behavior is intentional.

**Comment by River-b** [comment]
nice,  _Tip O_  would show what offset was used in last calibration then?
2.   understood,  just a sugestion from some people who I shared with  - _if possible_ helps make it obvious for new users who didn't read documents. it is not big deal to change it Box to let.  if scroll sentence  has "check the box..." that is clear enough.
4.  yes I remember reading that we have to go back to main screen before new setting saved.

more feedback from some people I shared this with:  they are okay it says Calibrate CJC with checkbox (saves space too)  since CJC is what it does if someone cares to look at Temperature document.
they also prefer  scroll sentence says  "Check the Box"  and "Calibrate Temperature" replaces  "calibrate cold junction compensation"  

These new changes  will help user understanding. Due to youtube more people are doing calibration when the Iron is new because they see all the YT people doing it. YT people don't explain the exact steps and also might or might not know exactly how it is implemented exactly in IronOS.

**Comment by discip** [comment]
1. It's the value that was previously shown, when calibration was done.

About the wording: *"Check the Box"*:

I think the *checkbox* isn't the hurdle here as all the other entries like:
`Cooldown flashing`, `Swap + - keys`, `Anim. loop`, `Invert screen`, `Detailed idle screen` & `Detailed solder screen` use the same scheme without causing anyone to complain about it.

It's more the *confirmation text* that raises questions.

Hence my suggestion to change:

```C#
Please make sure tip & handle are at room temperature at next boot!
```
to
```C#
Please make sure tip & handle are at room temperature at next boot! Please confirm.
```
What do you think?

**Comment by River-b** [comment]
only reason about Check the box  words in
 `Check the Box to calibrate tip temperature(T) at next reboot (skip this if Delta T < 5 °C)`
is people don't know what to expect on reboot to know if calibration happened.  other menu features, it's obvious if you did it wrong. if it is not Auto rotating the screen and you go back and guess again.  people may not know they should see a message on reboot "calibrating ..."   and might think it's done.  a couple words just to avoid some confusion if possible. I do see what you mean about how users can learn from other menu options to do this. Some people have a lot less menu knowledge than we do.  The feedback I got from people is they like "check the box" words  and am sharing it for consideration.

If you mean for this new sentence about the "...Tip & handle are at room..."  to replace other  Checkbox option,  I  prefer the first method with Calibrate CJC checkbox.

If you mean to have 2-step process , then sure,   but I don't know what that would look like or if it is easy for users: 
- first,  they check the box  to Calibrate CJC  (there is a scroll text that explaining this)
- second, they get another confirmation that could be _more firm_ since it's a critical requirement (or else the calibration will be worse than before and they think they have a defective Iron):
`Critical for Tip & Handle to be room Temperature before next boot! Please Confirm.`

I  totally understand there are limitations to what is reasonable for sentence length before it gets more confusing. At some point people may need to look at the detailed Github document for full procedure.  I think of the short sentences as a quick reminder of detailed document that I already read.  Some people _only_ use the short sentence to guide their actions.

**Everything that was in the first rendition was great.  Only suggestion was adding the "check the box calibrate temperature"  scroll sentence, otherwise people like the new way over the old one**. messages we get on reboot in the new version are Clear and good.

**Comment by River-b** [comment]
Actually, I just realize  what you might mean.

Display one sentence "...next boot! Please Confirm"    then the user  hits the  `(A/+) `  button to confirm. 
then message appears  "Calibrate text appears on reboot"

Then they reboot and see the  good messages " calibrating..." "calibration done"
I assume  if they have no Tip installed or Tip got loose,  they get some error message  on boot that calibration could not happen.

**Comment by discip** [comment]
Sorry, I think I did not express my self well enough.
I was referring to the current behavior and the additional confirmation text, that appears as soon as you press the (A/+) button.

Ok, I'll try again.

What causes confusion is not the question ***how to check the box***, since all the other entries with *check boxes* get checked effortlessly, but ***what to do*** when the additional confirmation text scrolls by.
Same scheme as **`Reset`** entry.

I hope you get my point. 😅

> Display one sentence "...next boot! Please Confirm" then the user hits the `(A/+) ` button to confirm.
> then message appears "Calibrate text appears on reboot"

I would like to keep the amount of strings down, to keep it simple.
As you stated yourself:
>I totally understand there are limitations to what is reasonable for sentence length before it gets more confusing.

What about:

Changing the description text

```C#
Calibrate tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)
```
to
```C#
At the next boot the tip Cold Junction Compensation will be calibrated (not required if Delta T is < 5°C)
```

and the confirmation text

```C#
Please make sure tip & handle are at room temperature at next boot!
```
to
```C#
Before rebooting, make sure tip & handle are at room temperature!
```

should make it clear enough.

What do you think?
Can we agree on that?

**Comment by discip** [comment]
Sorry, I think I did not express my self well enough.
I was referring to the current behavior and the additional confirmation text, that appears as soon as you press the (A/+) button.

Ok, I'll try again.

What causes confusion is not the question ***how to check the box***, since all the other entries with *check boxes* get checked effortlessly, but ***what to do*** when the additional confirmation text scrolls by.
Same scheme as **`Reset`** entry.

I hope you get my point. 😅

> Display one sentence "...next boot! Please Confirm" then the user hits the `(A/+) ` button to confirm.
> then message appears "Calibrate text appears on reboot"

I would like to keep the amount of strings down, to keep it simple.
As you stated yourself:
>I totally understand there are limitations to what is reasonable for sentence length before it gets more confusing.

What about:

Changing the description text

```C#
Calibrate tip Cold Junction Compensation at the next boot (not required if Delta T is < 5°C)
```
to
```C#
At the next boot the tip Cold Junction Compensation will be calibrated (not required if Delta T is < 5°C)
```

and the confirmation text

```C#
Please make sure tip & handle are at room temperature at next boot!
```
to
```C#
Before rebooting, make sure tip & handle are at room temperature!
```

should make it clear enough.

What do you think?
Can we agree on that?

I am going to change it as suggested and you could provide the result to the testers.

**Comment by discip** [comment]
@Ralim
I do not want to open a separate issue, but I need to know if I have harmed my **`TS80P`** by running it at **20 V**? (I did that by mistake. I used the **AVHzY CT-3** and unfortunately confused 20V with 12V.)
I did even start heating.
**`Power limit`** has been set to **30W** in **`Advanced menu`**.
It still works, but I'm wondering if I might have broken something (sensitive components)?

Thanks in advance

**Comment by River-b** [comment]
`At the next boot the tip Cold Junction Compensation will be calibrated (not required if Delta T is < 5°C)`

Yes, sure,  or shorten it to 'tip temperature' (some people requested). either way if you think it's important to keep that.

> and the confirmation text
 `Before rebooting, make sure tip & handle are at room temperature!`
yes sure

**Comment by discip** [comment]
> ... or shorten it to 'tip temperature' ...

1. I know it would be more user friendly, but the term *temperature* might mislead users into thinking that the calibration would actually calibrate the system to a specific temperature.

2. Since this is descriptive text, we should use words that describe the *actual method* best.
However, the abbreviation to CJC, which would shorten this text considerably, is too cryptic.

So we have no choice but to stick with the sentence suggested above. 😅 

Hope that makes sense.

**Comment by discip** [comment]
> ... or shorten it to 'tip temperature' ...

1. I know it would be more user friendly, but the term *temperature* might mislead users into thinking that the calibration would actually calibrate the system to a specific temperature.

2. Since this is descriptive text, we should use words that describe the *actual method* best.
However, the abbreviation to CJC, which would shorten this text considerably, is too cryptic.

So we have no choice but to stick with the sentence suggested above. 😅 

Hope that makes sense.

If you are good with that, I hereby ask @Ralim to merge this in.

**Comment by discip** [comment]
> ... or shorten it to 'tip temperature' ...

1. I know it would be more user friendly, but the term *temperature* might mislead users into thinking that the calibration would actually calibrate the system to a specific temperature.

2. Since this is descriptive text, we should use words that describe the *actual method* best.
However, the abbreviation to CJC, which would shorten this text considerably, is too cryptic.

So we have no choice but to stick with the sentence suggested above. 😅 

Hope that makes sense.

If you are good with that, I hereby ask @Ralim to merge this in. 

@Ralim
I don't mind if you squash commits down again. 😄

**Comment by discip** [comment]
@Ralim
I do not want to open a separate issue, but I need to know 
1. if I have harmed my **`TS80P`** by running it at **20 V**? (I did that by mistake. I used the **AVHzY CT-3** and unfortunately confused 20V with 12V.)
I did even start heating.
**`Power limit`** has been set to **30W** in **`Advanced menu`**.
It still works, but I'm wondering if I might have broken something (sensitive components)?

2. how often (approx.) am I allowed to flash my device (**`TS80P`**) before it dies of exhaustion?
I'm afraid I might hit that limit pretty soon if I keep flashing it to test different changes.

Thanks in advance

**Comment by Ralim** [comment]
(1) Honestly not sure, probably pushed voltage regulators a bit; but if it seems to be working well; then you are most likely fine. I dont have schematics for the TS80P to be able to confidently know limits sadly.

(2) _At least_ 10k cycles


----

Will wait for @River-b  to check before merge 😁  Thank you both for looking into this

**Comment by discip** [comment]
1. How would I notice if that was the case?

**Comment by discip** [comment]
Thank you for the instant reply!

1. How would I notice if that was the case?

2. Ok. Than there should be still room for testing. 😁

3. You are welcome. As mentioned before, you deserve to be thanked for making this whole project a reality.

**Comment by Ralim** [comment]
(1) Temperature being off or tip not working
(2) I think if you hit that limit I'd be honestly shocked 😁

**Comment by discip** [comment]
@Ralim
@River-b seems very busy. Since he was basically happy with the changes, I assume this can be merged.

But if you insist on waiting for his confirmation, that's okay too.

As you might have noticed I did update all the languages again.
What do you think? Should I open a separate issue to inform all translators after this PR has been merged?

regards

**Comment by discip** [comment]
@Ralim
@River-b seems very busy. Since he was basically happy with the changes, I assume this can be merged.
https://github.com/Ralim/IronOS/pull/1473#issuecomment-1320802949

But if you insist on waiting for his confirmation, that's okay too.

As you may have noticed, I've updated all the languages ​​again.
What do you think? Should I open a separate issue to inform all translators after this PR has been merged?

regards

**Comment by discip** [comment]
@Ralim
1. @River-b seems very busy. Since he was basically happy with the changes, I assume this can be merged.
https://github.com/Ralim/IronOS/pull/1473#issuecomment-1320802949

   But if you insist on waiting for his confirmation, that's okay too.

2. As you may have noticed, I've updated all the languages ​​again.
What do you think? Should I open a separate issue to inform all translators after this PR has been merged?

regards

**Comment by Ralim** [comment]
Please dont tag all the translators again; that last chain was very email spammy; probably best to instead merge and wait a bit and see; then for ones that need updates we can tag them in a comment on the code.
As soon as you tag someone into a PR/issue they will be emailed for every change, edit, push to the branch etc so its a bit spammy.

I want to get a better translation system setup.. one day.


I'm happy to merge now; but @River-b comment on here if there are changes you would still like.

**Comment by discip** [comment]
Ok!
Will do as you say. 😊

**Comment by River-b** [comment]
if you already did it that is fine. otherwise I can install it now and do one calibration with it.

**Comment by River-b** [comment]
1.  On testing this, I noticed that I'm able to see  both lines of sentences without ever checking the box.
as a new user, I might  hit "A/+"    button or hit the (B/-) button. 
 I was able to see 
`At the next boot the tip Cold Junction Compensation will be calibrated...`   and sentence  "before rebooting"
Then, I would reboot and could think this is done since I don't know I'm supposed to see a nice confirmation after I reboot.

Up to you all  how you want it finally, but  my opinion is  to consider saying "check the box": 
`Check the Box to calibrate tip temperature(T) at next reboot (skip this if Delta T < 5 °C)`
    OR  if you don't like that, then maybe
`Check Box to Calibrate Cold Junction at next reboot (skip this if Delta T < 5 °C)`
    or something similar that has check box.  

2. The detailed sentence warning people, "Before rebooting, make sure tip & handle are at room temperature!"  is good or could be more strongly worded warning.  
`If Tip & handle are not at room °C/°F before rebooting, Calibration may be worse!`

3.  The stuff that happens after reboot if you check the box  is  good - with `calibrating...`, and  `Calibration Done!`
please leave that :)

**Pull request merged**
