### PR TITLE
Only vbus mod check on pinecil

### PR DESCRIPTION
**Pull request by Ralim**
https://github.com/Ralim/IronOS/pull/1215#issuecomment-1036755827

FYI: @discip

### CODE REVIEW

**Comment by discip** [comment]
# Thank you! That worked! 😃👍

**Comment by discip** [comment]
It shows **`PWR PD W. VBus`**!
However if connected to PPS it restarts as well! 😩

**Comment by Ralim** [comment]
yeah not surprised the probing interfears with PPS, to probe vbus we have to disconnect from the CC lines entirely for a bit.

Modding VBus means you can use a DC source that is 21-24V

**Comment by discip** [comment]
OK! So not VBus mod for me! 😃

**Comment by discip** [comment]
So you do plan to do this? No pushing, just asking.

**Comment by Ralim** [comment]
Not for 2.17 release given I need to wrap that up _soon_.

**Pull request merged**
