### PR TITLE
Refactor gui files

### PR DESCRIPTION
**Pull request by Ralim**
This is purely a code cleanup change; splitting up GUI thread to make edits and reviews easier.

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
I know it is not the right place.
But please help me at finding out which part I need to swap, to make the **`TS80P`** show the right temperature again.

Last time you told me a sign for damage (after having fed 20V instead of 12V into my device) would be a temperature drift.

I left the **`TS80P`** sit on the desk to let it acclimate before calibration. But even after some time, the difference displayed in the **`debug menu`** was ~6°C [Tip C **20** and Han C **26.0**].

**Comment by Ralim** [comment]
Best would be to open a discussion for this; if you can. (I suspect it may be a long chat)
But TL;DR would be to figure out which is wrong (raw tip reading OR handle temp).
If its the handle temp its concerning as that circuit should  just be a resistor and an NTC resistor
More likely its the raw tip and the biggest suspect is the op-amp that measures the tip temperature

**Comment by discip** [comment]
One thing I've wanted to know for some time is:

In what unit is this difference measured (10):
https://github.com/Ralim/IronOS/blob/30f1840ea5c3a81a055e72b599b65a62dfb279d4/source/Core/Threads/GUIThread.cpp#L101
That should be in **`°C`**, right?

**Comment by Ralim** [comment]
Ah we probably should abs() that; getHandleTemp is in X10C (so the /10 to make it into C)

**Comment by discip** [comment]
Created a PR already. 😁

**Pull request merged**
