### PR TITLE
add new language (Belarussian)

### PR DESCRIPTION
**Pull request by lidacity**
add new language (Belarussian)

* **Please check if the PR fulfills these requirements**
- [] The changes have been tested locally
- [] There are no breaking changes

* **What kind of change does this PR introduce?**

* **What is the current behavior?**

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by Ralim** [comment]
Hello,
I think it would be better to use the ISO language code; which I believe would be `BE`?
Otherwise looks good to me but I cant check the translation.
Have you checked things look ok on a physical device?

**Comment by lidacity** [comment]
yes, please change to BEBelarussian language is correct on a physical device 23.11.2021, 10:48, "Ben V. Brown" ***@***.***>:
Hello,
I think it would be better to use the ISO language code; which I believe would be BE?
Otherwise looks good to me but I cant check the translation.
Have you checked things look ok on a physical device?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

--  З павагай, Дзмітры +375(29)7092638 Беларусамоўная Беларусь!Вейшнорыя - лепшая краіна!

**Comment by alvinhochun** [comment]
Can you please rewrite the subject line of this issue and the commit message in English?

**Comment by lidacity** [comment]
corrected

**Pull request merged**
