### PR TITLE
Enhanced to have PNG download and scaling

### PR DESCRIPTION
**Pull request by Ralim**
Original updates started by @ Pikapoo on the Pinecil community chat
Further improvements and png work by Robert Lipe <robertlipe@gmail.com>

I wrote _none_ of this, I deserve no credit :)

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Just had time to inspect the **BitmapEditor**.

And unfortunately found it to be some kind of unfinished.

A few questions about that here:
1. How to export the drawn picture as **`.png`**?
   - The **`Make PNG`** button in the  bottom left corner does not do that!
   - It exports an empty **`.png`** without the corresponding file extension and always the sized **`96 x 16`** no matter what is setup in the upper left.
2. What exactly the empty fields are for?
   2.1. How to export a **`.hex`** file?
     - I assumed that the empty field below the canvas is used to print the result of the drawing in **`.hex`** format.
     But there is not even a button! 🤷‍♂️
     - Would be very nice if not only
       1. the above described would work, but furthermore:
       2. If this field would accept **`.hex`** code and would depict it on the canvas.
   
   2.2. Why does the second empty field below the canvas, even if you set the correct canvas size, not always generate the correct **`.hex`** code.
3. What is the small area with the dotted border above the **`Make PNG`** button for?

**Comment by alvinhochun** [comment]
I know I'm late but I would not have merged this because it mixes code changes with formatting changes, which makes the diff unreviewable and breaks git blame history...

**Comment by discip** [comment]
@alvinhochun
Greetings, thank you for joining in.
Could you help with this?

**Comment by alvinhochun** [comment]
No, one cannot fix git history of changes that has already been merged, without severely breaking workflows anyway.

**Comment by discip** [comment]
> Could you please help with this?

I was thinking about the **BitmapEditor**.  😅

**Comment by Ralim** [comment]
So first box is the C representation as firmware uses.
Second is the hex escaped version for python.
Neither is for .hex files

This was mostly building features to add a .dfu file importer, png export.

But as all changes went out of git, via multiple people formatting was changed up and this was to bring it back in, in the hacked up state so we stop passing further hacked up ones around discord file attachments.
Its definitely not pretty or "great" but extra features are better here than having lots of versions hanging around the chat group.

**Comment by discip** [comment]
So the thing itself works?
But as mentioned I am not able to use it in any way. 🤷‍♂️
Is it just me?

**Comment by GPSBabelDeveloper** [comment]
The diff isn't "unreviewable". Click ignore whitespace in the diff. 

If you're not getting arrays if numbers in the two boxes, especially the first, png generation is not going to work.

It was developed/tested on MacOS, Android, and ChromeOS and in Chrome and Safari. Canvas support (a new dependency) has been part of browsers for years, so I wouldn't expect problems.

Focus on why those fields aren't getting populated. The PNG code is essentially picking numbers out of that first one and parsing the c style array. If that's blank, png is doomed.

Hope this helps narrow down your search.

Screenshot_20220216-180852

**Pull request merged**
