### PR TITLE
change increment and values of brightness settings

### PR DESCRIPTION
**Pull request by discip**
just trying

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Good evening Sir,
hope you don't mind helping me out with that one.
I achieved what I was trying, but I do not know, if this is the best way to do it!
I think there has to be a more elaborate way. 😁

**Comment by Ralim** [comment]
I'm glad Github's CI is free for open source 🤣 

I dont you doing it this way :) 
You could alternatively enable the actions on your fork and iterate there _then_ open the pr; but I dont honestly mind :)

Just make sure to ping me when you are happy with it if i don't notice :)

**Comment by discip** [comment]
@Ralim
I think I did not express myself well.
I was referring to the way I changed the code. 😅

**Comment by Ralim** [comment]
Eh I didnt comment on the code as it seems fine tbh 🙃

**Comment by discip** [comment]
> (add 50% of the step size then divide works as an alternative)

Could you please give me an example? 🥺

**Comment by Ralim** [comment]
So what I meant was:
* Given a step size of 28
* `value = (x+14)/28`

So the `+14` will make it act more like a `round()` call, which may work for what you want

**Comment by Ralim** [comment]
You might want to try:

```
auto value = getSettingValue(SettingsOptions::OLEDBrightness);
value = ((value+14)/28)+ value%28?1:0;
OLED::printNumber(value, 3, FontStyle::LARGE);
```

**Comment by discip** [comment]
I think I might have found a neat solution to that, without having to handle floating point at all. 😁

**Comment by discip** [comment]
It's good to go, imho.

**Pull request merged**
