### PR TITLE
Generate .dfu files

### LINKED ISSUE #1050: Please include a DFU suffix in firmware files for USB DFU
This is recommended (see also the standard https://www.usb.org/sites/default/files/DFU_1.1.pdf) so that the file includes a checksum, plus USB VID/PID so that users don't burn firmware files onto the wrong device (there are for instance laptop built-in bluetooth adapters with DFU support, and nobody wants to brick those).

For instance the tool dfu-suffix from the dfu-util package can be used to easily add such a suffix.

### PR DESCRIPTION
**Pull request by Ralim**
Adding in dfu files that have the dfu suffix

Will drop bin files once these are known to work.

Fixes #1050

### CODE REVIEW

**Comment by Ralim** [comment]
@tormodvolden 
Can you give this a look over

**Comment by tormodvolden** [comment]
Debian/Ubuntu ships dfuse-pack but doesn't install it in the path (yet?), you can pick it from /usr/share/doc/dfu-util/examples/dfuse-pack.py.gz (and uncompress).

**Comment by tormodvolden** [comment]
On the other hand their current version is so old you're better off picking it from upstream like you did :) Did you pretty-format the script?

**Comment by Ralim** [comment]
Haha, honestly didnt dig much except to find it wasnt in path; shrugged and pulled it in. I did format it as habit though (by virtue of opening it once in vscode and hitting save as habit).
Also if its not in ubuntu main package feels a bit weird to have to extract it from an odd path, as thats going to confuse any non-ubuntu uses out there (like me) 😂

**Comment by tormodvolden** [comment]
I'll pick up the reformatting upstream, with your authorship, if that's fine with you.

I have a dfu-util 0.11 including dfuse-pack.py in my PPA, using the package source "`deb http://ppa.launchpad.net/tormodvolden/ppa/ubuntu trusty main`" (also works on focal) if that could be an alternative.

**Comment by Ralim** [comment]
Oh the reformatting is done by tooling so I don't really need credit tbqh.

Do you expect the PPA to be around for the long term 😂 (Well at least until ubuntu puts it as part of the main package?)

If so, happy to swap to it

**Comment by tormodvolden** [comment]
Yes, the PPA has been around for ages and touch wood it will.

**Comment by Ralim** [comment]
Eugh the PPA requires a chunk more work to load in as need to either pull in keys or install the ppa helper I believe (which increase image size and runtime of CI) 😢

**Comment by Ralim** [comment]
@tormodvolden 
If there is a simple way to use the PPA without pulling in more dependencies I will change to it :)

**Comment by tormodvolden** [comment]
Instead of using the ppa helper, you can import the PPA key with this, probably without new dependencies:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4B1E287796DD5C9A`

**Pull request merged**
