### PR TITLE
PID Rework

### PR DESCRIPTION
**Pull request by Ralim**
Please try and fill out this template where possible, not all fields are required and can be removed.

* **Please check if the PR fulfills these requirements**
- [x] The changes have been tested locally
- [x] There are no breaking changes

* **What kind of change does this PR introduce?**
Lots of PID rework, basically taking the ideas from #1038 and also giving a lot of stuff a once over

* Cleaned up timings to be 10/5Hz update rates
* Cleaned up a second pass on making sure adc is only run by pid loop

* **What is the current behavior?**

* **Other information**:

Probably need to re-check all devices are correctly reaching 100% max power draw that they can reach.
Seems to be working here on my tester units but need to do more testing before merge

- [ ] Suspect may be adc timing quirks with QC3 code, will need to check this in more depth
- [ ] need to run this on on bench supply to check stability at all voltages
- [ ] Still seeing a little overshoot at higher voltages at first but stable after that, suspect thats to do with the derating we have to handle thermal lag that may no longer be required (more testing to do)

@firebie and @discip  you may want to give this a try since I know your following along the issue and see what you make of it.

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
Good afternoon Sir,
as you might have expected, I have already run some basic tests.

1. Regarding the stability it is **waaaaay better**, but as you mentioned above, it overshoots by ~40°C before settling almost exactly at the set temperature (320°C).
One more thing in ***the version you put up earlier*** is, that the temperature **_increase_** briefly **_halts_** at about 280°C only to overshoot as mentioned above.
2. Temperature calibration behaves very strange:
Currently it loops showing the dots until it is taken from the power supply or until the tip gets removed.
3. The changes above https://github.com/Ralim/IronOS/commit/a207f03c024164ea0a92fee822ff5c23a5819b0e seem to have broken something in the way the reaching of ends of *value ranges* is handled.
Because the following entries are looped through, when the ***`A-button`*** is held down, instead of pausing at the end of a *value range*.

Power settings  |  Soldering settings  |  Sleep mode |  User interface | Advanced settings
-|-|-|-|-
_*QC voltage_ | Heat on power up | Sleep timeout | _*Temperature unit_ | _*Detailed idle screen_
PD timeout | Temp change short | Shutdown timeout | Display orientation | _*Detailed solder screen_
|| Temp change long | Motion sensitivity | _*Cooldown blink_ | Power pulse
|| Allow locking buttons  |  | _*Scrolling speed_ | Power pulse delay
||  |  | _*Reverse +- keys_ | Power pulse duration
||  |  | Anim. speed | 
||  |  | _*Anim. loop_ | 
||  |  | _*Invert screen_ | 

Entries marked with a **`*`** consist of only two states / values.

<details>
  <summary>
    <b>setup</b>
  </summary>

iron  |  Firmware Version  |  PCB Version  |  Power Supply
-|-|-|-
**TS80P**|**https://github.com/Ralim/IronOS/commit/446faa4f74f51139dd6167b521d1ed0069eb7f25**  |**2**|**[UGREEN 65W GaN Charger](https://www.ugreen.com/products/65w-gan-usb-c-fast-charger?variant=32127034654782)**

</details>

**Comment by Firebie** [comment]
Pinecil, B2 tip, QC charger 19V 33W.
Overshoot is around 10°C on initial heat up, then very stable readings around set temperature.

**Comment by discip** [comment]
@Ralim
Good evening Ben.
Prior to reporting:
I have executed a reset after upgrading the firmware.

Have tested the last build and I have to say, that

1. the *temp ramp-up* improved in regard of overshoot, but behaves somewhat *'interesting'* shortly before reaching ***set temp*** (320°C).
To be precise this is a capture **(23 s)** of the *temp ramp-up sequence*.

<details>
<summary> temp ramp-up chart </summary>

°C	| V (if no value 12.1)| W
-|-|-
50	|          |  0.0
49	| 	   |  2.8
106	| 	   |  5.3
150	| 	   |  7.6
199	| 	   |  9.6
249	| 	   | 11.5
242	| 	   | 13.2
251	| 	   | 14.7
258	| 	   | 16.1
264	| 	   | 17.3
268	| 	   | 18.4
273	| 	   | 19.4
275	| 	   | 20.3
279	| 	   | 21.2
284	| 	   | 22.0
287	| 	   | 22.7
292	| 	   | 23.3
297	| 	   | 23.9
301	| 	   | 24.4
305	| 	   | 24.9
309	| 	   | 25.3
313	| 	   | 25.6
308	| 	   | 26.0
312	| 	   | 25.7
288	| 	   | 26.0
289	| 	   | 25.9
277	| 	   | 26.2
279	| 	   | 25.3
276	| 	   | 25.7
281	| 	   | 24.5
275	| 12.2 | 25.1
295	| 	   | 22.7
294	| 	   | 22.6
267	| 	   | 23.2
298	| 	   | 21.9
250	| 	   | 22.7
296	| 	   | 20.5
293	| 	   | 20.7
267	| 	   | 21.5
293	| 	   | 21.0
255	| 	   | 21.8
285	| 	   | 20.9
286	| 	   | 21.8
299	| 	   | 19.7
298	| 	   | 19.9
275	| 	   | 20.8
297	| 	   | 20.5
264	| 	   | 21.3
291	| 	   | 20.3
293	| 	   | 21.2
308	| 	   | 19.2
308	| 	   | 17.9
283	| 	   | 19.1
315	| 	   | 17.3
279	| 	   | 16.8
279	| 	   | 18.1
317	| 	   | 16.4
284	| 	   | 15.3
283	| 	   | 16.7
318	| 	   | 15.1
285	| 	   | 14.0
282	| 	   | 15.5
320	| 	   | 14.0
286	| 	   | 12.7
284	| 	   | 14.3
323	| 	   | 12.9
291	| 	   | 11.6
287	| 	   | 13.2
312	| 12.2 | 12.7
279	| 	   | 14.3
316	| 	   | 12.9
322	| 	   | 11.6
300	| 	   | 12.5
302	| 	   | 14.1
292	| 	   | 12.7
293	| 	   | 12.5
298	| 	   | 14.2
331	| 	   | 12.8
310	| 	   | 11.6
308	| 	   | 11.6
307	| 	   | 13.4
308	| 	   | 12.1
308	| 	   | 10.9
309	| 	   | 10.8
308	| 	   | 12.5
300	| 	   | 11.3
301	| 	   | 10.2
301	| 	   | 10.9
303	| 	   | 12.6
307	| 	   | 11.4
308	| 	   | 10.3
311	| 	   |  9.8
307	| 	   | 11.1
287	| 	   | 12.6
304	| 	   | 11.5
308	| 	   | 11.5
314	| 	   | 12.4
313	| 	   | 13.6
309	| 	   | 13.2
313	| 	   | 13.3
317	| 	   | 13.7
317	| 	   | 14.5
315	| 	   | 14.4
316	| 	   | 14.9
317	| 	   | 15.1
319	| 	   | 15.3
317	| 	   | 15.5
319	| 	   | 15.6
319	| 	   | 15.5
319	| 	   | 15.4
319	| 	   | 15.3
319	| 	   | 15.2
320	| 	   | 14.9
321	| 	   | 14.5
322	| 	   | 14.0
322	| 	   | 13.5
321	| 	   | 13.1
319	| 	   | 12.8
318	| 	   | 12.5
319	| 	   | 12.3
320	| 	   | 12.0
320	| 	   | 11.8
320	| 	   | 11.6
320	| 	   | 11.4
319	| 	   | 11.2
319	| 	   | 11.0
319	| 	   | 10.8
319	| 	   | 10.6
319	| 	   | 10.4
319	| 	   | 10.3
319	| 	   | 10.2
319	| 	   | 10.0
320	| 	   |  9.9
321	| 	   |  9.7
320	| 	   |  9.5
320	| 	   |  9.3
320	| 	   |  9.2
319	| 	   |  9.1
319	| 	   |  9.0
319	| 	   |  8.9
319	| 	   |  8.8
319	| 	   |  8.7
319	| 	   |  8.6
320	| 	   |  8.5
320	| 	   |  8.4
320	| 	   |  8.3
319	| 	   |  8.2
319	| 	   |  8.1
319	| 	   |  8.0
319	| 	   |  7.9
319	| 	   |  7.8
319	| 	   |  7.7
319	| 	   |  7.6
319	| 	   |  7.5
320	| 12.2 |  7.4
320	| 	   |  7.3
320	| 	   |  7.2
320	| 	   |  7.1
319	| 	   |  7.0
319	| 	   |  6.9
319	| 	   |  6.8
320	| 	   |  6.7
320	| 	   |  6.6
319	| 	   |  6.6
319	| 	   |  6.5
319	| 	   |  6.4
319	| 	   |  6.3
</details>

2. temperature calibration is still buggy (still *dot looping*).

iron  |  Firmware Version  |  PCB Version  |  Power Supply
-|-|-|-
**TS80P**|**https://github.com/Ralim/IronOS/commit/3d992512f44a80212b619b9b4450362351a934b4**  |**2**|**[UGREEN 65W GaN Charger](https://www.ugreen.com/products/65w-gan-usb-c-fast-charger?variant=32127034654782)**

**Comment by sandmanRO** [comment]
Hello Gentlemen/Hello discip,
Very interesting the temperature chart you posted. There is definitely something odd going on. I see those temperature reading drops from +290C to +250C or so within one reading cycle. They can not be in real. If they would be higher (like when we read too early after the heating window) that would have had an explanation but not such temperature drops in excess of 40C. However, this might explain the severe overshoots, as each of these "drops" lead to un unnecessary extra-charge of the pid integrator (a low temperature would be seen as a large setpoint delta that in turn would update the integrator with a larger than necessary value). And yet, if there would be a bug in the reading routine we would expect to see the same temperature reading drops after reaching the setpoint, right? But we don't see that so most likely something else is going on. The only significant difference would be that after reaching the setpoint the power demand drops and that puts less stress on the power supply / power circuitry (tip included). I wonder if you have a similar chart with side-by-side temperature-voltage-power readings. Mind if I'm only speculating as I do not have the hardware you are using, but my suspicions are pointed towards the power supply setup. All I can say for sure, that pid integator was tested on four different TS100 with all 10 designs miniware tips (that go form needle like to the "massive" horseshoe like tips) and I rarely seen overshoots in excess of 1-2 Celsius in the 4 (injected) x 16 averaged temperature value...definitely nothing even near close to the 10-40 degrees overshoots you are experiencing.

**Comment by discip** [comment]
@sandmanRO
First of all thank you for looking into this.

2. I don't know, If I got you right about the chart, but I think the parameters you are looking for are already there, but in a rather cryptic depiction.
I left the middle row empty because there are only 3 occurrences of the voltage being not **12.1 V** but **12.2 V**.
I thought it would be obvious the way I put it.
In the caption of the middle row it states:
> V (if no value 12.1)

Since I am only testing (regular user, no programming), you have to approach @Ralim to discuss the hows and whys of the coding.

kind regards

**Comment by sandmanRO** [comment]
...you are right, discip, my bad...it should have been obvious to anybody. I should go to bed I suppose (here is 2:38AM).

**Comment by Firebie** [comment]
For the calibration issue:
```diff --git i/source/Core/Src/gui.cpp w/source/Core/Src/gui.cpp
index 1d5c2821..c4ffa8c3 100644
--- i/source/Core/Src/gui.cpp
+++ w/source/Core/Src/gui.cpp
@@ -641,7 +641,7 @@ static void setTipOffset() {
       OLED::refresh();
       osDelay(100);
     }
-    setoffset = TipThermoModel::convertTipRawADCTouV(offset / 16);
+    setoffset = TipThermoModel::convertTipRawADCTouV(offset / 16, true);
   }
   setSettingValue(SettingsOptions::CalibrationOffset, setoffset);
   OLED::clearScreen();
```

**Comment by discip** [comment]
@Firebie
Good morning Sir,
for some reason I am not able to find the code snippet you posted. 🤷‍♂️
So would you please tell me, where I have to change these lines, to test if  this works for me? 🥺

thanks in advance

**Comment by Ralim** [comment]
Ah looks like my late night ticket writing wasn't quite up to scratch.
I'm aware of the overshoot and have some theories (just ran out of time to test them), will be poking them a little more tonight as I get time.

Thanks @Firebie , will need to figure out why that broke.


@discip 

In regards to your power table, can you confirm you are measuring those values _external_ to the iron?
Very close to the full 30W should be used by the iron.
Those menu changes will be from the settings rework, ill give them a poke too


Otherwise still trying to figure out why we are getting the little overshoot at the end.

**Comment by Firebie** [comment]
Hi  @discip
It is in pid branch, you need to find piece 'setoffset = TipThermoModel::convertTipRawADCTouV(offset / 16);' in 'gui.cpp'

**Comment by Ralim** [comment]
Okay PID overshoot should be better now.. Well it is for me 😓 
Going to look at the menu now

**Comment by sandmanRO** [comment]
If I may suggest an additional change that would improve the after setpoint behavior...once we exceed the setpoint, the delta temperature becomes negative. However, the micro volts - temperature lookup table does not handle negative values so it would return zero instead of a negative value. This would delay the reaction of the PID after setpoint as it would rely only on power store decay rather than both decay and active update. In my implementation I added to the Hakko lookup table something like this:
static const int16_t uVtoCTable[] = {
		-1244,  -50, 
		-1010,  -40,
		 -770,  -30,
		 -522,  -20,
		 -266,  -10,
		    0,    0, 
		  266,   10,
		  522,   20,
...
}

**Comment by discip** [comment]
@Ralim
Good morning Sir.

1. No these values are not measured externally.
You might laugh, but this was a quite tedious and a rather unconventional way of gathering those values.
I shoot a video, slowed it down and wrote down the values the **`detailed soldering screen`** was displaying. 🤣
2. But as you can see in the chart, it never got even close to **30 W**. 🤷‍♂️

**Comment by Ralim** [comment]
Aha, funny since thats one way I've also done to validate this stuff.
Those numbers are generally a little of an under reading as they are very "estimated" level accuracy at the moment.
Should be a little closer to reality now but they are +- 1-2W as they (a) dont account for consumption of anything but the iron tip and (b) there is always the bit of dead time from when we measure the tip temp and (c) your tip resistance is most likely not exactly what we have in the code.

The errors from (c) cancel out in terms of everything but the UI so are just cosmentic; (b) is part of life and (a) is just cosmetic entirely (arugable, could also be correct as you only want to to know _tip_ power).

But aside from that, could you give it another pass of testing please :)

**Comment by sandmanRO** [comment]
The lack of negative delta handling would definitely contribute to the overshooting you are experiencing as the pid is simply not reacting fast enough once the temperature exceeds the setpoint.

**Comment by Ralim** [comment]
> If I may suggest an additional change that would improve the after setpoint behavior...once we exceed the setpoint, the delta temperature becomes negative. However, the micro volts - temperature lookup table does not handle negative values so it would return zero instead of a negative value. This would delay the reaction of the PID after setpoint as it would rely only on power store decay rather than both decay and active update. In my implementation I added to the Hakko lookup table something like this:
> static const int16_t uVtoCTable[] = {
> -1244, -50,
> -1010, -40,
> -770, -30,
> -522, -20,
> -266, -10,
> 0, 0,
> 266, 10,
> 522, 20,
> ...
> }

Hia,

The uV to C table would only be going negative when the tip is cooler than the cold junction temperature.

At the moment the delta will go negative, which will then be converted into a negative power level without issue (constant * negative number is negative). So I'm not sure that changing this table would do anything in terms of the overshoot.

_However_, this missing segment of the table _is_ the cause of the effect where you start the iron at like 25C, then see it flat line / dip a bit then pick up and start heating. So adding it is a good idea _anyway_.

**Comment by Ralim** [comment]
Ah @sandmanRO  you commented while I was typing.

The overshoot looks to be mostly windup rather than a mis-calculation. I fixed the calculation for the "max" power that we use to limit the sum to and that fixed the issue. Though its probably not the optimal solution

**Comment by Firebie** [comment]
In a worst scenario iron can be used as thermometer :-)

**Comment by sandmanRO** [comment]
Hello Ralim, you are right. I keep forgetting that in your implementation the setpoint delta is computed directly in C, that is, after converting the tip temperature to C and not afterwards. Please disregard.

**Comment by Ralim** [comment]
Absolutely no issue at all 🤗 Absolutely appreciate you investing your brain power into this :)
Originally I wrote the firmware to run in units of uV but it started to get a little messy with keeping that updated to account for the cold junction changes if i recall correctly... Or maybe I just decided working in C was simpler for others to understand 😓 


I'm not sure about your assertion on the gain of _2_ since I dont require it here, and also the idea that the tip is at a 50% duty cycle isnt _quite_ true if you look at a plot of the current pulled from the tip. Though also its been _forever_ since I looked at it but i have a distinct memory of it basically being on / off only due to the gain of the switching transistor

**Comment by sandmanRO** [comment]
If gain=1 is used most likely the setpoint would be reached a bit slower.

**Comment by sandmanRO** [comment]
The relation is not linear...with gain=1 vs gain=2 we would probably reach setpoint in about 20% more time

**Comment by sandmanRO** [comment]
As for the limit, that is necessary for sure. If left unchecked the integrator would go up or down limitless and that is the classinc integrator problem.  When we derivate we basically lose a constant (any constant derivated is zero). When we integrate we are missing that lost constant. As the integration is additive process, since on any iteration we do not add the right constant the result goes up or down. It is like when an operational amplifier,  integration configuration (capacitor as negative feedback) would go in saturation (+VDD or -VDD). So that limit mimics this behavior. The decay is like when we aid the process by adding a resistor in parallel to the capacitor.

**Comment by Ralim** [comment]
Yeah its definitely not linear, but given that we are ultimately constraining the PWM based on the maximum achievable power, so long as that is fairly accurate there should be no requirement for the gain, as it would mostly be inclined to cause some overshoot?


My logic is that we are doing the following:
- Calculate temperature delta
- Convert that delta into an idea amount of energy to be added
- Mix that with a decaying portion of the historical power
- This, give a final amount of power that should be required to close the temperature gap (plus a "maintaining" power from the historical data
- This is then converted to PWM by computing this as a proportion of the maximum possible power, with saturation at the maximum PWM level

My feeling is that adding in a gain term would cause the "PID" to run against the saturation point for longer as the temperature delta closes. When tested with the gain of 1 or 2 it seemed the same during heat up, but a little more prone to being unstable when in temperature regulation when running?

But please, please tell me I'm wrong 😂 Since its easy to change and I'm not super commited to either.

In terms of the limit, indeed I agree, it is feels like the classic accumulating issue, just was surprised that being off only by a small amount in that calculation caused as much overshoot as it did :)

**Comment by sandmanRO** [comment]
The gain value is definitely not critical (as you noticed, the beauty of this integrator is that nothing is really critical) so it would do the job with pretty much "everything" we throw at it. If you see better results with gain 1 then go for it. Maybe on "heavy" tips the difference would be more noticeable, but after all it is just a soldering iron. I don't think the regular user would be bothered the iron gets hot one-two seconds faster or slower.

**Comment by sandmanRO** [comment]
I will do a test on TS100 with the "heaviest" tip I have (the horseshoe like) with gain=1 vs gain=2 and follow up with the findings so we will know for sure what would be the influence on the "worst case scenario".

**Comment by Ralim** [comment]
I would highly appreciate if you could have a look see. 
Its most likely an entirely academic discussion but it would be very good to know either way

**Comment by discip** [comment]
@Ralim
1. Temp calibration is back to normal! 👍
2. Menu is fixed and works as intended! 👍
2.1 Since you are on it I think it would contribute to consistency, if the entries below would behave just like all the others:
Meaning instead of a **`0`** being the ***`Off`** 'value'*, **`Off`** should be displayed as in the example (I only listed one, but there are actually more!).
2.2 I think it makes more sense to move the below mentioned items. 😁

|| 1. Power settings  | 2. Soldering settings  | 3. Sleep mode |  4. User interface | 5. Advanced settings
-|-|-|-|-|-
example | | | Sleep timeout
2.1 to be reworked | *PD timeout* | | *Motion sensitivity*
|| | | | |
2.2 to be moved | | | | here <===== | <= Detailed idle screen
2.2 to be moved | | | | here <===== | <= Detailed solder screen

Hope you don't mind the off topic content. 😊

@sandmanRO 
> regular user would be bothered the iron gets hot one-two seconds faster or slower.

Not entirely true, because faster is always better! 😁 Except for the case when **ACCURACY** is compromised, than speed moves to 2nd place.

**Comment by Ralim** [comment]
@discip 

You have no idea how much i love the tables you draw out for this.
Its very off topic for this, but if its easy Ill do it now and throw it in for you :P


I would argue: Consistency>Accuracy>Speed. Since if an iron is inaccurate but consistent people will naturally just adjust. But if its not consistent then everyone hates it.

**Comment by Ralim** [comment]
@discip 
So the PD timeout was easy, but for others there isnt enough on-screen room to make all of the off strings fit..
I think for the off strings it would be best to split that to a discussion / issue for ease of tracking if we can :)
Otherwise I'm inclined to merge this in

**Comment by discip** [comment]
@Ralim
> You have no idea how much i love the tables you draw out for this.

I appreciate this reaction very much. 👍
My intent is to make issues as obvious as possible. And if it is only by drawing tables.

> I would argue: Consistency>Accuracy>Speed. Since if an iron is inaccurate but consistent people will naturally just adjust. But if its not consistent then everyone hates it.

Yes you are **definitively right** about that! Reliable accuracy is the term I was having in mind.

**Comment by sandmanRO** [comment]
These are the test results:
Setup: TS100, horseshoe tip (I believe they call it TS-C4), Power Supply 24V / 80W, Room Temperature 25C, Setpoint 225C (start delta 200C).
gain=1....the average time (over 5 runs) to reach setpoint ~16s
gain=2....the average time (over 5 runs) to reach setpoint ~10s
I did not have the nerves of discip and make a video then get the time out of frames (otherwise a very great idea) so I used a chronometer. As a results, the time measurements are probably accurate within +/-1s.

**Comment by discip** [comment]
@ Ralim
> I think for the off strings it would be best to split that to a discussion / issue for ease of tracking if we can :)

**`0`** is also fine, but it should be consistent throughout the menu style.
May be pic would do the job as well?

**Comment by discip** [comment]
@sandmanRO
Could you upload a video showing the heat up process?

**Comment by sandmanRO** [comment]
Ok, just give me a minute to grab a camera and improvise a video fixture.

**Comment by Ralim** [comment]
Hmm interesting that the time difference is that big.
Wonder if this should be some form of setting to account for tip size.

In my testing both are similar enough I'm happy to go with a gain of `2` if it makes that much of a difference for a large tip :)

**Comment by sandmanRO** [comment]
Now the big question...how do I upload a video here?...I tried as zip file but github complained that "is not included in the list"

**Comment by sandmanRO** [comment]
I see...they accept MOV, MP4 not GP...let me try to convert it.

**Comment by sandmanRO** [comment]
This is ridiculous...as I converted to MP4 now they complain it is too big and it should be under 10MB while the file is 14MB. Let's see what I can do.

**Comment by discip** [comment]
@Ralim
Just tested the ***`gain=2`** build*.
I think **`gain=1`** is better in regard of **overshoot** and **speed** (21 s).
Will have to reflash the ***`gain=2`** build* and test again.

**Comment by discip** [comment]
@sandmanRO
Maybe convert to gif.

**Comment by Ralim** [comment]
Ah heck, yeah it's a bit messy. Compress it as much as you can or throw it on a different host if you need to.

If that's too messy you can also throw it to my email inbox (up to 25MB) and I can rehost it here

I'm easy to find at ralim@ ralimtek.com

**Comment by sandmanRO** [comment]
Ok...I will send to your email as mpg as the smallest format I have available (about 5MB...of course this format is not accepted by github)

**Comment by Ralim** [comment]
@discip definitely keen to hear your thoughts on the two builds.
This could also be something we tweak for each model (mildly suspect MHP30 will need further tweaking, since it's a bit odd compared to the rest).

**Comment by discip** [comment]
@Ralim
My guess seems to be right since **`gain=1`** took only **18 s**.
So please revert to **`gain=1`** again. 😊

One more thing, which I just now stumbled over, is that the real temperature (external measurement) is off by **15°C**.

**Comment by sandmanRO** [comment]
I sent the email like 10 minutes ago. @discip, you sure you did not mix-up the builds? You get shorter to setpoint time with gain=1 as opposed to longer to reach setpoint time with gain=2? That does not make any sense.

**Comment by discip** [comment]
@sandmanRO
I am sure, because with **`gain=2`** the temperature overshoots by almost **30°C** and after that dangles around **`set temp` (320°C)** much longer than with **`gain=1`**.

**Comment by sandmanRO** [comment]
I see...so you are counting for the time the temperature stabilizes around setpoint not when the temperature reaches / exceeds the setpoint.

**Comment by Ralim** [comment]
Video is still _processing_ (whatever that really means) but should appear here at some point soon : https://youtu.be/O68aObWneFk @discip

**Comment by sandmanRO** [comment]
I feel like I'm missing the point. With the video I sent, you will see that with gain=1 the PID is actually "struggling" to reach the setpoint (the PID spends un unnecessarily long time to cope with the remaining 2-3C)

**Comment by sandmanRO** [comment]
It gets there eventually but much slower than it could. Now I'm curious what could be so different at hardware level that would lead to such totally opposed results.

**Comment by sandmanRO** [comment]
Not that is it really matters. As Ralim pointed out earlier, it's just a pure academic curiosity.

**Comment by discip** [comment]
@Ralim & @sandmanRO
Sorry just realized my tip (**TS-J02**) seems to be faulty, as the results with 2 other ones (TS-K4 & TS-B02) are much, much better.
I was some kind of chocked by the steadiness of the *temp ramp-up* on @sandmanROs iron.

Will test the ***`gain=2`** build* as well and report back accordingly.
Will also post videos.

**Comment by sandmanRO** [comment]
discip, please humor me. Could you please also check that you are using the very latest update that Ralim put out (the one that includes the limits on PID?). Your earlier results just throwed my brains into the bushes so please help me get them back.

**Comment by sandmanRO** [comment]
Now I can see them all. Indeed, that TS-J02 looks bad... definitely something is not right with that tip. Just don't put it aside though. If it's brand new, apparently the brand new tips are "temperamental". I recall when we purchased the TS100s, each unit came with a collection of 10 tips. At the first run it was scary... with something like +30 out of 40 tips, the temperature readings were jumping all over the place. Luckily the seller advised us to run the tips for a while at +300C then cool them off and retry. It's almost like something needs to meltdown inside the tip in order for it to work correctly afterwards (this is just a supposition as I could not find out how the inner connections between the connector, heater and thermcouple are done inside the tip).

**Comment by discip** [comment]
@Ralim & @sandmanRO
I have tested the ***`gain=2`** build* and this works, but no significant improvement.
If higher mass tips are served better with this, than this should stay.

## Thanks for the effort! ❤
Since the temp ramp-up chart belongs to the bad tip, I am going to remove it to not confuse people reading this.

**Comment by Ralim** [comment]
@sandmanRO 
That is an excellent note that tips need a run-in time. Doesn't surprise me given how they are manufactured.
In terms of construction, online there are deconstructions of the TS100 / Hakko T12 ones. Havent found ones for TS80 yet though.

Also very interesting to catch up on this. I'm thinking I'll merge it in since it seems to be working with the gain of `2`.
I also agree its a little academic, but it never hurts to discuss :)

**Comment by sandmanRO** [comment]
Hello Ralim, definitely it's a pleasure to see our minds interacting in real time. In a sense, the process is like a PID. We oscillate, we tune, sometimes we go baloney and overshoot....and yet, eventually we reach the best solution our minds could come up with. It might not be THE BEST solution in absolute terms (assuming such a thing exists) but as long as we are honest with the nature, and listen what it tells us, it can not be too far.

**Comment by Ralim** [comment]
Yeah absolutely, its very pleasurable to be working through these problems. I think much like most controller systems we converge on the best solution known at the time... Then a random @sandmanRO  comes along and disturbs the whole system with new information and a better solution is converged on 🙃  (That is meant as a compliment)

**Comment by sandmanRO** [comment]
Thank you, Sir! (I think I'm blushing right now)

**Pull request merged**
