### PR TITLE
fixing languages & reverting unwanted weblate changes

### LINKED ISSUE #1547: screen is "messed up" with the detailed soldering screen
**Describe the bug**
when the Pinecil goes to sleep after the timeout the sleeping screen is "messed up" and still shows the temp

**To Reproduce**
let the pinecil go to sleep while soldering with the detailed soldering screen

**Expected behavior**

should just say "Sleeping"

**Details of your device:**
 
 - Device: Pinecil V2
 - Release: 2.20.07D85C8
 - Power adapter being used: Anker Nano 2 with pine64 c-c cable

**Additional context**

for me this has reliably happened every time it sleeps. i have tried with the sleep timeout of 10 to 60secs. it goes away when you move the pinecil to wake it up

possibly related to #1417 

IMG_8947

### PR DESCRIPTION
**Pull request by discip**
fixes #1547
closes #1544

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
I have no clue what I should do to make shellcheck happy.
Please help.

**Comment by Ralim** [comment]
Oops looks like shellcheck is broken.
I can override it for now so no drama.

Also looks like Weblate doesnt have a way for me to stop it stripping these newlines so thinking of just removing it and trying to find another option. Thoughts?

**Comment by discip** [comment]
Newlines are not the problem, but the unit getting set to true is annoying.

I could have used Weblate to change that as well, but I'm not sure how strong the butterfly effect would be.

Unfortunately, I have no idea what other option to consider.

I will hereby also implement the changes pushed by weblate users.

**Comment by discip** [comment]
@Ralim
This is good to go now.
Also implemented the PRs made by weblate users #1544. 😊

**Comment by Ralim** [comment]
Thank you for doing this; going to take out weblate and look for a better option.

**Comment by discip** [comment]
As always:
Happy to be able to help. 😊

**Pull request merged**
